"""Shared constants for BioNodulo environment management.

Centralises executable → conda package and R package → conda package mappings
to avoid duplication between manifest.py, diagnostics.py, and resolver.py.
"""
from __future__ import annotations

# Aliases for conda package names that nodes commonly declare under their
# Python-import / pip name. The conda-forge/bioconda package name differs, so a
# raw REQUIRED_CONDA_PACKAGES entry like "torch" must be normalised to "pytorch"
# or the solver reports "No candidates were found".
CONDA_PACKAGE_ALIASES: dict[str, str] = {
    "torch": "pytorch",
    "sklearn": "scikit-learn",
    "scikit_learn": "scikit-learn",
    "opencv-python": "opencv",
    "pillow": "pillow",
    "bio": "biopython",
    "biopython-bio": "biopython",
    # ViennaRNA ships as the bioconda package "viennarna"; the RNA structure
    # nodes declare the hyphenated upstream project name.
    "vienna-rna": "viennarna",
}


def normalize_conda_package(name: str) -> str:
    """Return the conda-forge/bioconda package name for a declared dependency."""
    if not name:
        return name
    base = name.strip()
    return CONDA_PACKAGE_ALIASES.get(base, base)


# Mapping of executable names to conda package names.
# This is the single source of truth for tool → package resolution.
EXECUTABLE_TO_CONDA_PACKAGE: dict[str, str] = {
    # bunzip2 is a binary shipped by the `bzip2` package; there is no conda
    # package of that name, so an unmapped entry produces an unsolvable
    # dependency. A dev box hides this by resolving bunzip2 from /usr/bin.
    "bunzip2": "bzip2",
    "bzip2": "bzip2",
    "bwa": "bwa",
    "bwa-mem2": "bwa-mem2",
    "blastn": "blast",
    "blastp": "blast",
    "blastx": "blast",
    "tblastn": "blast",
    "tblastx": "blast",
    "prefetch": "sra-tools",
    "fasterq-dump": "sra-tools",
    "bowtie2": "bowtie2",
    "bowtie2-build": "bowtie2",
    "bowtie2-inspect": "bowtie2",
    "hisat2": "hisat2",
    "hisat2-build": "hisat2",
    "STAR": "star",
    "minimap2": "minimap2",
    "salmon": "salmon",
    "kallisto": "kallisto",
    "samtools": "samtools",
    "bamleftalign": "freebayes",
    "mosdepth": "mosdepth",
    "rasusa": "rasusa",
    "samblaster": "samblaster",
    "bcftools": "bcftools",
    "gffread": "gffread",
    "seqtk": "seqtk",
    "gatk": "gatk4",
    "freebayes": "freebayes",
    "vcftools": "vcftools",
    "vcfanno": "vcfanno",
    "rtg": "rtg-tools",
    "Platypus.py": "platypus-variant",
    "run_deepvariant": "deepvariant",
    "run_clair3.sh": "clair3",
    "sniffles": "sniffles",
    "pbsv": "pbsv",
    "SURVIVOR": "survivor",
    "cuteSV": "cute-sv",
    "svim": "svim",
    "smoove": "smoove",
    "delly": "delly",
    "gridss": "gridss",
    "configureStrelkaGermlineWorkflow.py": "strelka",
    "configureStrelkaSomaticWorkflow.py": "strelka",
    "configManta.py": "manta",
    "runWorkflow.py": "manta",
    "cnvkit.py": "cnvkit",
    "cnvnator": "cnvnator",
    "freec": "control-freec",
    "modkit": "ont-modkit",
    "chopper": "chopper",
    "NanoPlot": "nanoplot",
    "medaka_consensus": "medaka",
    # Dorado is provisioned from ONT's official release archive in the worker image.
    "dorado": "",
    "fastqc": "fastqc",
    "multiqc": "multiqc",
    "qualimap": "qualimap",
    "fastp": "fastp",
    "trimmomatic": "trimmomatic",
    "cutadapt": "cutadapt",
    "trim_galore": "trim-galore",
    "spades.py": "spades",
    "megahit": "megahit",
    "canu": "canu",
    "flye": "flye",
    "unicycler": "unicycler",
    "quast": "quast",
    "prokka": "prokka",
    "bakta": "bakta",
    "emapper.py": "eggnog-mapper",
    "mafft": "mafft",
    "clustalo": "clustal-omega",
    "muscle": "muscle",
    "trimal": "trimal",
    "iqtree": "iqtree",
    "iqtree2": "iqtree",
    "FastTree": "fasttree",
    "raxmlHPC": "raxml",
    "raxmlHPC-PTHREADS": "raxml",
    "raxml-ng": "raxml-ng",
    "modeltest-ng": "modeltest-ng",
    "astral": "astral-tree",
    "nucmer": "mummer4",
    "dnadiff": "mummer4",
    "delta-filter": "mummer4",
    "show-coords": "mummer4",
    "show-snps": "mummer4",
    "mummer": "mummer4",
    "mummerplot": "mummer4",
    "gnuplot": "gnuplot",
    "featureCounts": "subread",
    "stringtie": "stringtie",
    "kraken2": "kraken2",
    "kraken2-build": "kraken2",
    "bracken": "bracken",
    "metaphlan": "metaphlan",
    "humann": "humann",
    "ktImportTaxonomy": "krona",
    "run_MaxBin.pl": "maxbin2",
    "checkm": "checkm-genome",
    "macs2": "macs2",
    "bedtools": "bedtools",
    "bismark": "bismark",
    "bismark_genome_preparation": "bismark",
    "bismark_methylation_extractor": "bismark",
    "MethylDackel": "methyldackel",
    "bamCoverage": "deeptools",
    "computeMatrix": "deeptools",
    "plotHeatmap": "deeptools",
    "plotProfile": "deeptools",
    "HiC-Pro": "",
    "juicer.sh": "",
    "cooler": "cooler",
    "cooltools": "cooltools",
    "maxquant": "maxquant",
    "mono": "mono",
    "msfragger": "msfragger",
    "fragpipe": "fragpipe",
    "sage": "sage-proteomics",
    "comet": "comet-ms",
    "percolator": "percolator",
    "FeatureFinderCentroided": "openms",
    "diann": "",
    # SIRIUS is distributed through its own licensed installer, not Conda.
    "sirius": "",
    "mzmine": "mzmine",
    # 10x binaries require external licensed installations.
    "spaceranger": "",
    "baysor": "baysor",
    "cellranger": "",
    "colabfold_batch": "colabfold",
    "esm-fold": "",
    "cp": "coreutils",
    "ln": "coreutils",
    "mkdir": "coreutils",
    "tee": "coreutils",
    "python": "python",
    "snpEff": "snpeff",
    "java": "openjdk",
    "dot": "graphviz",
    "vep": "ensembl-vep",
    # ANNOVAR is a licensed user-supplied distribution, not a Conda package.
    "table_annovar.pl": "",
    "convert2annovar.pl": "",
    "interproscan.sh": "interproscan",
    "aws": "awscli",
    "bwrap": "bubblewrap",
    "CRISPResso": "crispresso2",
    "mageck": "mageck",
    # MAGeCK ships these helper executables in the same ``mageck`` package.
    # Treating their binary names as Conda package names makes Pixi solve for
    # nonexistent ``RRA`` and ``mageckGSEA`` packages.
    "RRA": "mageck",
    "mageckGSEA": "mageck",
    "cas-offinder": "cas-offinder",
    "odgi": "odgi",
    "pggb": "pggb",
    "cactus": "cactus",
    "cactus-pangenome": "cactus",
    "hal2maf": "cactus",
    "hal2vg": "cactus",
    "hal2assemblyHub.py": "cactus",
    "panacus": "panacus",
    "panaroo": "panaroo",
    "vg": "vg",
    "minigraph": "minigraph",
    "vcfwave": "vcflib",
    "vcfdecompose": "vcflib",
    "vcfallelicprimitives": "vcflib",
    "bgzip": "htslib",
    "tabix": "htslib",
    "tar": "tar",
    "Rscript": "r-base",
    "CopasiSE": "",
    "iBioSim": "",
    "ibiosim": "",
    # ViennaRNA executables all ship inside the bioconda "viennarna" package.
    "RNAfold": "viennarna",
    "RNAplfold": "viennarna",
    "RNAeval": "viennarna",
}

# Mapping of R packages to conda package names.
R_PACKAGE_TO_CONDA_PACKAGE: dict[str, str] = {
    "ggplot2": "r-ggplot2",
    "ashr": "r-ashr",
    "readr": "r-readr",
    "dplyr": "r-dplyr",
    "tidyr": "r-tidyr",
    "patchwork": "r-patchwork",
    "Seurat": "r-seurat",
    "pheatmap": "r-pheatmap",
    "DESeq2": "bioconductor-deseq2",
    "edgeR": "bioconductor-edger",
    "limma": "bioconductor-limma",
    "Biostrings": "bioconductor-biostrings",
    "DSS": "bioconductor-dss",
    "xcms": "bioconductor-xcms",
    "CAMERA": "bioconductor-camera",
    "BiocParallel": "bioconductor-biocparallel",
    "jsonlite": "r-jsonlite",
    "GenomicRanges": "bioconductor-genomicranges",
    "ape": "r-ape",
    "vegan": "r-vegan",
    "ComplexHeatmap": "bioconductor-complexheatmap",
    "RColorBrewer": "r-rcolorbrewer",
    "rtracklayer": "bioconductor-rtracklayer",
    "summarizedexperiment": "bioconductor-summarizedexperiment",
    "tximport": "bioconductor-tximport",
}

# Minimum version constraints for critical bioinformatics tools.
# Used by generate_manifest() to ensure reproducible behaviour.
PACKAGE_MIN_VERSIONS: dict[str, str] = {
    "bwa": "0.7.19",
    "bwa-mem2": "2.3",
    "bowtie2": "2.5.5",
    "samtools": "==1.23.1",
    "mosdepth": "0.3.14",
    "rasusa": "4.1.0",
    "samblaster": "0.1.26",
    "bcftools": "1.24",
    "gffread": ">=0.12.7",
    "seqtk": "1.4",
    "gatk4": "4.6.2.0",
    "star": "2.7.11b",
    "spades": "4.2.0",
    "fastqc": "0.12.1",
    "multiqc": "1.33",
    "blast": "2.17.0",
    "sra-tools": "3.4.1",
    "biopython": "1.87",
    "hisat2": "2.2.2",
    "minimap2": "2.30",
    "salmon": "2.3.4",
    "kallisto": "0.52.0",
    "freebayes": "1.3.10",
    "vcftools": ">=0.1.16",
    "vcfanno": "0.3.9",
    "rtg-tools": ">=3.12",
    "platypus-variant": ">=0.8.1",
    "deepvariant": ">=1.6.0",
    "clair3": ">=2.0.1",
    "sniffles": ">=2.5.0",
    "pbsv": ">=2.10.0",
    "survivor": ">=1.0.7",
    "cute-sv": ">=2.1.1",
    "svim": ">=2.0.0",
    "smoove": ">=0.2.8",
    "lumpy-sv": ">=0.3.1",
    "svtyper": ">=0.7.1",
    "delly": "1.2.6",
    "gridss": ">=2.13.2",
    "strelka": ">=2.9.10",
    "manta": "1.6.0",
    "rseqc": "5.0.3",
    "cnvkit": "0.9.12",
    "cnvnator": ">=0.4.1",
    "control-freec": ">=11.6",
    "ont-modkit": "0.4.3",
    "chopper": "0.9.2",
    "pod5": "0.3.44",
    "vienna-rna": ">=2.7.0",
    "viennarna": ">=2.7.0",
    "nanoplot": "1.44.1",
    "medaka": "2.0.1",
    "fastp": "0.24.0",
    "trimmomatic": "0.40",
    "cutadapt": "5.2",
    "trim-galore": "0.6.10",
    "megahit": "1.2.9",
    "canu": "2.3",
    "flye": "2.9.6",
    "unicycler": "0.5.1",
    "quast": "5.3.0",
    "prokka": "1.15.6",
    "bakta": "1.9.4",
    "eggnog-mapper": "2.1.14",
    "mafft": "7.525",
    "clustal-omega": ">=1.2.4",
    "muscle": "5.3",
    "trimal": "1.4.1",
    "iqtree": "2.3.4",
    "fasttree": ">=2.1.11",
    "raxml": ">=8.2.12",
    "raxml-ng": ">=1.2.2",
    "modeltest-ng": ">=0.1.7",
    "astral-tree": ">=5.7.8",
    "mummer4": "4.0.1",
    "gnuplot": ">=6.0.4",
    "subread": "2.1.1",
    "qualimap": "2.3",
    "stringtie": "3.0.3",
    "kraken2": "2.17.1",
    "bracken": "3.1",
    "metaphlan": "4.2.4",
    "humann": "3.9",
    # NanoPlot's nanoplotter imports `kaleido.scopes.plotly`, removed in kaleido
    # 1.x. bioconda's nanoplot 1.44.1 declares no ceiling, so a free solver
    # installs 1.3 and NanoPlot dies at import. The conda package is named
    # python-kaleido; there is no conda-forge package called `kaleido`.
    "python-kaleido": "0.2.1",
    # pysbol3 1.1 hard-requires pyshacl ~=0.18.1, which imports pkg_resources.
    # setuptools 81 removed pkg_resources, so setuptools is held below it. Moving
    # pyshacl forward is not an option -- pysbol3 pins it.
    "setuptools": "80.10.2",
    # bioconda's humann 3.9 is a py312 build that installs into
    # lib/python3.12/site-packages but declares only `python >=3`. A solver left
    # free picks 3.13 and `humann` then dies with ModuleNotFoundError. This was
    # invisible while humann shared an env with metaphlan (which pins 3.12);
    # isolating humann exposed the upstream packaging bug. Nodes needing humann
    # list `python` explicitly so this pin reaches their environment.
    "python": "3.12.*",
    "krona": "2.8.1",
    "maxbin2": "2.2.7",
    "checkm-genome": "1.2.5",
    "macs2": "2.2.9.1",
    "bedtools": "2.31.1",
    "bedops": "2.4.42",
    "lofreq": "2.1.5",
    "freyja": "2.0.1",
    "preseq": "3.2.0",
    "abyss": "2.3.10",
    "bayescan": "2.1",
    "bellerophon": "1.0",
    "chromeister": "1.5.a",
    "pybigtools": "0.2.5",
    "ampligone": "2.0.1",
    "binette": "1.2.1",
    "binning_refiner": "1.4.3",
    "python-bioext": "0.21.10",
    "pybigwig": "0.3.24",
    "pysam": "0.23.3",
    "beagle": "5.4_29Oct24.c8e",
    "breseq": "0.35.5",
    "biscot": "2.3.3",
    "bigscape": "1.1.9",
    "compleasm": "0.2.6",
    "eastr-cpp": "2.1.1",
    "export2graphlan": "0.20",
    "graphlan": "1.1.3",
    "exonerate": "2.4.0",
    "evidencemodeler": "2.1.0",
    "comebin": "1.0.4",
    "drep": "3.6.2",
    "cami-amber": "2.0.7",
    "biobox_add_taxid": "1.2",
    "fargene": "0.1",
    "metabat2": "2.18.23",
    "fastspar": "1.0.0",
    "ivar": "1.4.4",
    "gtdbtk": "2.7.2",
    "litellm": "1.87.1",
    "transformers": "4.57.1",
    "datasets": "4.4.1",
    "peft": "0.18.0",
    "accelerate": "1.14.0",
    "numpy": "2.4.4",
    "diamond": "2.2.2",
    "hmmer": "3.4",
    "mmseqs2": "17-b804f",
    "kaiju": "1.10.1",
    "kraken": "1.1.1",
    "centrifuge": "1.0.4_beta",
    "beacon2-import": "2.2.4",
    "anise_basil": "1.2.0",
    "anndata2ri": "1.3.2",
    "argnorm": "1.0.0",
    "autobigs-cli": "0.6.2",
    "b2btools": "3.0.5",
    "baredsc": "1.1.3",
    "bax2bam": "0.0.11",
    "berokka": "0.2.3",
    "bioconductor-cemitool": "1.34.0",
    "bioconductor-singlecellexperiment": "1.24.0",
    "bioconductor-org.hs.eg.db": "3.18.0",
    "bioconductor-org.mm.eg.db": "3.18.0",
    "bioconductor-org.dm.eg.db": "3.18.0",
    "bioconductor-org.dr.eg.db": "3.18.0",
    "bioconductor-org.rn.eg.db": "3.18.0",
    "bioconductor-org.at.tair.db": "3.18.0",
    "bioconductor-org.gg.eg.db": "3.18.0",
    "bioconductor-org.bt.eg.db": "3.18.0",
    "cd-hit": "4.8.1",
    "celltypist": "1.7.1",
    "coreutils": "9.5",
    "datamash": "1.9",
    "falco": "1.3.2",
    "gawk": "4.1.3",
    "gzip": "1.13",
    "loompy": "3.0.8",
    "mlst": "2.22.0",
    "perl-bioperl": "1.7.2",
    "r-matrix": "1.2-12",
    "scipy": "1.14.0",
    "seqsero2": "1.3.2",
    "ucsc-bedgraphtobigwig": "455",
    "cramino": "1.3.0",
    "bamutil": "1.0.15",
    "bismark": "3.1.0",
    "methyldackel": "0.6.1",
    "deeptools": "3.5.6",
    "cooler": "0.10.2",
    "cooltools": "0.7.0",
    "maxquant": "2.0.3.0",
    "msfragger": "4.2",
    "fragpipe": "24.0",
    "sage-proteomics": "0.14.7",
    "comet-ms": "2024011",
    "percolator": "3.7.1",
    "openms": "3.5.0",
    "mono": "6.12.*",
    "baysor": "0.7.1",
    "colabfold": "1.5.5",
    "fair-esm": ">=2.0.0",
    "squidpy": "1.8.2",
    "cell2location": ">=0.1",
    "torch": ">=2.0",
    "pytorch": ">=2.0",
    "snpeff": "5.2",
    "openjdk": ">=17",
    "ensembl-vep": "113.4",
    "interproscan": "5.59_91.0",
    "awscli": "2.36.2",
    "bubblewrap": "0.11.2",
    "crispresso2": "2.3.4",
    "mageck": "0.5.9.5",
    "cas-offinder": "2.4.1",
    "odgi": "0.9.2",
    "pggb": "0.7.4",
    "cactus": "2.9.9",
    "panacus": "0.3.3",
    "panaroo": "1.5.0",
    "vg": "1.63.1",
    "minigraph": "0.21",
    "vcflib": "1.0.9",
    "htslib": "1.23.1",
    "tar": ">=1.34",
    "scanpy": "1.12.2",
    "python-igraph": "1.0.0",
    "anndata": ">=0.10",
    "pandas": "2.3.3",
    "matplotlib": "3.10.9",
    "psutil": "7.2.2",
    "pysbol3": "1.1",
    "bioconductor-xcms": "4.8.0",
    "bioconductor-camera": "1.66.0",
    "bioconductor-msexperiment": "1.12.0",
    "bioconductor-biocparallel": "1.44.0",
    "r-jsonlite": "2.0.0",
    "mzmine": "4.7.29",
    "r-base": "4.5.3",
    "r-seurat": "5.3.1",
    "r-ggplot2": "4.0.3",
    "r-patchwork": ">=1.2",
    "r-dplyr": ">=1.1.0",
    "r-tidyr": ">=1.3.0",
    "r-readr": "2.2.0",
    "r-pheatmap": "1.0.13",
    "r-ashr": "2.2_63",
    "bioconductor-deseq2": "1.50.2",
    "bioconductor-dss": "2.58.0",
    "bioconductor-edger": ">=3.42.0",
    "bioconductor-limma": ">=3.56.0",
    "bioconductor-biostrings": "2.78.0",
    "bioconductor-genomicranges": ">=1.52.0",
    "r-ape": ">=5.7.0",
    "r-vegan": ">=2.6.0",
    "bioconductor-complexheatmap": ">=2.16.0",
    "r-rcolorbrewer": ">=1.1.3",
    "bioconductor-rtracklayer": ">=1.60.0",
    "bioconductor-summarizedexperiment": ">=1.30.0",
    "bioconductor-tximport": ">=1.28.0",
}


# Exact package builds required for runtime compatibility.  MACS2's newer
# Bioconda py311 builds (_4/_5) import a ScoreTrack extension that references
# the unavailable ``__log_finite`` symbol.  Bioconda issue #59362 records the
# broken build, and Galaxy confirmed py311hdad781d_1 as the working 2.2.9.1
# build: https://github.com/usegalaxy-it/usegalaxy-it-tools/issues/2
PACKAGE_BUILD_CONSTRAINTS: dict[str, str] = {
    "macs2": "py311hdad781d_1",
}
