"""Platforms each committed environment is proven to solve for.

GENERATED by scripts/solve_macos_locks.py -- do not edit by hand.

Keyed by environment id (the package-set hash used for lock directory
names). An id absent from this table falls back to linux-64 only, so a
new environment is cloud-runnable before anyone has solved it for macOS.
"""

from __future__ import annotations

ENVIRONMENT_PLATFORMS: dict[str, tuple[str, ...]] = {
    "09d7c399ebb440f1": ("linux-64", "osx-64",),
    "0e5d735f7d9f2b5e": ("linux-64",),
    "10309abc3ac96f18": ("linux-64", "osx-64", "osx-arm64",),
    "1a89a3a68159a5d6": ("linux-64",),
    "3ba39594c49f0bb7": ("linux-64", "osx-64",),
    "4525a2e47cb49dec": ("linux-64", "osx-64", "osx-arm64",),
    "49242a6d8b2706ab": ("linux-64",),
    "4997531d441c35bf": ("linux-64",),
    "5789cfdfd03011a4": ("linux-64",),
    "5d721750b2649072": ("linux-64", "osx-64",),
    "5f56c77e87adf0dc": ("linux-64",),
    "7d22b66cc905eb5b": ("linux-64", "osx-64",),
    "7d364ae8e470841b": ("linux-64", "osx-64", "osx-arm64",),
    "803d9373dfa0b9cf": ("linux-64", "osx-64", "osx-arm64",),
    "85d423ef3183a8d5": ("linux-64", "osx-64",),
    "a3e1f5870a14637e": ("linux-64", "osx-64",),
    "a68e1929ede4348b": ("linux-64", "osx-64", "osx-arm64",),
    "a6d14540abf27c14": ("linux-64", "osx-64",),
    "a8aef18369bd202f": ("linux-64", "osx-64", "osx-arm64",),
    "b1d26aeb7a0b7724": ("linux-64", "osx-64",),
    "c6d3f5ee829887e8": ("linux-64",),
    "d1da0215b6844355": ("linux-64", "osx-64", "osx-arm64",),
    "d8d178d661ee5f33": ("linux-64", "osx-64", "osx-arm64",),
    "e592d5261ff94f83": ("linux-64",),
    "e7d71a57eedc92e4": ("linux-64",),
    "f0de6090a16f168f": ("linux-64", "osx-64", "osx-arm64",),
    "f77d48a3c217508c": ("linux-64", "osx-64", "osx-arm64",),
    "fba79120211a36f0": ("linux-64", "osx-64", "osx-arm64",),
    "fe6ff92bde2d33dc": ("linux-64", "osx-64", "osx-arm64",),
}
