"""Compatibility imports for focused BEDTools and BEDOPS nodes."""

# ruff: noqa: F401
from __future__ import annotations

from bionodulo.nodes.builtin.bedops_family.sort_bed import BEDOPSSortBedNode
from bionodulo.nodes.builtin.bedops_family.sort_bed_alias import BEDOPSSortBedGalaxyNode
from bionodulo.nodes.builtin.bedtools_family.annotate import BEDToolsAnnotateNode
from bionodulo.nodes.builtin.bedtools_family.bamtobed import BEDToolsBamToBedNode
from bionodulo.nodes.builtin.bedtools_family.bed12tobed6 import BEDToolsBed12ToBed6Node
from bionodulo.nodes.builtin.bedtools_family.bedpetobam import BEDToolsBedpeToBamNode
from bionodulo.nodes.builtin.bedtools_family.bedtobam import BEDToolsBedToBamNode
from bionodulo.nodes.builtin.bedtools_family.bedtoigv import BEDToolsBedToIgvNode
from bionodulo.nodes.builtin.bedtools_family.closestbed import BEDToolsClosestBedNode
from bionodulo.nodes.builtin.bedtools_family.cluster import BEDToolsClusterNode
from bionodulo.nodes.builtin.bedtools_family.complement import BEDToolsComplementNode
from bionodulo.nodes.builtin.bedtools_family.coverage import BEDToolsCoverageNode
from bionodulo.nodes.builtin.bedtools_family.expand import BEDToolsExpandNode
from bionodulo.nodes.builtin.bedtools_family.fisher import BEDToolsFisherNode
from bionodulo.nodes.builtin.bedtools_family.flank import BEDToolsFlankNode
from bionodulo.nodes.builtin.bedtools_family.genomecov import BEDToolsGenomeCoverageNode
from bionodulo.nodes.builtin.bedtools_family.getfasta import BEDToolsGetFastaNode
from bionodulo.nodes.builtin.bedtools_family.groupby import BEDToolsGroupByNode
from bionodulo.nodes.builtin.bedtools_family.intersectbed import BEDToolsIntersectBedNode
from bionodulo.nodes.builtin.bedtools_family.jaccard import BEDToolsJaccardNode
from bionodulo.nodes.builtin.bedtools_family.links import BEDToolsLinksNode
from bionodulo.nodes.builtin.bedtools_family.makewindows import BEDToolsMakeWindowsNode
from bionodulo.nodes.builtin.bedtools_family.map import BEDToolsMapNode
from bionodulo.nodes.builtin.bedtools_family.maskfasta import BEDToolsMaskFastaNode
from bionodulo.nodes.builtin.bedtools_family.merge import BEDToolsMergeNode
from bionodulo.nodes.builtin.bedtools_family.multicov import BEDToolsMultiCovNode
from bionodulo.nodes.builtin.bedtools_family.multiinter import BEDToolsMultiIntersectNode
from bionodulo.nodes.builtin.bedtools_family.nuc import BEDToolsNucNode
from bionodulo.nodes.builtin.bedtools_family.overlap import BEDToolsOverlapBedNode
from bionodulo.nodes.builtin.bedtools_family.random import BEDToolsRandomNode
from bionodulo.nodes.builtin.bedtools_family.reldist import BEDToolsRelativeDistanceNode
from bionodulo.nodes.builtin.bedtools_family.shuffle import BEDToolsShuffleNode
from bionodulo.nodes.builtin.bedtools_family.slop import BEDToolsSlopNode
from bionodulo.nodes.builtin.bedtools_family.sort import BEDToolsSortNode
from bionodulo.nodes.builtin.bedtools_family.spacing import BEDToolsSpacingNode
from bionodulo.nodes.builtin.bedtools_family.subtract import BEDToolsSubtractNode
from bionodulo.nodes.builtin.bedtools_family.tag import BEDToolsTagBedNode
from bionodulo.nodes.builtin.bedtools_family.unionbedg import BEDToolsUnionBedGraphNode
from bionodulo.nodes.builtin.bedtools_family.window import BEDToolsWindowNode
