"""Compatibility facade for focused protein and taxonomy wrapper nodes."""
# ruff: noqa: F401

from bionodulo.nodes.builtin.wrapped_protein_taxonomy_family import (
    Beacon2AnalysesNode,
    Beacon2BiosamplesNode,
    Beacon2BracketNode,
    Beacon2CNVNode,
    Beacon2CohortsNode,
    Beacon2DatasetsNode,
    Beacon2GeneNode,
    Beacon2IndividualsNode,
    Beacon2RangeNode,
    Beacon2RunsNode,
    Beacon2SequenceNode,
    CentrifugeNode,
    DiamondAlignNode,
    DiamondMakeDBNode,
    GalaxyDiamondMakeDBNode,
    GalaxyDiamondNode,
    GalaxyDiamondViewNode,
    HMMERAlimaskNode,
    HMMERHmmalignNode,
    HMMERHmmbuildNode,
    HMMERHmmconvertNode,
    HMMERHmmemitNode,
    HMMERHmmfetchNode,
    HMMERHmmscanNode,
    HMMERHmmsearchNode,
    HMMERJackhmmerNode,
    HMMERNhmmerNode,
    HMMERNhmmscanNode,
    HMMERPhmmerNode,
    Kaiju2KronaNode,
    Kaiju2TableNode,
    KaijuAddTaxonNamesNode,
    KaijuMergeOutputsNode,
    KaijuNode,
    KrakenFilterNode,
    KrakenMpaReportNode,
    KrakenNode,
    KrakenReportNode,
    KrakenTranslateNode,
    MMseqs2EasyClusterNode,
    MMseqs2EasyLinclustNode,
    MMseqs2EasyLinsearchNode,
    MMseqs2EasyRBHNode,
    MMseqs2EasySearchNode,
    MMseqs2EasyTaxonomyNode,
    MMseqs2TaxonomyAssignmentNode,
)

__all__ = [name for name in globals() if name.endswith("Node")]
