"""Compatibility facade for focused assembly and typing wrapper nodes."""
# ruff: noqa: F401

from bionodulo.nodes.builtin.wrapped_assembly_typing_family import (
    ABRicateListNode,
    ABRicateNode,
    ABRicateSummaryNode,
    BandageImageNode,
    BandageInfoNode,
    CheckM2Node,
    CheckMAnalyzeNode,
    CheckMLineageSetNode,
    CheckMLineageWFNode,
    CheckMPlotNode,
    CheckMQANode,
    CheckMTaxonSetNode,
    CheckMTaxonomyWFNode,
    CheckMTetraNode,
    CheckMTreeNode,
    CheckMTreeQANode,
    CheRRIEvalNode,
    CheRRITrainNode,
    ChewBBACAAlleleCallEvaluatorNode,
    ChewBBACAAlleleCallNode,
    ChewBBACACreateSchemaNode,
    ChewBBACADownloadSchemaNode,
    ChewBBACAExtractCgMLSTNode,
    ChewBBACAJoinProfilesNode,
    ChewBBACANSStatsNode,
    ChewBBACAPrepExternalSchemaNode,
    ChiraCollapseNode,
    ChiraExtractNode,
    ChiraMapNode,
    ChiraMergeNode,
    ChiraQuantifyNode,
    DASToolNode,
    FastaToContig2BinNode,
    GfaToFaNode,
    KleborateNode,
    PlasmidFinderNode,
    RavenNode,
    ShovillNode,
    SnippyCleanFullAlnNode,
    SnippyCoreNode,
    SnippyNode,
    StaramrSearchNode,
)

__all__ = [name for name in globals() if name.endswith("Node")]
