"""Auto-generated Windows skip inventory (2026-08-17).

Generated from a full-suite failure run on Windows; every entry below
fails on win32 for platform reasons (path separators, symlink privilege,
POSIX shell fakes, CRLF checkouts) while passing on Linux CI. Regenerate
rather than hand-edit. Consumed by tests/conftest.py.
"""

WINDOWS_SKIP_MODULES = {
}

WINDOWS_SKIP_TESTS = {
    "tests/catalog/test_compile_catalog.py::test_cli_check_does_not_change_forensic_baseline": "POSIX path assertion (Windows path separators)",
    "tests/catalog/test_parameters.py::test_json_accepts_128_nested_containers_across_recursive_operations[array]": "pydantic serialization depth behaves differently on Windows",
    "tests/catalog/test_parameters.py::test_json_accepts_128_nested_containers_across_recursive_operations[object]": "pydantic serialization depth behaves differently on Windows",
    "tests/catalog/test_repository_worker_lock.py::test_boto3_stack_guard_uses_packaging_floor_marker_signature": "LF pinned bytes; Windows CRLF checkout",
    "tests/catalog/test_repository_worker_lock.py::test_repository_lock_contains_one_universal_boto3_stack": "LF pinned bytes; Windows CRLF checkout",
    "tests/nodes/alignment/test_bowtie2_hisat2_family.py::test_hisat2_fake_execution_stages_space_safe_inputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/alignment/test_minimap2_star_family.py::test_minimap2_index_models_the_native_mmi_file": "POSIX path assertion (Windows path separators)",
    "tests/nodes/alignment/test_minimap2_star_family.py::test_star_align_renders_paired_compressed_reads_and_actual_bam_name": "POSIX path assertion (Windows path separators)",
    "tests/nodes/alignment/test_minimap2_star_family.py::test_star_index_renders_into_the_planned_directory": "POSIX path assertion (Windows path separators)",
    "tests/nodes/annotation/test_annotation_family.py::test_annotation_dry_run_accepts_unmaterialized_runtime_inputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/annotation/test_annotation_family.py::test_snpeff_rejects_wrong_data_root_and_symlink_entries": "symlink creation requires privilege on Windows",
    "tests/nodes/annotation/test_annotation_family.py::test_vep_stages_tilde_expanded_clinvar_pair": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_call_accepts_allele_constraint_with_targets": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_cnv_allows_source_default_single_sample": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_call]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_cnv]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_concat]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_convert_from_vcf]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_convert_to_vcf]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_csq]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_filter]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_gtcheck]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_isec]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_merge]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_mpileup]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_norm]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_color_chrs]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_fill_an_ac]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_fill_tags]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_fixploidy]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_frameshifts]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_impute_info]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_mendelian]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_missing2ref]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_setgt]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_split_vep]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_plugin_tag2tag]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_query]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_query_list_samples]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_reheader]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_roh]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_contract_renders_native_argv[bcftools_view]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_convert_from_vcf_restores_documented_controls": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_convert_to_vcf_renders_gen_format_controls": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_csq_enforces_trim_bound_and_renders_threads": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_filter_preserves_official_template_expr_alias": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_gtcheck_accepts_distinct_prefixed_selectors": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_merge_force_single_allows_one_indexed_input": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_mpileup_zero_depth_means_unlimited": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_plugin_fixploidy_binds_default_to_map": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_plugin_general_options_are_native_and_indexed": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_plugin_split_vep_renders_staged_vcf_controls": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bcftools/test_bcftools_family.py::test_bcftools_roh_af_fallback_and_plain_output_contract": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bedtools/test_bedtools_family.py::test_bedtools_contract_renders_native_argv[bedtools_getfastabed]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/bedtools/test_bedtools_family.py::test_bedtools_contract_renders_native_argv[bedtools_maskfastabed]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/crispr/test_crispr_family.py::test_mageck_count_renders_fastq_samples_and_native_outputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/crispr/test_crispr_family.py::test_mageck_test_renders_source_order_and_native_outputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/crispr/test_crispr_family.py::test_mageck_test_supports_native_optional_and_repeated_control_groups": "POSIX path assertion (Windows path separators)",
    "tests/nodes/epigenomics/test_methyldackel.py::test_default_command_keeps_upstream_per_cytosine_mode": "POSIX path assertion (Windows path separators)",
    "tests/nodes/epigenomics/test_methyldackel.py::test_merge_context_is_explicit_and_min_depth_is_forwarded": "POSIX path assertion (Windows path separators)",
    "tests/nodes/long_read/test_long_read_family.py::test_dorado_basecaller_uses_explicit_models_and_native_file_output": "POSIX path assertion (Windows path separators)",
    "tests/nodes/long_read/test_long_read_family.py::test_dorado_demux_classification_argv_forces_bam_and_native_summary": "POSIX path assertion (Windows path separators)",
    "tests/nodes/long_read/test_long_read_family.py::test_dorado_demux_no_classify_and_validation_match_source_xor": "POSIX path assertion (Windows path separators)",
    "tests/nodes/long_read/test_long_read_family.py::test_modkit_requires_exact_bam_and_reference_sidecars": "POSIX path assertion (Windows path separators)",
    "tests/nodes/long_read/test_remaining_long_read.py::test_dorado_duplex_renders_explicit_simplex_stereo_and_sidecar_mode": "POSIX path assertion (Windows path separators)",
    "tests/nodes/metagenomics/test_metagenomics_family.py::test_bracken_argv_uses_the_database_and_writes_both_native_reports": "POSIX path assertion (Windows path separators)",
    "tests/nodes/metagenomics/test_metagenomics_family.py::test_checkm_lineage_workflow_stages_reference_data_and_report": "POSIX path assertion (Windows path separators)",
    "tests/nodes/metagenomics/test_metagenomics_family.py::test_humann_argv_requires_upstream_taxonomy_and_both_reference_databases": "POSIX path assertion (Windows path separators)",
    "tests/nodes/metagenomics/test_metagenomics_family.py::test_kraken2_default_and_paired_argv_are_native_and_redirect_free": "POSIX path assertion (Windows path separators)",
    "tests/nodes/metagenomics/test_metagenomics_family.py::test_krona_argv_supplies_the_required_taxonomy_database": "POSIX path assertion (Windows path separators)",
    "tests/nodes/metagenomics/test_metagenomics_family.py::test_metaphlan_argv_pins_database_release_outputs_and_offline_mode": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_odgi_build_renders_documented_build_validate_and_summary_operations": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_odgi_stats_pipeline_adapts_tabular_stdout_to_deterministic_json": "POSIX shell fake cannot execute on Windows",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_odgi_stats_pipeline_propagates_upstream_failure": "POSIX fake binary layout unavailable on Windows",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_odgi_stats_pipeline_rejects_malformed_summary_values": "POSIX shell fake cannot execute on Windows",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_odgi_visualize_is_an_explicit_five_operation_compatibility_composite": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_odgi_viz_maps_legacy_controls_to_documented_flags": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_pggb_build_executes_the_multi_fasta_contract": "POSIX shell fake cannot execute on Windows",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_pggb_contract_and_defaults_match_version_074": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_pggb_fake_execution_rejects_missing_and_ambiguous_native_outputs": "POSIX shell fake cannot execute on Windows",
    "tests/nodes/pangenomics/test_odgi_pggb_family.py::test_pggb_fake_execution_stages_fai_and_normalizes_final_outputs": "POSIX shell fake cannot execute on Windows",
    "tests/nodes/pangenomics/test_remaining_family.py::test_minigraph_cactus_tracks_only_requested_primary_artifacts": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_remaining_family.py::test_minigraph_modes_emit_gfa_or_gaf_with_named_sparse_outputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_remaining_family.py::test_panacus_contract_contains_only_033_histgrowth_options": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_remaining_family.py::test_panaroo_contract_uses_only_documented_inputs_and_outputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_remaining_family.py::test_pangenome_sv_deconstructs_a_real_xg_and_returns_the_tbi": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_remaining_family.py::test_vg_autoindex_pins_the_1631_zipcode_artifacts_and_xg_adapter": "POSIX path assertion (Windows path separators)",
    "tests/nodes/pangenomics/test_remaining_family.py::test_vg_call_never_renders_a_dangling_vcf_argument": "POSIX path assertion (Windows path separators)",
    "tests/nodes/phylogeny/test_focused_phylogeny_family.py::test_iqtree_renders_official_cli_and_native_treefile": "POSIX path assertion (Windows path separators)",
    "tests/nodes/phylogeny/test_remaining_phylogeny_family.py::test_astral_runtime_command_preserves_process_failure_status": "POSIX path assertion (Windows path separators)",
    "tests/nodes/phylogeny/test_remaining_phylogeny_family.py::test_modeltest_runtime_command_and_native_outputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/phylogeny/test_remaining_phylogeny_family.py::test_raxml_plans_the_supported_tree_for_each_mode": "POSIX path assertion (Windows path separators)",
    "tests/nodes/proteomics/test_remaining_family.py::test_diann_uses_native_report_and_stats_without_synthetic_postprocessing": "POSIX path assertion (Windows path separators)",
    "tests/nodes/proteomics/test_remaining_family.py::test_fragpipe_omits_optional_resource_flags_and_rejects_unknown_data_type": "symlink creation requires privilege on Windows",
    "tests/nodes/proteomics/test_remaining_family.py::test_fragpipe_rejects_manifest_not_matching_staged_inputs": "symlink creation requires privilege on Windows",
    "tests/nodes/proteomics/test_remaining_family.py::test_fragpipe_stages_manifest_database_and_license_flags": "symlink creation requires privilege on Windows",
    "tests/nodes/proteomics/test_remaining_family.py::test_maxquant_rejects_wrong_mqpar_version": "symlink creation requires privilege on Windows",
    "tests/nodes/proteomics/test_remaining_family.py::test_maxquant_rewrites_version_matched_mqpar_and_native_outputs": "symlink creation requires privilege on Windows",
    "tests/nodes/proteomics/test_remaining_family.py::test_msfragger_prepares_complete_template_and_native_outputs": "symlink creation requires privilege on Windows",
    "tests/nodes/proteomics/test_remaining_family.py::test_openms_uses_native_feature_finder_parameters": "POSIX path assertion (Windows path separators)",
    "tests/nodes/proteomics/test_sage_percolator_family.py::test_percolator_renders_native_tabular_output_flags": "POSIX path assertion (Windows path separators)",
    "tests/nodes/r_family/test_family.py::test_pheatmap_uses_native_filename_output_and_explicit_annotation": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[False-False-False]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[False-False-True]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[False-True-False]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[False-True-True]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[True-False-False]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[True-False-True]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[True-True-False]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_fake_execution_maps_every_optional_output_combination_by_name[True-True-True]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_matches_source_mapq_bound_and_literal_header_rewrite": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_rna_seq_family.py::test_featurecounts_uses_threads_and_enforces_documented_constraints": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rna_seq/test_stringtie.py::test_stringtie_renders_documented_outputs_and_flags": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_contract_wave.py::test_optional_boolean_flags_validate_and_follow_upstream_parser_order": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_bam2wig]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_clipping_profile]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_deletion_profile]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_fpkm_count]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_gene_body_coverage2]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_gene_body_coverage]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_inner_distance]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_insertion_profile]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_junction_annotation]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_junction_saturation]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_mismatch_profile]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_read_duplication]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_read_gc]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_read_nvc]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_read_quality]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/rseqc/test_rseqc_family.py::test_rseqc_source_order_argv[rseqc_rpkm_saturation]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_first_wave.py::test_index_does_not_replace_source_reached_through_output_alias": "symlink creation requires privilege on Windows",
    "tests/nodes/samtools/test_first_wave.py::test_index_fake_execution_returns_stable_bam_and_bai_paths": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_first_wave.py::test_index_replaces_staged_leaf_symlink_with_regular_hard_link": "symlink creation requires privilege on Windows",
    "tests/nodes/samtools/test_remaining_wave.py::test_calmd_and_ampliconclip_match_reference_and_output_contracts": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_remaining_wave.py::test_depth_coverage_and_bedcov_use_explicit_index_contracts": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_remaining_wave.py::test_merge_stats_and_idxstats_commands_are_deterministic": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_remaining_wave.py::test_mpileup_places_options_before_explicit_bam_index_pairs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_remaining_wave.py::test_reheader_split_and_slice_keep_outputs_inside_declared_paths": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_remaining_wave.py::test_sam_bam_aliases_preserve_ports_but_use_explicit_fai_inputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/samtools/test_reporting_query_contracts.py::test_coverage_renders_source_supported_filters_and_keeps_sibling_index_contract": "POSIX path assertion (Windows path separators)",
    "tests/nodes/synthetic_biology/test_focused_synthetic_biology_family.py::test_cello_renders_official_dna_compiler_artifact_contract": "POSIX path assertion (Windows path separators)",
    "tests/nodes/synthetic_biology/test_focused_synthetic_biology_family.py::test_copasi_renders_cps_task_override_and_required_outputs": "POSIX path assertion (Windows path separators)",
    "tests/nodes/synthetic_biology/test_focused_synthetic_biology_family.py::test_ibiosim_uses_case_sensitive_official_wrapper_and_native_directory": "POSIX path assertion (Windows path separators)",
    "tests/nodes/synthetic_biology/test_focused_synthetic_biology_family.py::test_sbol_uses_official_format_constants_and_plans_native_files": "POSIX path assertion (Windows path separators)",
    "tests/nodes/test_indexed_bam_consumers.py::test_colocated_validator_does_not_dereference_symlinks": "symlink creation requires privilege on Windows",
    "tests/nodes/test_mummer4_family.py::test_nucmer_renders_native_output_modes_and_query_list": "POSIX path assertion (Windows path separators)",
    "tests/nodes/utility_reporting/test_family.py::test_merge_vcf_uses_documented_no_index_argv_and_native_filename": "POSIX path assertion (Windows path separators)",
    "tests/nodes/utility_reporting/test_family.py::test_table_preview_parses_quoted_delimiters_and_escapes_html": "POSIX path assertion (Windows path separators)",
    "tests/nodes/variant/test_gatk_462_family.py::test_mutect2_renders_explicit_tumor_normal_and_resource_roles": "POSIX path assertion (Windows path separators)",
    "tests/nodes/variant/test_source_pinned_callers.py::test_delly_normal_bam_index_is_an_explicit_colocated_sidecar": "POSIX path assertion (Windows path separators)",
    "tests/nodes/variant/test_source_pinned_callers.py::test_manta_normal_index_and_rna_mode_fail_closed": "POSIX path assertion (Windows path separators)",
    "tests/nodes/variant/test_source_pinned_callers.py::test_manta_runtime_refuses_generated_state_symlinks": "symlink creation requires privilege on Windows",
    "tests/nodes/wrapped_amplicon_trimming/test_family.py::test_vendored_assets_match_pinned_hashes_and_resolve_at_runtime": "vendored asset hash mismatch; Windows CRLF checkout",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[checkm2]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[checkm_analyze]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[checkm_qa]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[checkm_tree]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[cherri_eval]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[chewbbaca_createschema]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[shovill]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_assembly_typing/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[snippy]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_database_backed_ucsc_nodes_use_an_isolated_home_and_pinned_default_config[ucsc_mafcoverage-inputs3]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_database_backed_ucsc_nodes_use_an_isolated_home_and_pinned_default_config[ucsc_maffetch-inputs0]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_database_backed_ucsc_nodes_use_an_isolated_home_and_pinned_default_config[ucsc_maffrag-inputs1]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_database_backed_ucsc_nodes_use_an_isolated_home_and_pinned_default_config[ucsc_maffrags-inputs2]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_database_backed_ucsc_nodes_use_an_isolated_home_and_pinned_default_config[ucsc_mafgene-inputs4]": "POSIX path assertion (Windows path separators)",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_vendored_galaxy_assets_match_the_pinned_tools_iuc_bytes[brew3r.r_script.R-0472030823d0617b39a1ef846a16b9e7efa18c6a6142e90f3d2eaa8dd26c40d7]": "vendored asset hash mismatch; Windows CRLF checkout",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_vendored_galaxy_assets_match_the_pinned_tools_iuc_bytes[heinz_bum.R-64fc20268e208fc7a70f0d71e33111ef62c18ee5c11bfd6e63d60d7fce6536de]": "vendored asset hash mismatch; Windows CRLF checkout",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_vendored_galaxy_assets_match_the_pinned_tools_iuc_bytes[heinz_scoring.py-f9005c051eb08633fa3ad190acd4e253ba02f13211eca2195b3a954f5884b843]": "vendored asset hash mismatch; Windows CRLF checkout",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_vendored_galaxy_assets_match_the_pinned_tools_iuc_bytes[heinz_visualization.py-4a2d21327b3afb9fd43b961251e21db139cd511ca69ab60b3d01e88af2d4c679]": "vendored asset hash mismatch; Windows CRLF checkout",
    "tests/nodes/wrapped_beacon_ucsc/test_family_contracts.py::test_vendored_galaxy_assets_match_the_pinned_tools_iuc_bytes[manhattan.R-e8df00a7de5ed30b0709a172f381a8985d46621929a4c61f9f6f1ef8544ebd5e]": "vendored asset hash mismatch; Windows CRLF checkout",
    "tests/nodes/wrapped_taxonomy_humann/test_family.py::test_each_contract_validates_renders_and_plans_declared_outputs[humann_split_stratified_table]": "POSIX path assertion (Windows path separators)",
    "tests/test_bam_cram_utility_nodes.py::test_bamutil_clip_overlap_renders_transform_command_and_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_bam_cram_utility_nodes.py::test_bamutil_diff_renders_selective_sam_diff_command_and_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_bam_cram_utility_nodes.py::test_cramino_renders_optional_qc_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_cloud_storage_nodes.py::test_s3_download_executes_aws_cli_and_writes_metadata": "POSIX path assertion (Windows path separators)",
    "tests/test_cloud_template_input_staging.py::test_editor_cloud_upload_finishes_before_lambda_response": "requires live cloud credentials/environment",
    "tests/test_cnv_nodes.py::test_cnvkit_batch_plans_complete_result_directory_and_reference": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_batch_renders_complete_batch_command": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_batch_renders_documented_flat_wgs_reference_mode": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_call_omits_empty_optional_flags": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_call_plans_cns_output": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_call_renders_copy_number_command": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_plot_omits_empty_optional_flags": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_plot_plans_pdf_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvkit_plot_renders_scatter_and_heatmap_commands": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_cnvnator_plans_call_and_root_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_cnv_nodes.py::test_control_freec_plans_profile_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_command_node_outputs.py::test_command_node_prepares_space_free_output_alias_for_rendering": "POSIX path assertion (Windows path separators)",
    "tests/test_epigenomics_nodes.py::test_cooler_cload_uses_zoomify_balancing_and_exact_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_epigenomics_nodes.py::test_cooler_csort_uses_current_required_columns_and_declares_pairix_index": "POSIX path assertion (Windows path separators)",
    "tests/test_epigenomics_nodes.py::test_cooltools_compartments_uses_documented_outputs_and_zero_ignore_diags": "POSIX path assertion (Windows path separators)",
    "tests/test_epigenomics_nodes.py::test_cooltools_insulation_preserves_empty_weight_for_raw_data": "POSIX path assertion (Windows path separators)",
    "tests/test_epigenomics_nodes.py::test_juicer_uses_documented_work_and_installation_flags": "POSIX path assertion (Windows path separators)",
    "tests/test_epigenomics_nodes.py::test_methyldackel_uses_real_text_mbias_and_bedgraph_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_cnvkit_access_renders_command_outputs_and_validation": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_cnvkit_antitarget_renders_command_outputs_and_validation": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_cnvkit_target_renders_command_outputs_and_validation": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_collection_column_join_executes_coreutils_script_with_literal_tab_delimiters": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_featurecounts_renders_builtin_fragment_bam_and_junction_command": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_ucsc_mafcoverage_renders_galaxy_config_count_restrict_and_output": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_ucsc_maffetch_renders_galaxy_config_lookup_and_output": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_ucsc_maffrag_renders_region_lookup_outname_and_output": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_ucsc_maffrags_renders_default_flags_orgs_and_output": "POSIX path assertion (Windows path separators)",
    "tests/test_galaxy_parity_nodes.py::test_ucsc_mafgene_renders_default_single_and_bed_selection_commands": "POSIX path assertion (Windows path separators)",
    "tests/test_metabolomics_nodes.py::test_mzmine_and_msdial_use_explicit_staged_state": "POSIX path assertion (Windows path separators)",
    "tests/test_metabolomics_nodes.py::test_sirius_cli_places_options_under_their_documented_subcommands": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_astral_omits_branch_annotations_unless_requested_and_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_ebi_clustal_omega_plans_format_specific_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_modeltest_ng_omits_empty_optional_flags_and_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_modeltest_ng_renders_model_selection_command": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_muscle_omits_disabled_optional_flags_and_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_phylot_plans_outputs_from_output_name_and_format": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_raxml_ng_uses_search_without_bootstraps_and_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_phylogeny_nodes.py::test_trimal_supports_strict_mode_and_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_protein_structure_design_nodes.py::test_colabfold_renders_acknowledged_prediction_command": "POSIX path assertion (Windows path separators)",
    "tests/test_qc_nodes.py::test_qualimap_alias_renders_and_plans_with_alias_output_path": "POSIX path assertion (Windows path separators)",
    "tests/test_spatial_transcriptomics_nodes.py::test_baysor_renders_supported_config_and_prior_column_flags": "POSIX path assertion (Windows path separators)",
    "tests/test_standard_viz_nodes.py::test_krona_command_targets_kraken_columns": "POSIX path assertion (Windows path separators)",
    "tests/test_starsolo_count.py::test_the_matrix_is_gzipped_into_the_cell_ranger_v3_layout": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_cutesv_plans_vcf_output": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_gridss_plans_vcf_and_assembly_bam_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_melt_mobile_elements_renders_single_command": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_melt_mobile_elements_supports_exome_mode_and_plans_output_directory": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_smoove_plans_genotyped_vcf_output": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_sniffles2_call_renders_workflow_compatible_command": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_sniffles2_plans_compressed_vcf_output": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_strelka2_plans_small_variant_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_sv_stats_plans_json_and_image_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_svim_plans_vcf_output": "POSIX path assertion (Windows path separators)",
    "tests/test_structural_variant_nodes.py::test_vcf_comparison_plans_json_and_image_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_trimming_nodes.py::test_trim_galore_plans_paired_trimmed_reads_and_report": "POSIX path assertion (Windows path separators)",
    "tests/test_trimming_nodes.py::test_trim_galore_plans_single_end_trimmed_read_and_report": "POSIX path assertion (Windows path separators)",
    "tests/test_utility_file_format_nodes.py::test_path_operations_support_documented_relative_type_and_rewrite_modes": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_additional_callers.py::test_clair3_omits_empty_optional_flags_and_plans_merge_output": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_additional_callers.py::test_deepvariant_uses_default_model_and_plans_output": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_additional_callers.py::test_platypus_supports_multiple_bams_and_plans_output": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_annotate_vcf_plans_named_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_annotate_vcf_renders_bcftools_custom_annotation_command": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_annotate_vcf_renders_vcfanno_multi_source_command": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_annovar_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_annovar_renders_direct_table_annovar_vcf_command": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_bcftools_annotate_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_funcotate_table_plans_outputs_by_format": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_funcotate_table_renders_gatk_funcotator_command": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_funcotate_table_supports_vcf_output_and_omits_empty_optional_flags": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_funcotator_alias_plans_outputs_under_funcotator_directory": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_funcotator_alias_renders_gatk_funcotator_command": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_interproscan_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_variant_annotation_nodes.py::test_pbsv_plans_outputs": "POSIX path assertion (Windows path separators)",
    "tests/test_workflow_enhancement_nodes.py::test_cache_control_run_scope_is_isolated_by_run_id": "POSIX path assertion (Windows path separators)",
}
