// High-frequency Spanish translation overlay for the locale generator.
// Each entry maps a literal English value to its Spanish equivalent.
// Keys are matched case-sensitively against the *value* portion of an
// `key: 'Value'` line in en.ts; structural keys (the `key:` part) are not
// touched. Anything not listed falls back to English at runtime via
// i18next's fallbackLng.
//
// Strings without a translation here are intentional — they're either
// brand names (BioNodulo, HPC, FASTQ) or short tokens we want to leave
// in English for now.
export const overlay: Record<string, string> = {
  'Cancel': 'Cancelar', 'Close': 'Cerrar', 'Confirm': 'Confirmar', 'Dismiss': 'Descartar',
  'Done': 'Hecho', 'Save': 'Guardar', 'Saved': 'Guardado', 'Saving...': 'Guardando...',
  'Edit': 'Editar', 'Rename': 'Cambiar nombre', 'Duplicate': 'Duplicar', 'Delete': 'Eliminar',
  'Remove': 'Quitar', 'Add': 'Agregar', 'Refresh': 'Actualizar', 'Reset': 'Restablecer',
  'Apply': 'Aplicar', 'Discard': 'Descartar', 'Open': 'Abrir', 'Create': 'Crear',
  'Search': 'Buscar', 'Search...': 'Buscar...', 'Filter': 'Filtrar', 'Clear': 'Limpiar',
  'Clear all': 'Limpiar todo', 'Select': 'Seleccionar', 'Select all': 'Seleccionar todo',
  'Deselect': 'Deseleccionar', 'Deselect all': 'Deseleccionar todo',
  'Next': 'Siguiente', 'Previous': 'Anterior', 'Back': 'Atras', 'Forward': 'Adelante',
  'Upload': 'Subir', 'Download': 'Descargar', 'Import': 'Importar', 'Export': 'Exportar',
  'Copy': 'Copiar', 'Paste': 'Pegar', 'Cut': 'Cortar', 'Undo': 'Deshacer', 'Redo': 'Rehacer',
  'Yes': 'Si', 'Untitled': 'Sin titulo', 'Loading...': 'Cargando...',
  'Empty': 'Vacio', 'Warning': 'Advertencia', 'Success': 'Exito',
  'Retry': 'Reintentar', 'More': 'Mas', 'Less': 'Menos',
  'Expand': 'Expandir', 'Collapse': 'Contraer', 'Show': 'Mostrar', 'Hide': 'Ocultar',
  'Enabled': 'Activado', 'Disabled': 'Desactivado',
  'Advanced': 'Avanzado', 'Settings': 'Ajustes', 'Preferences': 'Preferencias',
  'Help': 'Ayuda', 'Learn more': 'Saber mas', 'Optional': 'Opcional',
  'Required': 'Obligatorio', 'Type here': 'Escriba aqui',
  'Name': 'Nombre', 'Description': 'Descripcion', 'Type': 'Tipo',
  'Status': 'Estado', 'Actions': 'Acciones', 'Details': 'Detalles',
  'Summary': 'Resumen', 'Overview': 'Vision general', 'Options': 'Opciones',
  'History': 'Historial', 'Today': 'Hoy', 'Yesterday': 'Ayer',
  'Notifications': 'Notificaciones', 'Notice': 'Aviso',
  'Confirm action': 'Confirmar accion',
  'Confirm destructive action': 'Confirmar accion destructiva',
  'Enter details': 'Ingrese detalles', 'Type a value': 'Escriba un valor',
  'Unsaved changes': 'Cambios sin guardar',
  'You have unsaved changes. Discard or keep editing?': 'Tienes cambios sin guardar. Descartarlos o seguir editando?',
  'Discard changes': 'Descartar cambios', 'Keep editing': 'Seguir editando',
  'Command palette': 'Paleta de comandos',
  'Search commands...': 'Buscar comandos...', 'No commands found': 'No se encontraron comandos',
  'Commands': 'Comandos', 'Recent': 'Reciente', 'Suggested': 'Sugerido', 'Run': 'Ejecutar',
  'Keyboard shortcuts': 'Atajos de teclado', 'Press keys...': 'Presione las teclas...',
  'Conflict': 'Conflicto', 'No shortcuts found': 'No se encontraron atajos',
  'Canvas': 'Lienzo', 'Panels': 'Paneles', 'Navigation': 'Navegacion',
  'Editing': 'Edicion', 'View': 'Vista',
  'New workflow': 'Nuevo workflow', 'Open workflow...': 'Abrir workflow...',
  'Save workflow': 'Guardar workflow', 'Save workflow as...': 'Guardar workflow como...',
  'Import workflow': 'Importar workflow', 'Export workflow': 'Exportar workflow',
  'New workflow tab': 'Nueva pestana de workflow',
  'Scroll tabs left': 'Desplazar pestanas a la izquierda',
  'Scroll tabs right': 'Desplazar pestanas a la derecha',
  'Close tab': 'Cerrar pestana', 'Close other tabs': 'Cerrar otras pestanas',
  'Close tabs to left': 'Cerrar pestanas a la izquierda',
  'Close tabs to right': 'Cerrar pestanas a la derecha',
  'Close all tabs': 'Cerrar todas las pestanas',
  'Run workflow': 'Ejecutar workflow', 'Cancel run': 'Cancelar ejecucion',
  'Validate workflow': 'Validar workflow',
  'Sign in': 'Iniciar sesion', 'Sign out': 'Cerrar sesion',
  'Profile': 'Perfil', 'User': 'Usuario', 'Guest': 'Invitado',
  'Node library': 'Biblioteca de nodos', 'Parameters': 'Parametros',
  'Workspace': 'Espacio de trabajo',
  'Settings sections': 'Secciones de ajustes',
  'Search settings... (e.g. theme, cache, hpc)': 'Buscar ajustes... (p. ej. tema, cache, hpc)',
  'Search settings': 'Buscar ajustes',
  'No settings match "{{query}}"': 'Ningun ajuste coincide con "{{query}}"',
  '{{count}} match': '{{count}} coincidencia',
  '{{count}} matches': '{{count}} coincidencias',
  'Appearance': 'Apariencia',
  'Execution': 'Ejecucion',
  'Files': 'Archivos',
  'AI Assistant': 'Asistente de IA',
  'Feature Flags': 'Funciones experimentales',
  'Telemetry': 'Telemetria',
  'Theme': 'Tema',
  'Select app theme': 'Seleccionar tema de la app',
  'System': 'Sistema',
  'Light': 'Claro',
  'Dark': 'Oscuro',
  'Show tooltips on hover': 'Mostrar tooltips al pasar el cursor',
  'Palette': 'Paleta',
  'Switch color palette': 'Cambiar paleta de colores',
  'Export Palette': 'Exportar paleta',
  'Import Palette': 'Importar paleta',
  'Palette exported': 'Paleta exportada',
  'Palette imported': 'Paleta importada',
  'Could not import palette': 'No se pudo importar la paleta',
  'Invalid palette file': 'Archivo de paleta no valido',
  'Snap to grid': 'Ajustar a la cuadricula',
  'Align nodes to grid': 'Alinear nodos a la cuadricula',
  'Lock Viewport': 'Bloquear vista',
  'Prevent canvas pan/zoom': 'Impedir desplazamiento/zoom del lienzo',
  'Preserve View': 'Conservar vista',
  'Remember canvas position': 'Recordar posicion del lienzo',
  'Auto-save workflow': 'Guardado automatico',
  'Automatically save workflows': 'Guardar workflows automaticamente',
  'Off': 'Desactivado',
  'Every 30s': 'Cada 30 s',
  'Every minute': 'Cada minuto',
  'Render Quality': 'Calidad de renderizado',
  'Visual fidelity vs. performance on large graphs': 'Fidelidad visual vs. rendimiento en grafos grandes',
  'Auto (recommended)': 'Auto (recomendado)',
  'High (always)': 'Alta (siempre)',
  'Low (fast)': 'Baja (rapida)',
  'Node Shadows': 'Sombras de nodos',
  'Draw drop shadows behind nodes': 'Dibujar sombras detras de los nodos',
  'Smooth Links': 'Enlaces suavizados',
  'Anti-alias bezier connections': 'Suavizar conexiones bezier',
  'Color by Status': 'Color por estado',
  'Tint node headers by last run status (completed/error/cached)': 'Tintar encabezados de nodos segun el ultimo estado de ejecucion (completed/error/cached)',
  'Link Color': 'Color de enlaces',
  'How connection lines are colored': 'Como se colorean las lineas de conexion',
  'By data type': 'Por tipo de dato',
  'Gradient (mismatch highlight)': 'Gradiente (resalta incompatibilidad)',
  'Uniform': 'Uniforme',
  'Mode': 'Modo',
  'BioNodulo starts offline. Create or join a temporary room when you want shared editing.': 'BioNodulo inicia sin conexion. Crea o unite a una sala temporal cuando quieras edicion compartida.',
  'Live': 'En vivo',
  'Connecting': 'Conectando',
  'Link ready': 'Enlace listo',
  'Offline': 'Sin conexion',
  'Create Link': 'Crear enlace',
  'Start a temporary room and copy a link for other users.': 'Iniciar una sala temporal y copiar un enlace para otros usuarios.',
  'Join Link': 'Unirse con enlace',
  'Paste a BioNodulo collaboration link or room ID.': 'Pega un enlace de colaboracion de BioNodulo o ID de sala.',
  'Join': 'Unirse',
  'Current Link': 'Enlace actual',
  'Temporary link for this running BioNodulo server.': 'Enlace temporal para este servidor BioNodulo en ejecucion.',
  'Stop Collaboration': 'Detener colaboracion',
  'Return this browser to offline mode.': 'Devolver este navegador al modo sin conexion.',
  'Stop': 'Detener',
  'Presence Cursors': 'Cursores de presencia',
  'Show collaborators on the canvas': 'Mostrar colaboradores en el lienzo',
  'Enable Cache': 'Activar cache',
  'Cache workflow node results between runs': 'Cachear resultados de nodos de workflow entre ejecuciones',
  'Delete all cached execution results': 'Eliminar todos los resultados de ejecucion cacheados',
  'Cache cleared': 'Cache limpiada',
  '{{count}} entry deleted': '{{count}} entrada eliminada',
  '{{count}} entries deleted': '{{count}} entradas eliminadas',
  'Failed to clear cache': 'No se pudo limpiar la cache',
  'Server unreachable': 'Servidor inaccesible',
  'Queue History Size': 'Tamano de historial de cola',
  'Maximum history entries': 'Entradas maximas del historial',
  'Strong Hashing': 'Hashing fuerte',
  'Use stronger cache keys': 'Usar claves de cache mas fuertes',
  'Explorer Depth': 'Profundidad del explorador',
  'File tree nesting limit': 'Limite de anidacion del arbol de archivos',
  'Show Hidden Files': 'Mostrar archivos ocultos',
  'Display dotfiles': 'Mostrar dotfiles',
  'Confirm Delete': 'Confirmar eliminacion',
  'Prompt before file deletion': 'Pedir confirmacion antes de eliminar archivos',
  'Provider': 'Proveedor',
  'LLM API provider': 'Proveedor de API LLM',
  'LiteLLM Proxy': 'Proxy LiteLLM',
  'Custom OpenAI-compatible': 'Personalizado compatible con OpenAI',
  'Model': 'Modelo',
  'Model name or LiteLLM model string': 'Nombre de modelo o cadena de modelo LiteLLM',
  'Base URL': 'URL base',
  'API base URL for proxy or custom endpoint': 'URL base de API para proxy o endpoint personalizado',
  'API Key': 'Clave API',
  'Your API key': 'Tu clave API',
  'Temperature': 'Temperatura',
  'Sampling temperature': 'Temperatura de muestreo',
  'Max Tokens': 'Tokens maximos',
  'Maximum response tokens': 'Tokens maximos de respuesta',
  'No telemetry events recorded yet': 'Aun no hay eventos de telemetria registrados',
  'Telemetry exported': 'Telemetria exportada',
  'Record diagnostic events': 'Registrar eventos de diagnostico',
  'Capture a local ring buffer of UI events for debugging. Never leaves your machine.': 'Captura un buffer circular local de eventos de UI para depuracion. Nunca sale de tu maquina.',
  '{{count}} event stored (capped at {{limit}})': '{{count}} evento almacenado (limite {{limit}})',
  '{{count}} events stored (capped at {{limit}})': '{{count}} eventos almacenados (limite {{limit}})',
  'Workspace Root': 'Raiz del espacio de trabajo',
  '/path/to/workspace': '/ruta/al/espacio',
  'Set': 'Definir',
  'Set workspace root': 'Definir raiz del espacio de trabajo',
  'Default': 'Predeterminado',
  'Reload current root': 'Recargar raiz actual',
  'Open settings': 'Abrir ajustes',
  'Failed to change workspace': 'No se pudo cambiar el espacio de trabajo',
  'Network error': 'Error de red',
  'Go up': 'Subir',
  '{{count}} selected': '{{count}} seleccionado',
  '{{count}} items selected': '{{count}} seleccionados',
  'No files in this directory': 'No hay archivos en este directorio',
  'Double-click to open': 'Doble clic para abrir',
  'Double-click to preview, drag to canvas to import': 'Doble clic para previsualizar; arrastra al lienzo para importar',
  'Double-click to preview, drag to canvas to add as input': 'Doble clic para previsualizar; arrastra al lienzo para agregar como entrada',
  'Error loading file: {{status}}': 'Error al cargar archivo: {{status}}',
  'Invalid workflow JSON': 'JSON de workflow no valido',
  'Load as Workflow': 'Cargar como workflow',
  'Runs': 'Ejecuciones', 'Queue': 'Cola', 'Templates': 'Plantillas',
  'Environment': 'Entorno',
  'Environments': 'Entornos',
  'Loading environments...': 'Cargando entornos...',
  'No environments yet.': 'No hay entornos todavia.',
  'Run a workflow to create one.': 'Ejecuta un workflow para crear uno.',
  'Show packages': 'Mostrar paquetes',
  'Collapse packages': 'Contraer paquetes',
  '{{count}} package': '{{count}} paquete',
  '{{count}} packages': '{{count}} paquetes',
  'Remove {{name}}': 'Eliminar {{name}}',
  "Renamed to '{{name}}'": "Renombrado a '{{name}}'",
  'Rename failed': 'No se pudo renombrar',
  'Delete environment?': 'Eliminar entorno?',
  "Delete environment '{{name}}'? This cannot be undone.": "Eliminar entorno '{{name}}'? Esta accion no se puede deshacer.",
  "Deleted environment '{{name}}'": "Entorno '{{name}}' eliminado",
  'Delete failed': 'No se pudo eliminar',
  "Duplicated '{{name}}'": "Duplicado '{{name}}'",
  'Duplicate failed': 'No se pudo duplicar',
  'Remove package?': 'Eliminar paquete?',
  "Remove package '{{packageName}}' from environment '{{environmentName}}'?": "Eliminar paquete '{{packageName}}' del entorno '{{environmentName}}'?",
  "Removed '{{name}}'": "Eliminado '{{name}}'",
  'Remove failed': 'No se pudo eliminar',
  'HPC Configuration': 'Configuracion HPC',
  'Enable HPC Mode': 'Activar modo HPC',
  'Submit jobs to cluster instead of local execution': 'Enviar trabajos al cluster en lugar de ejecucion local',
  'HPC is enabled': 'HPC esta activado',
  'Jobs will be submitted to the configured scheduler.': 'Los trabajos se enviaran al planificador configurado.',
  'Scheduler': 'Planificador',
  'Job Resources': 'Recursos del trabajo',
  'Partition / Queue': 'Particion / Cola',
  'Account / Project': 'Cuenta / Proyecto',
  'Walltime': 'Tiempo limite',
  'CPUs per Task': 'CPUs por tarea',
  'Memory per CPU': 'Memoria por CPU',
  'Modules (one per line)': 'Modulos (uno por linea)',
  'Container (optional)': 'Contenedor (opcional)',
  'Extra Args': 'Argumentos extra',
  'Test Connection': 'Probar conexion',
  'Testing...': 'Probando...',
  'Connected': 'Conectado',
  ' (partition: {{partition}})': ' (particion: {{partition}})',
  'Connected: {{backend}}{{partition}}': 'Conectado: {{backend}}{{partition}}',
  'Failed to connect ({{status}}). Check your HPC configuration.': 'No se pudo conectar ({{status}}). Revisa tu configuracion HPC.',
  'Backend not available. Ensure the HPC module is configured.': 'Backend no disponible. Asegurate de que el modulo HPC este configurado.',
  'Job Script Preview': 'Vista previa del script de trabajo',
  'Help & wiki': 'Ayuda y wiki', 'Console': 'Consola', 'Logs': 'Registros',
  'Previews': 'Previsualizaciones', 'Report': 'Informe',
  'Close console': 'Cerrar consola',
  'No logs yet. Run a workflow to see logs.': 'Todavia no hay registros. Ejecuta un workflow para verlos.',
  'Queue is empty.': 'La cola esta vacia.',
  'No completed runs yet.': 'Todavia no hay ejecuciones completadas.',
  'No previews yet. Run a workflow that generates plots or HTML reports.': 'Todavia no hay previsualizaciones. Ejecuta un workflow que genere graficos o informes HTML.',
  'Expand All': 'Expandir todo',
  'Collapse All': 'Contraer todo',
  'Expand all log groups': 'Expandir todos los grupos de registros',
  'Collapse all log groups': 'Contraer todos los grupos de registros',
  'Clear all logs': 'Limpiar todos los registros',
  'Clear Queue': 'Limpiar cola',
  'Clear queued runs': 'Limpiar ejecuciones en cola',
  'Hide details': 'Ocultar detalles',
  'Show details': 'Mostrar detalles',
  'Hide solver details': 'Ocultar detalles del solver',
  'Show solver details': 'Mostrar detalles del solver',
  'Hide verbose': 'Ocultar verboso',
  'Show verbose': 'Mostrar verboso',
  'Expand node': 'Expandir nodo',
  'Collapse node': 'Contraer nodo',
  '{{lines}} lines, {{nodes}} nodes': '{{lines}} lineas, {{nodes}} nodos',
  'Show {{count}} earlier lines ({{hidden}} hidden)': 'Mostrar {{count}} lineas anteriores ({{hidden}} ocultas)',
  '{{count}} solver line hidden - click "Show verbose" to reveal': '{{count}} linea del solver oculta - haz clic en "Mostrar verboso" para verla',
  '{{count}} solver lines hidden - click "Show verbose" to reveal': '{{count}} lineas del solver ocultas - haz clic en "Mostrar verboso" para verlas',
  '{{percent}}% complete': '{{percent}}% completado',
  'Untitled workflow': 'Workflow sin titulo',
  'No node plan': 'Sin plan de nodos',
  '{{completed}}/{{total}} nodes': '{{completed}}/{{total}} nodos',
  '{{count}} running': '{{count}} ejecutando',
  '{{count}} pending': '{{count}} pendiente',
  '{{count}} failed': '{{count}} fallida',
  'Move earlier': 'Mover antes',
  'Move later': 'Mover despues',
  'Retry run': 'Reintentar ejecucion',
  'Load this workflow into a new tab': 'Cargar este workflow en una pestana nueva',
  'Delete this run from history': 'Eliminar esta ejecucion del historial',
  'in progress': 'en progreso',
  'Past Week': 'Ultima semana',
  'Earlier': 'Anterior',
  'Filter by name or run ID': 'Filtrar por nombre o ID de ejecucion',
  'Filter history': 'Filtrar historial',
  'Filter history by status': 'Filtrar historial por estado',
  'Show all runs': 'Mostrar todas las ejecuciones',
  'Show {{status}} runs': 'Mostrar ejecuciones {{status}}',
  'Compare runs': 'Comparar ejecuciones',
  'Compare outputs of two completed runs': 'Comparar salidas de dos ejecuciones completadas',
  'Clear history': 'Limpiar historial',
  'Clear all completed runs from history': 'Limpiar todas las ejecuciones completadas del historial',
  'No runs match the current filter.': 'Ninguna ejecucion coincide con el filtro actual.',
  'Provenance reports become available once a run completes or fails.': 'Los informes de procedencia estaran disponibles cuando una ejecucion termine o falle.',
  'Run:': 'Ejecucion:',
  'Download JSON provenance manifest': 'Descargar manifiesto de procedencia JSON',
  'Manifest (JSON)': 'Manifiesto (JSON)',
  'Open report in a new tab': 'Abrir informe en una pestana nueva',
  'Open report': 'Abrir informe',
  'Loading provenance report...': 'Cargando informe de procedencia...',
  'Run report': 'Informe de ejecucion',
  'Double-click to view fullscreen': 'Doble clic para ver en pantalla completa',
  'Click to open HTML report': 'Clic para abrir informe HTML',
  'Preview {{node}}': 'Previsualizacion {{node}}',
  'All': 'Todas',
  'Completed': 'Completadas',
  'Errors': 'Errores',
  'Cancelled': 'Canceladas',
  'pending': 'pendiente',
  'running': 'ejecutando',
  'completed': 'completada',
  'cancelled': 'cancelada',
  'failed': 'fallida',
  'Statistics': 'Estadisticas', 'Node map': 'Mapa de nodos',
  'Minimap': 'Minimapa', 'Notes': 'Notas',
  'Close inspector': 'Cerrar inspector',
  'No node selected': 'Ningun nodo seleccionado',
  'Click any node on the canvas to edit its parameters here. Double-click also opens a floating editor.': 'Haz clic en cualquier nodo del lienzo para editar sus parametros aqui. Doble clic tambien abre un editor flotante.',
  'Search nodes...': 'Buscar nodos...', 'No nodes found': 'No se encontraron nodos',
  'Favourites': 'Favoritos', 'All categories': 'Todas las categorias',
  'Add to canvas': 'Agregar al lienzo',
  'Pin node': 'Fijar nodo', 'Unpin node': 'Desfijar nodo',
};
