// High-frequency Spanish translation overlay for the locale generator.
// Each entry maps a literal English value to its Spanish equivalent.
// Keys are matched case-sensitively against the *value* portion of an
// `key: 'Value'` line in en.ts; structural keys (the `key:` part) are not
// touched. Anything not listed falls back to English at runtime via
// i18next's fallbackLng.
//
// Strings without a translation here are intentional — they're either
// brand names (BioNodulo, HPC, FASTQ) or short tokens we want to leave
// in English for now.
export const overlay: Record<string, string> = {
  'Cancel': 'Cancelar', 'Close': 'Cerrar', 'Confirm': 'Confirmar', 'Dismiss': 'Descartar',
  'Done': 'Hecho', 'Save': 'Guardar', 'Saved': 'Guardado', 'Saving...': 'Guardando...',
  'Edit': 'Editar', 'Rename': 'Cambiar nombre', 'Duplicate': 'Duplicar', 'Delete': 'Eliminar',
  'Remove': 'Quitar', 'Add': 'Agregar', 'Refresh': 'Actualizar', 'Reset': 'Restablecer',
  'Apply': 'Aplicar', 'Discard': 'Descartar', 'Open': 'Abrir', 'Create': 'Crear',
  'Search': 'Buscar', 'Search...': 'Buscar...', 'Filter': 'Filtrar', 'Clear': 'Limpiar',
  'Clear all': 'Limpiar todo', 'Select': 'Seleccionar', 'Select all': 'Seleccionar todo',
  'Deselect': 'Deseleccionar', 'Deselect all': 'Deseleccionar todo',
  'Next': 'Siguiente', 'Previous': 'Anterior', 'Back': 'Atras', 'Forward': 'Adelante',
  'Upload': 'Subir', 'Download': 'Descargar', 'Import': 'Importar', 'Export': 'Exportar',
  'Copy': 'Copiar', 'Paste': 'Pegar', 'Cut': 'Cortar', 'Undo': 'Deshacer', 'Redo': 'Rehacer',
  'Yes': 'Si', 'Untitled': 'Sin titulo', 'Loading...': 'Cargando...',
  'Empty': 'Vacio', 'Warning': 'Advertencia', 'Success': 'Exito',
  'Retry': 'Reintentar', 'More': 'Mas', 'Less': 'Menos',
  'Expand': 'Expandir', 'Collapse': 'Contraer', 'Show': 'Mostrar', 'Hide': 'Ocultar',
  'Enabled': 'Activado', 'Disabled': 'Desactivado',
  'Advanced': 'Avanzado', 'Settings': 'Ajustes', 'Preferences': 'Preferencias',
  'Help': 'Ayuda', 'Learn more': 'Saber mas', 'Optional': 'Opcional',
  'Required': 'Obligatorio', 'Type here': 'Escriba aqui',
  'Name': 'Nombre', 'Description': 'Descripcion', 'Type': 'Tipo',
  'Status': 'Estado', 'Actions': 'Acciones', 'Details': 'Detalles',
  'Summary': 'Resumen', 'Overview': 'Vision general', 'Options': 'Opciones',
  'History': 'Historial', 'Today': 'Hoy', 'Yesterday': 'Ayer',
  'Notifications': 'Notificaciones', 'Notice': 'Aviso',
  'Confirm action': 'Confirmar accion',
  'Confirm destructive action': 'Confirmar accion destructiva',
  'Enter details': 'Ingrese detalles', 'Type a value': 'Escriba un valor',
  'Unsaved changes': 'Cambios sin guardar',
  'You have unsaved changes. Discard or keep editing?': 'Tienes cambios sin guardar. Descartarlos o seguir editando?',
  'Discard changes': 'Descartar cambios', 'Keep editing': 'Seguir editando',
  'Command palette': 'Paleta de comandos',
  'Search commands...': 'Buscar comandos...', 'No commands found': 'No se encontraron comandos',
  'Commands': 'Comandos', 'Recent': 'Reciente', 'Suggested': 'Sugerido', 'Run': 'Ejecutar',
  'Keyboard shortcuts': 'Atajos de teclado', 'Press keys...': 'Presione las teclas...',
  'Conflict': 'Conflicto', 'No shortcuts found': 'No se encontraron atajos',
  'Canvas': 'Lienzo', 'Panels': 'Paneles', 'Navigation': 'Navegacion',
  'Editing': 'Edicion', 'View': 'Vista',
  'New workflow': 'Nuevo workflow', 'Open workflow...': 'Abrir workflow...',
  'Save workflow': 'Guardar workflow', 'Save workflow as...': 'Guardar workflow como...',
  'Import workflow': 'Importar workflow', 'Export workflow': 'Exportar workflow',
  'New workflow tab': 'Nueva pestana de workflow',
  'Scroll tabs left': 'Desplazar pestanas a la izquierda',
  'Scroll tabs right': 'Desplazar pestanas a la derecha',
  'Close tab': 'Cerrar pestana', 'Close other tabs': 'Cerrar otras pestanas',
  'Close tabs to left': 'Cerrar pestanas a la izquierda',
  'Close tabs to right': 'Cerrar pestanas a la derecha',
  'Close all tabs': 'Cerrar todas las pestanas',
  'Run workflow': 'Ejecutar workflow', 'Cancel run': 'Cancelar ejecucion',
  'Validate workflow': 'Validar workflow',
  'Sign in': 'Iniciar sesion', 'Sign out': 'Cerrar sesion',
  'Profile': 'Perfil', 'User': 'Usuario', 'Guest': 'Invitado',
  'Collaboration: {{status}}': 'Colaboracion: {{status}}',
  'Collaboration: {{status}} | Shared': 'Colaboracion: {{status}} | Compartido',
  'Join': 'Unirse',
  'Local': 'Local',
  'Syncing': 'Sincronizando',
  'Reconnecting': 'Reconectando',
  'Reconnecting ({{count}})': 'Reconectando ({{count}})',
  'Collaboration link ready': 'Enlace de colaboracion listo',
  'Collaboration disabled': 'Colaboracion desactivada',
  'Offline - changes saved locally': 'Sin conexion - cambios guardados localmente',
  'Synchronizing': 'Sincronizando',
  'Connected': 'Conectado',
  'Reconnecting (attempt {{count}})': 'Reconectando (intento {{count}})',
  'Disconnected': 'Desconectado',
  'Offline mode is active. Start a temporary room or join one from a BioNodulo share link.': 'Modo sin conexion activo. Inicia una sala temporal o unete desde un enlace compartido de BioNodulo.',
  'Create collaboration link': 'Crear enlace de colaboracion',
  'Join collaboration': 'Unirse a colaboracion',
  'Active users': 'Usuarios activos',
  'Audit log': 'Registro de auditoria',
  'Stop collaboration': 'Detener colaboracion',
  'Collaboration settings': 'Ajustes de colaboracion',
  'Follow Viewport': 'Seguir vista',
  'Stop following {{name}}': 'Dejar de seguir a {{name}}',
  'No other users are active.': 'No hay otros usuarios activos.',
  'Workflow {{id}}': 'Workflow {{id}}',
  'Admin': 'Administrador',
  'Commenter': 'Comentarista',
  "Could not change {{name}}'s role.": 'No se pudo cambiar el rol de {{name}}.',
  'Could not remove {{name}}.': 'No se pudo eliminar a {{name}}.',
  'Active Users': 'Usuarios activos',
  'No live collaboration sessions': 'No hay sesiones de colaboracion activas',
  '(You)': '(Tu)',
  'Manage access': 'Gestionar acceso',
  'Make {{role}}': 'Hacer {{role}}',
  'Kick user': 'Expulsar usuario',
  'Join Collaboration': 'Unirse a colaboracion',
  'Enter your display name to collaborate on workflows in real time.': 'Ingresa tu nombre visible para colaborar en workflows en tiempo real.',
  'Display Name': 'Nombre visible',
  'Your name': 'Tu nombre',
  'Joining...': 'Uniendo...',
  'Continue as Guest': 'Continuar como invitado',
  'Your session is authenticated with a secure token.': 'Tu sesion esta autenticada con un token seguro.',
  'Failed to join': 'No se pudo unir',
  'Failed to join as guest': 'No se pudo unir como invitado',
  'Following {{name}}. Click to unfollow.': 'Siguiendo a {{name}}. Haz clic para dejar de seguir.',
  'Following {{name}}': 'Siguiendo a {{name}}',
  "Follow a user's viewport": 'Seguir la vista de un usuario',
  'Follow': 'Seguir',
  'Unfollow': 'Dejar de seguir',
  'No active users': 'No hay usuarios activos',
  'Active': 'Activo',
  'Idle': 'Inactivo',
  'Dragging': 'Arrastrando',
  'Typing': 'Escribiendo',
  'Audit Log': 'Registro de auditoria',
  'Export CSV': 'Exportar CSV',
  'Failed to load audit log': 'No se pudo cargar el registro de auditoria',
  'Export failed': 'No se pudo exportar',
  '{{count}} action': '{{count}} accion',
  '{{count}} actions': '{{count}} acciones',
  '{{count}} user': '{{count}} usuario',
  '{{count}} users': '{{count}} usuarios',
  'Top: {{action}} ({{count}})': 'Principal: {{action}} ({{count}})',
  'All users': 'Todos los usuarios',
  'All actions': 'Todas las acciones',
  'Apply Filters': 'Aplicar filtros',
  'Loading audit log...': 'Cargando registro de auditoria...',
  'No audit entries found.': 'No se encontraron entradas de auditoria.',
  'Time': 'Hora',
  'Action': 'Accion',
  'Target': 'Destino',
  'Prev': 'Anterior',
  'Create node': 'Crear nodo',
  'Delete node': 'Eliminar nodo',
  'Update node': 'Actualizar nodo',
  'Move node': 'Mover nodo',
  'Create edge': 'Crear enlace',
  'Delete edge': 'Eliminar enlace',
  'Create comment': 'Crear comentario',
  'Resolve comment': 'Resolver comentario',
  'Save version': 'Guardar version',
  'Restore version': 'Restaurar version',
  'Leave': 'Salir',
  'Node': 'Nodo',
  'Edge': 'Enlace',
  'Group': 'Grupo',
  'Comment': 'Comentario',
  'Node library': 'Biblioteca de nodos', 'Parameters': 'Parametros',
  'Workspace': 'Espacio de trabajo',
  'Settings sections': 'Secciones de ajustes',
  'Search settings... (e.g. theme, cache, hpc)': 'Buscar ajustes... (p. ej. tema, cache, hpc)',
  'Search settings': 'Buscar ajustes',
  'No settings match "{{query}}"': 'Ningun ajuste coincide con "{{query}}"',
  '{{count}} match': '{{count}} coincidencia',
  '{{count}} matches': '{{count}} coincidencias',
  'Appearance': 'Apariencia',
  'Execution': 'Ejecucion',
  'Files': 'Archivos',
  'AI Assistant': 'Asistente de IA',
  'Feature Flags': 'Funciones experimentales',
  'Telemetry': 'Telemetria',
  'Theme': 'Tema',
  'Select app theme': 'Seleccionar tema de la app',
  'System': 'Sistema',
  'Light': 'Claro',
  'Dark': 'Oscuro',
  'Show tooltips on hover': 'Mostrar tooltips al pasar el cursor',
  'Palette': 'Paleta',
  'Switch color palette': 'Cambiar paleta de colores',
  'Export Palette': 'Exportar paleta',
  'Import Palette': 'Importar paleta',
  'Palette exported': 'Paleta exportada',
  'Palette imported': 'Paleta importada',
  'Could not import palette': 'No se pudo importar la paleta',
  'Invalid palette file': 'Archivo de paleta no valido',
  'Snap to grid': 'Ajustar a la cuadricula',
  'Align nodes to grid': 'Alinear nodos a la cuadricula',
  'Lock Viewport': 'Bloquear vista',
  'Prevent canvas pan/zoom': 'Impedir desplazamiento/zoom del lienzo',
  'Preserve View': 'Conservar vista',
  'Remember canvas position': 'Recordar posicion del lienzo',
  'Auto-save workflow': 'Guardado automatico',
  'Automatically save workflows': 'Guardar workflows automaticamente',
  'Off': 'Desactivado',
  'Every 30s': 'Cada 30 s',
  'Every minute': 'Cada minuto',
  'Render Quality': 'Calidad de renderizado',
  'Visual fidelity vs. performance on large graphs': 'Fidelidad visual vs. rendimiento en grafos grandes',
  'Auto (recommended)': 'Auto (recomendado)',
  'High (always)': 'Alta (siempre)',
  'Low (fast)': 'Baja (rapida)',
  'Node Shadows': 'Sombras de nodos',
  'Draw drop shadows behind nodes': 'Dibujar sombras detras de los nodos',
  'Smooth Links': 'Enlaces suavizados',
  'Anti-alias bezier connections': 'Suavizar conexiones bezier',
  'Color by Status': 'Color por estado',
  'Tint node headers by last run status (completed/error/cached)': 'Tintar encabezados de nodos segun el ultimo estado de ejecucion (completed/error/cached)',
  'Link Color': 'Color de enlaces',
  'How connection lines are colored': 'Como se colorean las lineas de conexion',
  'By data type': 'Por tipo de dato',
  'Gradient (mismatch highlight)': 'Gradiente (resalta incompatibilidad)',
  'Uniform': 'Uniforme',
  'Zoom in': 'Acercar',
  'Zoom out': 'Alejar',
  'Reset zoom': 'Restablecer zoom',
  'Fit view': 'Ajustar vista',
  'Fit selection': 'Ajustar seleccion',
  'Center on selection': 'Centrar en seleccion',
  'Toggle minimap': 'Alternar minimapa',
  'Toggle links': 'Alternar enlaces',
  'Auto-arrange nodes': 'Autoordenar nodos',
  'Delete selection': 'Eliminar seleccion',
  'Duplicate selection': 'Duplicar seleccion',
  'Group selection': 'Agrupar seleccion',
  'Ungroup selection': 'Desagrupar seleccion',
  'Align left': 'Alinear izquierda',
  'Align right': 'Alinear derecha',
  'Align top': 'Alinear arriba',
  'Align bottom': 'Alinear abajo',
  'Align center': 'Alinear centro',
  'Distribute horizontally': 'Distribuir horizontalmente',
  'Distribute vertically': 'Distribuir verticalmente',
  'Reroute edge': 'Redirigir enlace',
  'Delete edge': 'Eliminar enlace',
  'Connect from selection': 'Conectar desde seleccion',
  'Snap enabled': 'Ajuste activado',
  'Snap disabled': 'Ajuste desactivado',
  'Mode': 'Modo',
  'BioNodulo starts offline. Create or join a temporary room when you want shared editing.': 'BioNodulo inicia sin conexion. Crea o unite a una sala temporal cuando quieras edicion compartida.',
  'Collaboration': 'Colaboracion',
  'Share workflow': 'Compartir workflow',
  'Share with user': 'Compartir con usuario',
  'Viewer': 'Lector',
  'Share link': 'Enlace compartido',
  'Collaboration is offline. Create a temporary room before sharing this workflow.': 'La colaboracion esta sin conexion. Crea una sala temporal antes de compartir este workflow.',
  'User ID or email': 'Usuario o email',
  'Invite': 'Invitar',
  'Collaboration room link': 'Enlace de sala de colaboracion',
  'Create link': 'Crear enlace',
  'Creating...': 'Creando...',
  'Create a temporary collaboration room to generate a share link.': 'Crea una sala temporal de colaboracion para generar un enlace compartible.',
  'This local link works only on this machine or LAN. Use a Cloudflare/ngrok tunnel or hosted URL for external collaborators.': 'Este enlace local solo funciona en esta maquina o LAN. Usa un tunel Cloudflare/ngrok o una URL alojada para colaboradores externos.',
  'Links work while this BioNodulo server is running. Stop the app to invalidate temporary links.': 'Los enlaces funcionan mientras este servidor BioNodulo este ejecutandose. Deten la app para invalidar enlaces temporales.',
  'Shared with': 'Compartido con',
  'No shares yet': 'Sin compartidos todavia',
  'Collaboration link copied': 'Enlace de colaboracion copiado',
  'Copy the collaboration link from the field': 'Copia el enlace de colaboracion desde el campo',
  'Revoke': 'Revocar',
  'Share it with collaborators while this app is running.': 'Compartelo con colaboradores mientras esta app se ejecuta.',
  'This is a local link. Start a tunnel or use a public host before sharing outside this machine.': 'Este es un enlace local. Inicia un tunel o usa un host publico antes de compartir fuera de esta maquina.',
  'Open Share workflow to copy it.': 'Abre Compartir workflow para copiarlo.',
  'Open Share workflow to copy the local link, or start BioNodulo through a public tunnel.': 'Abre Compartir workflow para copiar el enlace local, o inicia BioNodulo mediante un tunel publico.',
  'Could not create collaboration link': 'No se pudo crear el enlace de colaboracion',
  'Join Collaboration': 'Unirse a colaboracion',
  'Paste a BioNodulo collaboration link or room ID.': 'Pega un enlace de colaboracion de BioNodulo o ID de sala.',
  'Share link': 'Enlace compartido',
  'https://bionodulo.example/?workflow=...&invite=...': 'https://bionodulo.example/?workflow=...&invite=...',
  'Join': 'Unirse',
  'Invalid collaboration link': 'Enlace de colaboracion invalido',
  'Expected a BioNodulo URL with ?workflow=... or a room ID.': 'Se esperaba una URL de BioNodulo con ?workflow=... o un ID de sala.',
  'Joined collaboration': 'Colaboracion unida',
  'Connected as {{role}}.': 'Conectado como {{role}}.',
  'Could not join collaboration': 'No se pudo unir a la colaboracion',
  'Collaboration stopped': 'Colaboracion detenida',
  'This browser is back in offline mode.': 'Este navegador vuelve al modo sin conexion.',
  '{{name}} is editing': '{{name}} esta editando',
  '{{name}} is idle': '{{name}} esta inactivo',
  'Join collaboration before using workflow comments.': 'Unete a la colaboracion antes de usar comentarios de workflow.',
  'Join collaboration before posting comments.': 'Unete a la colaboracion antes de publicar comentarios.',
  'Failed to load comments': 'No se pudieron cargar los comentarios',
  'Failed to post comment': 'No se pudo publicar el comentario',
  'Failed to post reply': 'No se pudo publicar la respuesta',
  'Failed to resolve comment': 'No se pudo resolver el comentario',
  'Failed to delete comment': 'No se pudo eliminar el comentario',
  'Delete comment?': 'Eliminar comentario?',
  'Delete this comment?': 'Eliminar este comentario?',
  'Node Only': 'Solo nodo',
  'Show All': 'Mostrar todo',
  'Loading comments...': 'Cargando comentarios...',
  'No comments for this node.\nClick "{{showAll}}" to see all comments.': 'No hay comentarios para este nodo.\nHaz clic en "{{showAll}}" para ver todos los comentarios.',
  'No comments yet across your workflows.\nStart the conversation!': 'Aun no hay comentarios en tus workflows.\nInicia la conversacion!',
  'Focus this node on the canvas': 'Centrar este nodo en el lienzo',
  'Go to node': 'Ir al nodo',
  'Write a reply...': 'Escribe una respuesta...',
  'Comment on this node... Use @name to mention': 'Comenta en este nodo... Usa @nombre para mencionar',
  'New comment... Use @name to mention': 'Nuevo comentario... Usa @nombre para mencionar',
  'Comment on node': 'Comentar nodo',
  'Node comments': 'Comentarios del nodo',
  'Close comments': 'Cerrar comentarios',
  'Reply': 'Responder',
  'Reply...': 'Responder...',
  'Send reply': 'Enviar respuesta',
  'Post comment': 'Publicar comentario',
  '{{name}}, add a node comment...': '{{name}}, agrega un comentario al nodo...',
  'Could not post comment': 'No se pudo publicar el comentario',
  'Could not resolve comment': 'No se pudo resolver el comentario',
  'just now': 'ahora',
  '{{count}}m ago': 'hace {{count}} min',
  '{{count}}h ago': 'hace {{count}} h',
  '{{count}}d ago': 'hace {{count}} d',
  'Template Gallery': 'Galeria de plantillas',
  '+ Save': '+ Guardar',
  'Close template gallery': 'Cerrar galeria de plantillas',
  'Search templates...': 'Buscar plantillas...',
  'All': 'Todas',
  'Loading templates...': 'Cargando plantillas...',
  'No templates found.': 'No se encontraron plantillas.',
  'by {{userId}}': 'por {{userId}}',
  'Fork': 'Bifurcar',
  'Forking...': 'Bifurcando...',
  'Failed to load templates': 'No se pudieron cargar las plantillas',
  'Fork failed': 'No se pudo bifurcar',
  'No active workflow to save as a template': 'No hay workflow activo para guardar como plantilla',
  'Save template': 'Guardar plantilla',
  'Name this shared workflow template.': 'Nombra esta plantilla compartida de workflow.',
  'Template title': 'Titulo de plantilla',
  'Template description': 'Descripcion de plantilla',
  'Add a short description for this template.': 'Agrega una descripcion breve para esta plantilla.',
  'Description': 'Descripcion',
  'Template tags': 'Etiquetas de plantilla',
  'Add comma-separated tags.': 'Agrega etiquetas separadas por comas.',
  'Tags': 'Etiquetas',
  'rna, alignment, qc': 'rna, alineamiento, qc',
  'Save Template': 'Guardar plantilla',
  'Failed to save template': 'No se pudo guardar la plantilla',
  'Version History': 'Historial de versiones',
  'Loading versions...': 'Cargando versiones...',
  'No saved versions yet.': 'No hay versiones guardadas todavia.',
  'Auto-saved': 'Guardado automatico',
  'Manual save': 'Guardado manual',
  'Auto-save #{{count}}': 'Guardado automatico #{{count}}',
  'Version {{count}}': 'Version {{count}}',
  '{{nodes}} nodes, {{edges}} edges': '{{nodes}} nodos, {{edges}} enlaces',
  'Restore': 'Restaurar',
  'Failed to load versions': 'No se pudieron cargar las versiones',
  'Save version': 'Guardar version',
  'Name this workflow version.': 'Nombra esta version del workflow.',
  'Version name': 'Nombre de version',
  'Optional': 'Opcional',
  'Save Version': 'Guardar version',
  'Failed to save version': 'No se pudo guardar la version',
  'Restore version?': 'Restaurar version?',
  'Restore this version? This will create a new branch of the current workflow.': 'Restaurar esta version? Esto creara una nueva rama del workflow actual.',
  'Failed to restore version': 'No se pudo restaurar la version',
  'Delete version?': 'Eliminar version?',
  'Delete this version?': 'Eliminar esta version?',
  'Failed to delete version': 'No se pudo eliminar la version',
  'Failed to load diff': 'No se pudo cargar el diff',
  'Auto-save': 'Guardado automatico',
  'Version Diff': 'Diff de versiones',
  '({{count}} changed)': '({{count}} cambiados)',
  'No differences between these versions.': 'Sin diferencias entre estas versiones.',
  '+ Added node': '+ Nodo agregado',
  '- Removed node': '- Nodo eliminado',
  '~ Modified node': '~ Nodo modificado',
  '+ Added edge': '+ Enlace agregado',
  '- Removed edge': '- Enlace eliminado',
  '~ Modified edge': '~ Enlace modificado',
  '+ Added group': '+ Grupo agregado',
  '- Removed group': '- Grupo eliminado',
  '~ Modified group': '~ Grupo modificado',
  '~ Meta: {{key}} (before)': '~ Meta: {{key}} (antes)',
  '~ Meta: {{key}} (after)': '~ Meta: {{key}} (despues)',
  '{{count}} added': '{{count}} agregados',
  '{{count}} removed': '{{count}} eliminados',
  '{{count}} modified': '{{count}} modificados',
  'Waiting for collaborators...': 'Esperando colaboradores...',
  'Live': 'En vivo',
  'Connecting': 'Conectando',
  'Link ready': 'Enlace listo',
  'Offline': 'Sin conexion',
  'Create Link': 'Crear enlace',
  'Start a temporary room and copy a link for other users.': 'Iniciar una sala temporal y copiar un enlace para otros usuarios.',
  'Join Link': 'Unirse con enlace',
  'Paste a BioNodulo collaboration link or room ID.': 'Pega un enlace de colaboracion de BioNodulo o ID de sala.',
  'Join': 'Unirse',
  'Current Link': 'Enlace actual',
  'Temporary link for this running BioNodulo server.': 'Enlace temporal para este servidor BioNodulo en ejecucion.',
  'Stop Collaboration': 'Detener colaboracion',
  'Return this browser to offline mode.': 'Devolver este navegador al modo sin conexion.',
  'Stop': 'Detener',
  'Presence Cursors': 'Cursores de presencia',
  'Show collaborators on the canvas': 'Mostrar colaboradores en el lienzo',
  'Enable Cache': 'Activar cache',
  'Cache workflow node results between runs': 'Cachear resultados de nodos de workflow entre ejecuciones',
  'Delete all cached execution results': 'Eliminar todos los resultados de ejecucion cacheados',
  'Cache cleared': 'Cache limpiada',
  '{{count}} entry deleted': '{{count}} entrada eliminada',
  '{{count}} entries deleted': '{{count}} entradas eliminadas',
  'Failed to clear cache': 'No se pudo limpiar la cache',
  'Server unreachable': 'Servidor inaccesible',
  'Queue History Size': 'Tamano de historial de cola',
  'Maximum history entries': 'Entradas maximas del historial',
  'Strong Hashing': 'Hashing fuerte',
  'Use stronger cache keys': 'Usar claves de cache mas fuertes',
  'Explorer Depth': 'Profundidad del explorador',
  'File tree nesting limit': 'Limite de anidacion del arbol de archivos',
  'Show Hidden Files': 'Mostrar archivos ocultos',
  'Display dotfiles': 'Mostrar dotfiles',
  'Confirm Delete': 'Confirmar eliminacion',
  'Prompt before file deletion': 'Pedir confirmacion antes de eliminar archivos',
  'Provider': 'Proveedor',
  'LLM API provider': 'Proveedor de API LLM',
  'LiteLLM Proxy': 'Proxy LiteLLM',
  'Custom OpenAI-compatible': 'Personalizado compatible con OpenAI',
  'Model': 'Modelo',
  'Model name or LiteLLM model string': 'Nombre de modelo o cadena de modelo LiteLLM',
  'Base URL': 'URL base',
  'API base URL for proxy or custom endpoint': 'URL base de API para proxy o endpoint personalizado',
  'API Key': 'Clave API',
  'Your API key': 'Tu clave API',
  'Temperature': 'Temperatura',
  'Sampling temperature': 'Temperatura de muestreo',
  'Max Tokens': 'Tokens maximos',
  'Maximum response tokens': 'Tokens maximos de respuesta',
  'No telemetry events recorded yet': 'Aun no hay eventos de telemetria registrados',
  'Telemetry exported': 'Telemetria exportada',
  'Record diagnostic events': 'Registrar eventos de diagnostico',
  'Capture a local ring buffer of UI events for debugging. Never leaves your machine.': 'Captura un buffer circular local de eventos de UI para depuracion. Nunca sale de tu maquina.',
  '{{count}} event stored (capped at {{limit}})': '{{count}} evento almacenado (limite {{limit}})',
  '{{count}} events stored (capped at {{limit}})': '{{count}} eventos almacenados (limite {{limit}})',
  'Workspace Root': 'Raiz del espacio de trabajo',
  '/path/to/workspace': '/ruta/al/espacio',
  'Set': 'Definir',
  'Set workspace root': 'Definir raiz del espacio de trabajo',
  'Default': 'Predeterminado',
  'Reload current root': 'Recargar raiz actual',
  'Open settings': 'Abrir ajustes',
  'Failed to change workspace': 'No se pudo cambiar el espacio de trabajo',
  'Network error': 'Error de red',
  'Go up': 'Subir',
  '{{count}} selected': '{{count}} seleccionado',
  '{{count}} items selected': '{{count}} seleccionados',
  'No files in this directory': 'No hay archivos en este directorio',
  'Double-click to open': 'Doble clic para abrir',
  'Double-click to preview, drag to canvas to import': 'Doble clic para previsualizar; arrastra al lienzo para importar',
  'Double-click to preview, drag to canvas to add as input': 'Doble clic para previsualizar; arrastra al lienzo para agregar como entrada',
  'Error loading file: {{status}}': 'Error al cargar archivo: {{status}}',
  'Invalid workflow JSON': 'JSON de workflow no valido',
  'Load as Workflow': 'Cargar como workflow',
  'Runs': 'Ejecuciones', 'Queue': 'Cola', 'Templates': 'Plantillas',
  'Environment': 'Entorno',
  'Environments': 'Entornos',
  'Loading environments...': 'Cargando entornos...',
  'No environments yet.': 'No hay entornos todavia.',
  'Run a workflow to create one.': 'Ejecuta un workflow para crear uno.',
  'Show packages': 'Mostrar paquetes',
  'Collapse packages': 'Contraer paquetes',
  '{{count}} package': '{{count}} paquete',
  '{{count}} packages': '{{count}} paquetes',
  'Remove {{name}}': 'Eliminar {{name}}',
  "Renamed to '{{name}}'": "Renombrado a '{{name}}'",
  'Rename failed': 'No se pudo renombrar',
  'Delete environment?': 'Eliminar entorno?',
  "Delete environment '{{name}}'? This cannot be undone.": "Eliminar entorno '{{name}}'? Esta accion no se puede deshacer.",
  "Deleted environment '{{name}}'": "Entorno '{{name}}' eliminado",
  'Delete failed': 'No se pudo eliminar',
  "Duplicated '{{name}}'": "Duplicado '{{name}}'",
  'Duplicate failed': 'No se pudo duplicar',
  'Remove package?': 'Eliminar paquete?',
  "Remove package '{{packageName}}' from environment '{{environmentName}}'?": "Eliminar paquete '{{packageName}}' del entorno '{{environmentName}}'?",
  "Removed '{{name}}'": "Eliminado '{{name}}'",
  'Remove failed': 'No se pudo eliminar',
  'HPC Configuration': 'Configuracion HPC',
  'Enable HPC Mode': 'Activar modo HPC',
  'Submit jobs to cluster instead of local execution': 'Enviar trabajos al cluster en lugar de ejecucion local',
  'HPC is enabled': 'HPC esta activado',
  'Jobs will be submitted to the configured scheduler.': 'Los trabajos se enviaran al planificador configurado.',
  'Scheduler': 'Planificador',
  'Job Resources': 'Recursos del trabajo',
  'Partition / Queue': 'Particion / Cola',
  'Account / Project': 'Cuenta / Proyecto',
  'Walltime': 'Tiempo limite',
  'CPUs per Task': 'CPUs por tarea',
  'Memory per CPU': 'Memoria por CPU',
  'Modules (one per line)': 'Modulos (uno por linea)',
  'Container (optional)': 'Contenedor (opcional)',
  'Extra Args': 'Argumentos extra',
  'Test Connection': 'Probar conexion',
  'Testing...': 'Probando...',
  'Connected': 'Conectado',
  ' (partition: {{partition}})': ' (particion: {{partition}})',
  'Connected: {{backend}}{{partition}}': 'Conectado: {{backend}}{{partition}}',
  'Failed to connect ({{status}}). Check your HPC configuration.': 'No se pudo conectar ({{status}}). Revisa tu configuracion HPC.',
  'Backend not available. Ensure the HPC module is configured.': 'Backend no disponible. Asegurate de que el modulo HPC este configurado.',
  'Job Script Preview': 'Vista previa del script de trabajo',
  'Help & wiki': 'Ayuda y wiki',
  'Search help...': 'Buscar ayuda...',
  'No matching articles': 'Sin articulos coincidentes',
  'Getting Started': 'Primeros pasos',
  'Canvas & Nodes': 'Lienzo y nodos',
  'Node Reference': 'Referencia de nodos',
  'Templates Guide': 'Guia de plantillas',
  'Custom Nodes': 'Nodos personalizados',
  'HPC Integration': 'Integracion HPC',
  'Workflow Converters': 'Conversores de workflow',
  'Keyboard Shortcuts': 'Atajos de teclado',
  'No results for "{{query}}"': 'Sin resultados para "{{query}}"',
  'Wiki pages': 'Paginas wiki',
  'Nodes': 'Nodos',
  'Show docs for {{name}}': 'Mostrar documentacion de {{name}}',
  'from search': 'desde busqueda',
  'selected on canvas': 'seleccionado en el lienzo',
  'No description provided by the node author.': 'El autor del nodo no proporciono descripcion.',
  'Uncategorised': 'Sin categoria',
  'Other': 'Otro',
  'default: {{value}}': 'predeterminado: {{value}}',
  'experimental': 'experimental',
  'Bulk parameter edit': 'Edicion masiva de parametros',
  'Editing {{count}} node': 'Editando {{count}} nodo',
  'Editing {{count}} nodes': 'Editando {{count}} nodos',
  'Editing parameters shared by': 'Editando parametros compartidos por',
  'selected node': 'nodo seleccionado',
  'selected nodes': 'nodos seleccionados',
  'No parameters are common to every selected node.': 'Ningun parametro es comun a todos los nodos seleccionados.',
  "The selected nodes don't share any parameter keys. Pick nodes of the same type (or a compatible subset) to bulk-edit.": 'Los nodos seleccionados no comparten claves de parametros. Elige nodos del mismo tipo o un subconjunto compatible para editarlos en bloque.',
  'Multiple values': 'Varios valores',
  'Apply to all selected': 'Aplicar a todos los seleccionados',
  'Apply to {{count}} node': 'Aplicar a {{count}} nodo',
  'Apply to {{count}} nodes': 'Aplicar a {{count}} nodos',
  'Revert field': 'Revertir campo',
  "Don't change this parameter": 'No cambiar este parametro',
  '[varies]': '[varios]',
  'Workflow doctor': 'Doctor de workflow',
  'Workflow looks healthy': 'El workflow se ve correcto',
  'No issues found. Everything looks wired up.': 'No se encontraron incidencias. Todo esta conectado.',
  '{{count}} errors': '{{count}} errores',
  '{{count}} warning': '{{count}} advertencia',
  '{{count}} warnings': '{{count}} advertencias',
  'Jump': 'Ir',
  'Centre the canvas on this node': 'Centrar el lienzo en este nodo',
  '{{node}}: required input "{{input}}" is unset': '{{node}}: la entrada obligatoria "{{input}}" no esta definida',
  'Connect an upstream output or set a default in the node editor.': 'Conecta una salida anterior o define un valor predeterminado en el editor del nodo.',
  '{{node}} has unused outputs': '{{node}} tiene salidas sin usar',
  'Connect to a downstream node, or remove if intentional.': 'Conecta a un nodo posterior o elimina si es intencional.',
  '{{node}} requires: {{tools}}': '{{node}} requiere: {{tools}}',
  'Workflow is empty': 'El workflow esta vacio',
  'Drop a template, drag a file from the workspace, or open the node library to start.': 'Suelta una plantilla, arrastra un archivo desde el espacio de trabajo o abre la biblioteca de nodos para empezar.',
  'No connections between nodes': 'No hay conexiones entre nodos',
  'Wire outputs to inputs by dragging between slots.': 'Conecta salidas con entradas arrastrando entre puertos.',
  'Batch run from sample sheet': 'Lote desde hoja de muestras',
  'One run per row. Map columns to node parameters; the rest are ignored. CSV or TSV both work.': 'Una ejecucion por fila. Asigna columnas a parametros de nodos; el resto se omite. CSV y TSV funcionan.',
  'Sample': 'Muestra',
  'Upload sample sheet': 'Subir hoja de muestras',
  'Run name prefix': 'Prefijo del nombre de ejecucion',
  'sample,fastq_in,threads\nctrl_01,/data/c1.fastq.gz,8\nctrl_02,/data/c2.fastq.gz,8': 'muestra,fastq_in,threads\nctrl_01,/data/c1.fastq.gz,8\nctrl_02,/data/c2.fastq.gz,8',
  '{{count}} row': '{{count}} fila',
  '{{count}} rows': '{{count}} filas',
  '{{count}} column': '{{count}} columna',
  '{{count}} columns': '{{count}} columnas',
  'Column mapping': 'Mapeo de columnas',
  '(column {{index}})': '(columna {{index}})',
  'Skip': 'Omitir',
  'Use as run name': 'Usar como nombre de ejecucion',
  'Preview ({{shown}} of {{total}})': 'Vista previa ({{shown}} de {{total}})',
  'Submitting...': 'Enviando...',
  'Queue {{count}} run': 'Encolar {{count}} ejecucion',
  'Queue {{count}} runs': 'Encolar {{count}} ejecuciones',
  'Paste or upload a CSV/TSV sample sheet first.': 'Pega o sube primero una hoja de muestras CSV/TSV.',
  'Sample sheet has no data rows.': 'La hoja de muestras no tiene filas de datos.',
  'Map at least one column to a node parameter.': 'Asigna al menos una columna a un parametro de nodo.',
  'Import workflow': 'Importar workflow',
  'Paste workflow code above, or upload a file (PNGs with embedded workflow metadata are decoded automatically):': 'Pega codigo de workflow arriba o sube un archivo (los PNG con metadatos de workflow incrustados se decodifican automaticamente):',
  'Parsing...': 'Analizando...',
  'Could not parse the workflow. Ensure the format is correct.': 'No se pudo analizar el workflow. Asegurate de que el formato sea correcto.',
  'Could not parse the workflow.': 'No se pudo analizar el workflow.',
  'No workflow found': 'No se encontro ningun workflow',
  'This PNG does not contain a BioNodulo workflow tEXt chunk. Export with the "PNG (workflow embedded)" option to produce one.': 'Este PNG no contiene un fragmento tEXt de workflow de BioNodulo. Exporta con la opcion "PNG (workflow incrustado)" para generar uno.',
  'PNG read failed': 'No se pudo leer el PNG',
  'PNG (workflow embedded)': 'PNG (workflow incrustado)',
  'BioNodulo JSON': 'JSON de BioNodulo',
  'The PNG carries the full workflow JSON in a tEXt chunk; drag it back into the canvas to restore the graph.': 'El PNG lleva el JSON completo del workflow en un fragmento tEXt; arrastralo de vuelta al lienzo para restaurar el grafo.',
  'Transparent background': 'Fondo transparente',
  'Resolution': 'Resolucion',
  'JSON only (skip PNG wrapper)': 'Solo JSON (omitir contenedor PNG)',
  'Generating...': 'Generando...',
  'Render thumbnail': 'Renderizar miniatura',
  'Generate': 'Generar',
  'Workflow thumbnail preview': 'Vista previa de miniatura del workflow',
  'Download PNG': 'Descargar PNG',
  'Copy to Clipboard': 'Copiar al portapapeles',
  'Regenerate': 'Regenerar',
  '{{format}} export': 'Exportacion {{format}}',
  'Backend converter not available ({{status}})': 'El conversor del backend no esta disponible ({{status}})',
  'Download HTML': 'Descargar HTML',
  'Open in new tab': 'Abrir en una pestana nueva',
  'Close (Esc)': 'Cerrar (Esc)',
  'Previous (←)': 'Anterior (←)',
  'Next (→)': 'Siguiente (→)',
  'Save image': 'Guardar imagen',
  'Missing dependencies:': 'Dependencias faltantes:',
  '{{count}} missing': '{{count}} faltantes',
  'env': 'entorno',
  '(ready)': '(listo)',
  '(not ready)': '(no listo)',
  'Installing...': 'Instalando...',
  'Install Env': 'Instalar entorno',
  'Env ready': 'Entorno listo',
  'Details': 'Detalles',
  'Required Packages ({{count}})': 'Paquetes requeridos ({{count}})',
  'Missing Nodes ({{count}})': 'Nodos faltantes ({{count}})',
  'Missing Python Packages ({{count}})': 'Paquetes Python faltantes ({{count}})',
  'Missing R Packages ({{count}})': 'Paquetes R faltantes ({{count}})',
  'Errors': 'Errores',
  'Host prerequisite missing:': 'Falta un prerrequisito del host:',
  '{{count}} required tool missing': '{{count}} herramienta requerida faltante',
  '{{count}} required tools missing': '{{count}} herramientas requeridas faltantes',
  'Auto Install Pixi': 'Instalar Pixi automaticamente',
  'Already installed': 'Ya instalado',
  'Installed successfully - reload the page to activate.': 'Instalado correctamente - recarga la pagina para activar.',
  'Install failed: {{message}}': 'Instalacion fallida: {{message}}',
  'unknown error': 'error desconocido',
  'Install request failed - check server logs.': 'La solicitud de instalacion fallo - revisa los registros del servidor.',
  'Host Checks': 'Comprobaciones del host',
  'Install manually and ensure it is on PATH': 'Instala manualmente y asegurate de que este en PATH',
  'Can be auto-installed': 'Se puede instalar automaticamente',
  '← Back': '← Volver',
  'Edit Properties': 'Editar propiedades',
  'Node Info': 'Informacion del nodo',
  'Add Comment': 'Agregar comentario',
  'Mute Node': 'Silenciar nodo',
  'Bypass Node': 'Omitir nodo',
  'Pin / Lock Node': 'Fijar / bloquear nodo',
  'Collapse/Expand': 'Contraer/expandir',
  'Set as Output': 'Definir como salida',
  'Set Color': 'Definir color',
  'Round Shape': 'Forma redonda',
  'Box Shape': 'Forma de caja',
  'Card Shape': 'Forma de tarjeta',
  'Group Selected': 'Agrupar seleccionados',
  'Create Subgraph': 'Crear subgrafo',
  'Save Subgraph to Library': 'Guardar subgrafo en biblioteca',
  'Promote Widgets to Parent': 'Promover widgets al padre',
  'Save Params as Preset...': 'Guardar parametros como preset...',
  'Apply Preset...': 'Aplicar preset...',
  'Execute Selected': 'Ejecutar seleccionados',
  'Add Node': 'Agregar nodo',
  'Add node with {{type}} input': 'Agregar nodo con entrada {{type}}',
  'Add node with {{type}} output': 'Agregar nodo con salida {{type}}',
  'Close node palette': 'Cerrar paleta de nodos',
  'Add Group': 'Agregar grupo',
  'Requires:': 'Requiere:',
  'Inputs': 'Entradas',
  'Outputs': 'Salidas',
  'Name': 'Nombre',
  'Type': 'Tipo',
  'Notes': 'Notas',
  'Tip: select another node on the canvas to view its docs here.': 'Consejo: selecciona otro nodo en el lienzo para ver su documentacion aqui.',
  'Getting started': 'Primeros pasos',
  'Tutorials': 'Tutoriales',
  'Node reference': 'Referencia de nodos',
  'Keyboard reference': 'Referencia de teclado',
  'Troubleshooting': 'Solucion de problemas',
  'Release notes': 'Notas de version',
  'Frequently asked questions': 'Preguntas frecuentes',
  'Send feedback': 'Enviar comentarios',
  'Report an issue': 'Informar un problema',
  'Open in browser': 'Abrir en navegador',
  'Console': 'Consola', 'Logs': 'Registros',
  'Previews': 'Previsualizaciones', 'Report': 'Informe',
  'Close console': 'Cerrar consola',
  'No logs yet. Run a workflow to see logs.': 'Todavia no hay registros. Ejecuta un workflow para verlos.',
  'Queue is empty.': 'La cola esta vacia.',
  'No completed runs yet.': 'Todavia no hay ejecuciones completadas.',
  'No previews yet. Run a workflow that generates plots or HTML reports.': 'Todavia no hay previsualizaciones. Ejecuta un workflow que genere graficos o informes HTML.',
  'Expand All': 'Expandir todo',
  'Collapse All': 'Contraer todo',
  'Expand all log groups': 'Expandir todos los grupos de registros',
  'Collapse all log groups': 'Contraer todos los grupos de registros',
  'Clear all logs': 'Limpiar todos los registros',
  'Clear Queue': 'Limpiar cola',
  'Clear queued runs': 'Limpiar ejecuciones en cola',
  'Hide details': 'Ocultar detalles',
  'Show details': 'Mostrar detalles',
  'Hide solver details': 'Ocultar detalles del solver',
  'Show solver details': 'Mostrar detalles del solver',
  'Hide verbose': 'Ocultar verboso',
  'Show verbose': 'Mostrar verboso',
  'Expand node': 'Expandir nodo',
  'Collapse node': 'Contraer nodo',
  '{{lines}} lines, {{nodes}} nodes': '{{lines}} lineas, {{nodes}} nodos',
  'Show {{count}} earlier lines ({{hidden}} hidden)': 'Mostrar {{count}} lineas anteriores ({{hidden}} ocultas)',
  '{{count}} solver line hidden - click "Show verbose" to reveal': '{{count}} linea del solver oculta - haz clic en "Mostrar verboso" para verla',
  '{{count}} solver lines hidden - click "Show verbose" to reveal': '{{count}} lineas del solver ocultas - haz clic en "Mostrar verboso" para verlas',
  '{{percent}}% complete': '{{percent}}% completado',
  'Untitled workflow': 'Workflow sin titulo',
  'No node plan': 'Sin plan de nodos',
  '{{completed}}/{{total}} nodes': '{{completed}}/{{total}} nodos',
  '{{count}} running': '{{count}} ejecutando',
  '{{count}} pending': '{{count}} pendiente',
  '{{count}} failed': '{{count}} fallida',
  'Move earlier': 'Mover antes',
  'Move later': 'Mover despues',
  'Retry run': 'Reintentar ejecucion',
  'Load this workflow into a new tab': 'Cargar este workflow en una pestana nueva',
  'Delete this run from history': 'Eliminar esta ejecucion del historial',
  'in progress': 'en progreso',
  'Past Week': 'Ultima semana',
  'Earlier': 'Anterior',
  'Filter by name or run ID': 'Filtrar por nombre o ID de ejecucion',
  'Filter history': 'Filtrar historial',
  'Filter history by status': 'Filtrar historial por estado',
  'Show all runs': 'Mostrar todas las ejecuciones',
  'Show {{status}} runs': 'Mostrar ejecuciones {{status}}',
  'Compare runs': 'Comparar ejecuciones',
  'Compare outputs of two completed runs': 'Comparar salidas de dos ejecuciones completadas',
  'Clear history': 'Limpiar historial',
  'Clear all completed runs from history': 'Limpiar todas las ejecuciones completadas del historial',
  'No runs match the current filter.': 'Ninguna ejecucion coincide con el filtro actual.',
  'Provenance reports become available once a run completes or fails.': 'Los informes de procedencia estaran disponibles cuando una ejecucion termine o falle.',
  'Run:': 'Ejecucion:',
  'Download JSON provenance manifest': 'Descargar manifiesto de procedencia JSON',
  'Manifest (JSON)': 'Manifiesto (JSON)',
  'Open report in a new tab': 'Abrir informe en una pestana nueva',
  'Open report': 'Abrir informe',
  'Loading provenance report...': 'Cargando informe de procedencia...',
  'Run report': 'Informe de ejecucion',
  'Double-click to view fullscreen': 'Doble clic para ver en pantalla completa',
  'Click to open HTML report': 'Clic para abrir informe HTML',
  'Preview {{node}}': 'Previsualizacion {{node}}',
  'Cancel run?': 'Cancelar ejecucion?',
  'Cancel {{name}}?': 'Cancelar {{name}}?',
  'Clear queue?': 'Limpiar cola?',
  'Remove all pending runs from the queue?': 'Quitar todas las ejecuciones pendientes de la cola?',
  'Clear history?': 'Limpiar historial?',
  'Remove all completed runs from history? This cannot be undone.': 'Quitar todas las ejecuciones completadas del historial? Esta accion no se puede deshacer.',
  'Run {{runId}}': 'Ejecucion {{runId}}',
  '{{name}} (retry)': '{{name}} (reintento)',
  'Run cancelled': 'Ejecucion cancelada',
  'Workflow loaded from run': 'Workflow cargado desde la ejecucion',
  'Retry queued': 'Reintento en cola',
  'Queue cleared': 'Cola limpiada',
  'History cleared': 'Historial limpiado',
  'Run does not have an associated workflow snapshot': 'La ejecucion no tiene una instantanea de workflow asociada',
  'Could not cancel run': 'No se pudo cancelar la ejecucion',
  'Could not load workflow': 'No se pudo cargar el workflow',
  'Could not retry run': 'No se pudo reintentar la ejecucion',
  'Could not reorder queue': 'No se pudo reordenar la cola',
  'Could not clear queue': 'No se pudo limpiar la cola',
  'Could not clear history': 'No se pudo limpiar el historial',
  'Could not delete run': 'No se pudo eliminar la ejecucion',
  'Run A': 'Ejecucion A',
  'Run B': 'Ejecucion B',
  ' (loading...)': ' (cargando...)',
  'No run selected': 'Ninguna ejecucion seleccionada',
  '{{nodes}} - {{artifacts}}': '{{nodes}} - {{artifacts}}',
  '{{count}} node': '{{count}} nodo',
  '{{count}} nodes': '{{count}} nodos',
  '{{count}} artifact': '{{count}} artefacto',
  '{{count}} artifacts': '{{count}} artefactos',
  '- started {{time}}': '- iniciada {{time}}',
  'Per-node status ({{count}})': 'Estado por nodo ({{count}})',
  'Artifacts ({{count}})': 'Artefactos ({{count}})',
  'No nodes in either run.': 'No hay nodos en ninguna ejecucion.',
  'Neither run produced artifacts yet.': 'Ninguna ejecucion produjo artefactos todavia.',
  '- pick a run -': '- elige una ejecucion -',
  '{{name}} - {{status}} - {{runId}}': '{{name}} - {{status}} - {{runId}}',
  'message': 'mensaje',
  'Left run: {{message}}': 'Ejecucion izquierda: {{message}}',
  'Right run: {{message}}': 'Ejecucion derecha: {{message}}',
  'All': 'Todas',
  'Completed': 'Completadas',
  'Errors': 'Errores',
  'Cancelled': 'Canceladas',
  'pending': 'pendiente',
  'running': 'ejecutando',
  'completed': 'completada',
  'cancelled': 'cancelada',
  'failed': 'fallida',
  'Statistics': 'Estadisticas', 'Node map': 'Mapa de nodos',
  'Minimap': 'Minimapa', 'Notes': 'Notas',
  'Close inspector': 'Cerrar inspector',
  'No node selected': 'Ningun nodo seleccionado',
  'Click any node on the canvas to edit its parameters here. Double-click also opens a floating editor.': 'Haz clic en cualquier nodo del lienzo para editar sus parametros aqui. Doble clic tambien abre un editor flotante.',
  'Search nodes...': 'Buscar nodos...', 'Search nodes': 'Buscar nodos', 'No nodes found': 'No se encontraron nodos',
  'Favourites': 'Favoritos', 'All categories': 'Todas las categorias',
  'Add to canvas': 'Agregar al lienzo',
  'Pin node': 'Fijar nodo', 'Unpin node': 'Desfijar nodo',
  '{{count}} fuzzy match': '{{count}} coincidencia aproximada',
  '{{count}} fuzzy matches': '{{count}} coincidencias aproximadas',
  'No nodes match "{{query}}"': 'Ningun nodo coincide con "{{query}}"',
  'Show Advanced': 'Mostrar avanzados',
  'Hide Advanced': 'Ocultar avanzados',
  'adv': 'avanzado',
  'Required Tools': 'Herramientas requeridas',
  'Documentation ↗': 'Documentacion ↗',
  'Open Documentation ↗': 'Abrir documentacion ↗',
  'Drop file or type path...': 'Suelta un archivo o escribe una ruta...',
  'Drop directory or type path...': 'Suelta un directorio o escribe una ruta...',
  'Required Inputs': 'Entradas obligatorias',
  'Optional Inputs': 'Entradas opcionales',
  'Metadata': 'Metadatos',
  'Version': 'Version',
  'Requires': 'Requiere',
  'Aliases': 'Alias',
  'Default': 'Predeterminado',
};
