"""Comet 2024.01.1 database-search contract."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .adapter import (
    ProteomicsCommandNode,
    path_value,
    replace_assignments,
    require_file,
    validate_int,
    validate_number,
)


class CometNode(ProteomicsCommandNode):
    """Search one spectrum file with a version-matched Comet parameter template."""

    NODE_ID = "comet"
    DISPLAY_NAME = "Comet"
    DESCRIPTION = "Search one MS/MS spectrum file with Comet 2024.01.1."
    SEARCH_ALIASES = ["BioNodulo builtin", "Comet", "MS/MS", "peptide identification", "pepXML"]
    RETURN_TYPES = ("FILE", "TSV", "FILE")
    RETURN_NAMES = ("pep_xml", "psm_tsv", "params")
    REQUIRED_EXECUTABLES = ["comet"]
    REQUIRED_CONDA_PACKAGES = ["comet-ms"]
    REQUIRED_PATH_INPUTS = ("spectra_file", "fasta_db", "params_template")
    VERSION = "2024.01.1"
    GIT_URL = "https://github.com/UWPR/Comet.git"
    GIT_COMMIT = "b23621001caeb758c1727bc1dafd7ec1f9b2bd15"
    DOCUMENTATION_URL = "https://uwpr.github.io/Comet/"
    UPSTREAM_SOURCE = "Comet.cpp command-line parser and generated comet.params contract"
    PACKAGE_AUTHORITY = (
        "Bioconda comet-ms 2024011 recipe at "
        "0f45cb6931cc383705d156ad4e7e8c7e5015b505"
    )
    CITATION_DOIS = ["10.1007/s13361-015-1179-x"]
    CITATION_URLS = ["https://doi.org/10.1007/s13361-015-1179-x"]
    CITATION_TEXT = "Comet: an open-source MS/MS sequence database search tool."
    PARAMETER_HEADER = "# comet_version 2024.01 rev. 1"
    RUN_IN_NODE_OUTPUT_DIR = True

    @classmethod
    def INPUT_TYPES(cls) -> dict[str, dict[str, Any]]:
        return {
            "required": {
                "spectra_file": ("FILE", {"description": "One mzML, mzXML, MGF, RAW, or MS2 file"}),
                "fasta_db": ("FASTA", {"description": "Protein sequence database"}),
                "params_template": (
                    "FILE",
                    {"description": "comet.params generated by Comet 2024.01.1"},
                ),
            },
            "optional": {
                "threads": ("INT", {"default": 4, "min": 0, "max": 128}),
                "peptide_mass_tolerance_lower": ("FLOAT", {"default": -20.0}),
                "peptide_mass_tolerance_upper": ("FLOAT", {"default": 20.0}),
                "peptide_mass_units": (
                    "INT",
                    {"default": 2, "min": 0, "max": 2, "label": "0=amu, 1=mmu, 2=ppm"},
                ),
                "fragment_bin_tol": ("FLOAT", {"default": 0.02, "min": 0.0}),
                "fragment_bin_offset": ("FLOAT", {"default": 0.0}),
                "search_enzyme_number": ("INT", {"default": 1, "min": 0}),
                "allowed_missed_cleavage": ("INT", {"default": 2, "min": 0, "max": 5}),
                "decoy_search": (
                    "INT",
                    {
                        "default": 1,
                        "options": [0, 1],
                        "description": "No decoys or concatenated target-decoy output; separate decoy files are not exposed",
                    },
                ),
            },
            "hidden": {"output": ("STRING", {})},
        }

    @classmethod
    def VALIDATE_INPUTS(cls, inputs: dict[str, Any]) -> bool | str:
        validation = super().VALIDATE_INPUTS(inputs)
        if validation is not True:
            return validation
        for key, default, minimum, maximum in (
            ("threads", 4, 0, 128),
            ("peptide_mass_units", 2, 0, 2),
            ("search_enzyme_number", 1, 0, None),
            ("allowed_missed_cleavage", 2, 0, 5),
            ("decoy_search", 1, 0, 1),
        ):
            validation = validate_int(inputs.get(key, default), key, minimum=minimum, maximum=maximum)
            if validation is not True:
                return validation
        for key, default, minimum in (
            ("peptide_mass_tolerance_lower", -20.0, None),
            ("peptide_mass_tolerance_upper", 20.0, None),
            ("fragment_bin_tol", 0.02, 0.0),
            ("fragment_bin_offset", 0.0, None),
        ):
            validation = validate_number(inputs.get(key, default), key, minimum=minimum)
            if validation is not True:
                return validation
        if float(inputs.get("peptide_mass_tolerance_lower", -20.0)) > float(
            inputs.get("peptide_mass_tolerance_upper", 20.0)
        ):
            return "Input 'peptide_mass_tolerance_lower' must not exceed 'peptide_mass_tolerance_upper'"
        return True

    @classmethod
    def PLAN_OUTPUTS(cls, inputs: dict[str, Any], output_dir: str | Path) -> list[Path]:
        node_dir = Path(output_dir) / cls.NODE_ID
        node_dir.mkdir(parents=True, exist_ok=True)
        return [node_dir / "comet.pep.xml", node_dir / "comet.txt", node_dir / "comet.params"]

    @classmethod
    def PREPARE_EXECUTION(cls, inputs: dict[str, Any], outputs: list[Path]) -> None:
        cls.require_valid_inputs(inputs)
        template = require_file(inputs["params_template"], "params_template")
        text = template.read_text(encoding="utf-8")
        first_line = next((line.strip() for line in text.splitlines() if line.strip()), "")
        if first_line != cls.PARAMETER_HEADER:
            raise ValueError(f"Comet parameter template must start with '{cls.PARAMETER_HEADER}'")
        rendered = replace_assignments(
            text,
            {
                "database_name": str(Path(path_value(inputs["fasta_db"])).resolve()),
                "num_threads": inputs.get("threads", 4),
                "peptide_mass_tolerance_lower": inputs.get("peptide_mass_tolerance_lower", -20.0),
                "peptide_mass_tolerance_upper": inputs.get("peptide_mass_tolerance_upper", 20.0),
                "peptide_mass_units": inputs.get("peptide_mass_units", 2),
                "fragment_bin_tol": inputs.get("fragment_bin_tol", 0.02),
                "fragment_bin_offset": inputs.get("fragment_bin_offset", 0.0),
                "search_enzyme_number": inputs.get("search_enzyme_number", 1),
                "allowed_missed_cleavage": inputs.get("allowed_missed_cleavage", 2),
                "decoy_search": inputs.get("decoy_search", 1),
                "output_pepxmlfile": 1,
                "output_txtfile": 1,
            },
        )
        outputs[2].write_text(rendered, encoding="utf-8")
        inputs["_comet_params"] = str(outputs[2])

    @classmethod
    def render_command(cls, inputs: dict[str, Any]) -> list[str]:
        cls.require_valid_inputs(inputs)
        output = Path(path_value(inputs.get("output", ".")))
        params = str(inputs.get("_comet_params", output / "comet.params"))
        return [
            "comet",
            f"-P{params}",
            f"-D{path_value(inputs['fasta_db'])}",
            f"-N{output / 'comet'}",
            path_value(inputs["spectra_file"]),
        ]
