"""
NextFlow import/export converter.

Converts BioNodulo workflows to NextFlow main.nf scripts and vice versa.
"""

from __future__ import annotations

import re
import shlex
from collections import deque
from pathlib import Path
from typing import Any

from bionodulo.converter.edge_utils import (
    edge_source, edge_source_port, edge_target, edge_target_port, executable_edges, executable_nodes, node_outputs, validate_edge_ports,
)
from bionodulo.converter.node_adapter import canonicalize_foreign_workflow, node_option_widgets
from bionodulo.converter.roundtrip import restore_workflow_source, stamp_workflow_source


def export_to_nextflow(
    workflow: dict[str, Any],
    output_path: str | Path | None = None,
) -> str:
    """Convert a BioNodulo workflow to a NextFlow main.nf script.

    Args:
        workflow: BioNodulo workflow dict with ``nodes`` and ``edges``.
        output_path: If given, write the script to this path.

    Returns:
        The NextFlow script content as a string.
    """
    nodes = executable_nodes(workflow)
    edges = executable_edges(workflow, nodes)
    validate_edge_ports(nodes, edges)

    incoming: dict[str, list[dict[str, Any]]] = {nid: [] for nid in nodes}
    outgoing: dict[str, list[dict[str, Any]]] = {nid: [] for nid in nodes}
    for edge in edges:
        src = edge_source(edge)
        tgt = edge_target(edge)
        if src in nodes and tgt in nodes:
            required_input = "reads" if nodes[tgt].get("type") == "fastqc" else "reports"
            if edge_target_port(edge) != required_input:
                raise ValueError(f"Nextflow export cannot bind {required_input!r} from edge {edge.get('id', '')!r}")
            if (nodes[tgt].get("type") != "multiqc" or
                    nodes[src].get("type") != "fastqc" or edge_source_port(edge) != "report_dir"):
                raise ValueError("Nextflow export supports only FastQC.report_dir to MultiQC.reports edges")
            incoming[tgt].append(edge)
            outgoing[src].append(edge)

    process_names = {nid: _sanitize_process_name(nid) for nid in nodes}
    if len(set(process_names.values())) != len(process_names):
        raise ValueError("Nextflow export has colliding process names after sanitization")
    for node_id, node in nodes.items():
        outputs = node_outputs(node)
        if node.get("type") not in {"fastqc", "multiqc"}:
            raise ValueError(f"Cannot export unsupported node type '{node.get('type')}' to NextFlow")
        ports = set(outputs)
        required_ports = {"report_dir"} if node.get("type") == "fastqc" else {"report", "data_dir"}
        if ports != required_ports or len(incoming[node_id]) > 1:
            raise ValueError("Nextflow export requires supported FastQC/MultiQC output ports and at most one incoming edge")
        supported_widgets = ({"input_path", "threads", "kmers", "nogroup", "extract", "format", "contaminants", "adapters", "limits"} if node.get("type") == "fastqc" else {"input_path", "title", "comment", "filename", "force"})
        options = node_option_widgets(node, connected_inputs={edge_target_port(e) for e in incoming[node_id]})
        ignored = set(options) - supported_widgets
        if ignored:
            raise ValueError(f"Nextflow export cannot preserve widgets: {', '.join(sorted(ignored))}")
        if node.get("type") == "fastqc" and any(
            options.get(name) for name in ("contaminants", "adapters", "limits")
        ):
            raise ValueError("Nextflow export cannot stage FastQC adapter/contaminant/limits files")

    lines: list[str] = [
        "#!/usr/bin/env nextflow",
        "// Auto-generated by BioNodulo v2",
        "",
        "nextflow.enable.dsl=2",
        "",
    ]

    for node_id, node in nodes.items():
        node_type = node.get("type", "unknown")
        meta = node.get("meta", {})
        widgets = node_option_widgets(node, connected_inputs={edge_target_port(e) for e in incoming[node_id]})
        process_name = process_names[node_id]
        lines.append("process " + process_name + " {")
        lines.append('    tag "' + process_name + '"')

        container = meta.get("container") or widgets.get("container")
        conda_env = meta.get("conda_env") or widgets.get("conda_env")
        if container:
            lines.append('    container ' + _groovy_string(container))
        if conda_env:
            lines.append('    conda ' + _groovy_string(conda_env))

        cpus = meta.get("threads") or widgets.get("threads")
        memory = meta.get("memory") or widgets.get("memory")
        if cpus:
            lines.append("    cpus " + str(cpus))
        if memory:
            lines.append("    memory '" + str(memory) + " MB'")

        lines.append("    input:")
        lines.append("        path input_0")

        output_defs: list[str] = []
        for port in node_outputs(node):
            output_defs.append('        path "' + port + '_output", emit: ' + port)
        if output_defs:
            lines.append("    output:")
            lines.extend(output_defs)

        command = _build_nextflow_script(node_type, widgets, incoming[node_id], next(iter(node_outputs(node))) + "_output")
        lines.append("    script:")
        lines.append('        """')
        lines.append(command)
        lines.append('        """')
        lines.append("}")
        lines.append("")

    lines.append("workflow {")
    input_nodes = [nid for nid, inc in incoming.items() if not inc]
    for nid in input_nodes:
        var = "ch_" + process_names[nid]
        input_path = node_option_widgets(nodes[nid]).get("input_path")
        if input_path:
            lines.append(f"    params.{process_names[nid]}_input = {_groovy_string(input_path)}")
        lines.append(f"    {var} = Channel.fromPath(params.{process_names[nid]}_input)")

    for node_id in _topological_sort_nf(nodes, incoming):
        process_name = _sanitize_process_name(node_id)
        inc = incoming[node_id]
        if inc:
            edge = inc[0]
            source = process_names[str(edge_source(edge))]
            lines.append("    " + process_name + "(" + source + ".out." + edge_source_port(edge) + ")")
        else:
            lines.append("    " + process_name + "(ch_" + process_name + ")")

    lines.append("}")

    content = stamp_workflow_source("\n".join(lines), workflow, "//")
    if output_path:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
    return content


def import_from_nextflow(
    script_content: str,
    workflow_id: str = "imported_nextflow",
) -> dict[str, Any]:
    """Parse a NextFlow main.nf script into a BioNodulo workflow."""
    original = restore_workflow_source(script_content, "//")
    if original is not None:
        return original
    _validate_foreign_nextflow(script_content)
    processes = _parse_processes(script_content)
    workflow_block = _parse_workflow_block(script_content)
    if not processes:
        raise ValueError("No supported Nextflow processes found")
    process_names = {process["name"] for process in processes}
    called_names = {call["process"] for call in workflow_block["calls"]}
    if not called_names or called_names != process_names or len(workflow_block["calls"]) != len(processes):
        raise ValueError("Nextflow import requires one workflow call for each process")

    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    node_id_map: dict[str, str] = {}

    for proc in processes:
        proc_name = proc["name"]
        node_id = "node_" + proc_name
        node_id_map[proc_name] = node_id
        node_type = "generic_command"

        inputs = {}
        for i, inp in enumerate(proc.get("inputs", [])):
            inputs["input_" + str(i)] = {"type": "FILE", "value": inp}

        outputs = {}
        for i, out in enumerate(proc.get("outputs", [])):
            outputs["output_" + str(i)] = {"path": out}

        widgets = dict(proc.get("params", {}))
        if node_type == "generic_command" and proc.get("script"):
            widgets["command"] = str(proc["script"]).strip()

        node = {
            "id": node_id,
            "type": node_type,
            "pos": [100 + len(nodes) * 250, 100 + (len(nodes) % 3) * 200],
            "inputs": inputs,
            "outputs": outputs,
            "widgets": widgets,
            "meta": {
                "threads": proc.get("cpus"),
                "container": proc.get("container"),
                "conda_env": proc.get("conda"),
                "memory": proc.get("memory"),
                "import_status": "structural_only",
            },
        }
        nodes.append(node)

    channel_to_node: dict[str, str] = {}
    for call in workflow_block.get("calls", []):
        proc_name = call["process"]
        output_ch = call.get("output_channel")
        if output_ch and proc_name in node_id_map:
            channel_to_node[output_ch] = node_id_map[proc_name]

    for call in workflow_block.get("calls", []):
        tgt_proc = call["process"]
        tgt_id = node_id_map.get(tgt_proc, "")
        for inp_ch in call.get("input_channels", []):
            if inp_ch in channel_to_node:
                src_id = channel_to_node[inp_ch]
                edges.append({
                    "id": "edge_" + src_id + "_" + tgt_id,
                    "source": src_id,
                    "target": tgt_id,
                    "source_output": "default",
                    "target_input": "default",
                })

    return canonicalize_foreign_workflow({
        "id": workflow_id,
        "name": "Imported NextFlow Workflow",
        "nodes": nodes,
        "edges": edges,
    })


def _sanitize_process_name(name: str) -> str:
    sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    sanitized = re.sub(r"_+", "_", sanitized).strip("_")
    if sanitized and sanitized[0].isdigit():
        sanitized = "proc_" + sanitized
    return sanitized or "unnamed_process"


def _shell_arg(value: Any) -> str:
    return shlex.quote(str(value)).replace("\\", "\\\\").replace("$", "\\$")


def _groovy_string(value: Any) -> str:
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def _build_nextflow_script(
    node_type: str,
    widgets: dict[str, Any],
    incoming_edges: list[dict[str, Any]],
    out_file: str,
) -> str:
    in_file = "${input_0}"
    # Nextflow escapes staged TaskPath interpolation for the shell. Wrapping
    # it in quotes makes an escaped space a literal backslash in the filename.
    q_in = in_file
    q_out = _shell_arg(out_file)
    if node_type == "fastqc" and out_file == "report_dir_output":
        flags = ["--threads", _shell_arg(widgets.get("threads", 1))]
        for name in ("nogroup", "extract"):
            if widgets.get(name):
                flags.append("--" + name)
        for name in ("kmers", "format", "contaminants", "adapters", "limits"):
            if widgets.get(name) not in (None, ""):
                flags.extend(["--" + name, _shell_arg(widgets[name])])
        return "mkdir -p report_dir_output\nfastqc " + " ".join(flags) + " --outdir report_dir_output " + q_in
    if node_type == "multiqc" and out_file == "report_output":
        stem = str(widgets.get("filename") or "multiqc_report").removesuffix(".html")
        if not stem or "/" in stem or "\\" in stem or stem in {".", ".."}:
            raise ValueError("MultiQC export requires a filename basename")
        flags = ["--filename", _shell_arg(stem), "--force"]
        for name in ("title", "comment"):
            if widgets.get(name):
                flags.extend(["--" + name, _shell_arg(widgets[name])])
        return (
            "multiqc " + q_in + " --outdir . " + " ".join(flags)
            + "\nmv -- " + _shell_arg(stem + ".html") + " report_output"
            + "\nmv -- " + _shell_arg(stem + "_data") + " data_dir_output"
        )
    q_index = _shell_arg(widgets.get("index", "index"))
    q_ref = _shell_arg(widgets.get("ref", "ref.fa"))
    q_genome_dir = _shell_arg(widgets.get("genome_dir", "./"))
    q_annotation = _shell_arg(widgets.get("annotation", "anno.gtf"))
    q_db = _shell_arg(widgets.get("db", "db"))

    templates: dict[str, str] = {
        "fastqc": f"fastqc -o . {q_in}\nmv -- *_fastqc.{('zip' if out_file.startswith('zip_') else 'html')} {q_out}",
        "multiqc": f"mkdir -p .multiqc_input\ncp {q_in} .multiqc_input/input_fastqc.zip\nmultiqc .multiqc_input -o .\nmv -- multiqc_report.html {q_out}",
        "fastp": f"fastp -i {q_in} -o {q_out}",
        "trimmomatic": f"trimmomatic PE {q_in} {q_out}",
        "bowtie2": f"bowtie2 -x {q_index} -U {q_in} -S {q_out}",
        "bwa": f"bwa mem {q_index} {q_in} > {q_out}",
        "samtools_sort": f"samtools sort {q_in} -o {q_out}",
        "samtools_index": f"samtools index {q_in}",
        "bcftools": f"bcftools mpileup -f {q_ref} {q_in} | bcftools call -mv -o {q_out}",
        "spades": f"spades.py -1 {q_in} -o {q_out}",
        "prokka": f"prokka --outdir . {q_in}",
        "star": f"STAR --genomeDir {q_genome_dir} --readFilesIn {q_in} --outFileNamePrefix {q_out}",
        "hisat2": f"hisat2 -x {q_index} -U {q_in} -S {q_out}",
        "salmon": f"salmon quant -i {q_index} -l A -r {q_in} -o {q_out}",
        "featurecounts": f"featureCounts -a {q_annotation} -o {q_out} {q_in}",
        "kraken2": f"kraken2 --db {q_db} {q_in} --output {q_out}",
        "iqtree": f"iqtree -s {q_in} -pre {q_out}",
    }

    if node_type not in templates:
        raise ValueError(f"Cannot export unsupported node type '{node_type}' to NextFlow")
    return templates[node_type]


def _parse_processes(content: str) -> list[dict[str, Any]]:
    """Parse NextFlow DSL2 processes from script content."""
    processes: list[dict[str, Any]] = []
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        proc_match = re.match(r"process\s+(\w+)\s*\{", line.strip())
        if proc_match:
            proc: dict[str, Any] = {"name": proc_match.group(1), "inputs": [], "outputs": [], "params": {}, "script": ""}
            i += 1
            script_lines: list[str] = []
            while i < len(lines) and lines[i].strip() != "}":
                stripped = lines[i].strip()
                if stripped.startswith("tag "):
                    pass
                elif stripped.startswith("container "):
                    m = re.search(r'"([^"]+)"', stripped)
                    if m:
                        proc["container"] = m.group(1)
                elif stripped.startswith("conda "):
                    m = re.search(r'"([^"]+)"', stripped)
                    if m:
                        proc["conda"] = m.group(1)
                elif stripped.startswith("cpus "):
                    proc["cpus"] = stripped.split(None, 1)[1]
                elif stripped.startswith("memory "):
                    m = re.search(r"'([^']+)'", stripped)
                    if m:
                        proc["memory"] = m.group(1)
                elif stripped == "input:":
                    i += 1
                    while i < len(lines) and lines[i].strip() and not lines[i].strip().endswith(":"):
                        inp_line = lines[i].strip()
                        if inp_line:
                            m = re.search(r"path\s+(\w+)", inp_line)
                            if m:
                                proc["inputs"].append(m.group(1))
                        i += 1
                    continue
                elif stripped == "output:":
                    i += 1
                    while i < len(lines) and lines[i].strip() and not lines[i].strip().endswith(":"):
                        out_line = lines[i].strip()
                        if out_line:
                            m = re.search(r'"([^"]+)"', out_line)
                            if m:
                                proc["outputs"].append(m.group(1))
                        i += 1
                    continue
                elif stripped == "script:":
                    i += 1
                    while i < len(lines) and '"""' not in lines[i]:
                        i += 1
                    i += 1
                    while i < len(lines) and '"""' not in lines[i]:
                        script_lines.append(lines[i])
                        i += 1
                    proc["script"] = "\n".join(script_lines).strip()
                    i += 1
                    continue
                i += 1
            processes.append(proc)
        i += 1
    return processes


def _validate_foreign_nextflow(content: str) -> None:
    """Reject DSL features the lightweight structural parser does not model."""
    unsupported = re.search(
        r"(?m)^\s*(?:include\b|workflow\s+\w+\s*\{|when:|exec:|shell:|stub:|"
        r"publishDir\b|errorStrategy\b|retry\b|take:|emit:|main:|if\s*\(|for\s*\()",
        content,
    )
    if unsupported:
        raise ValueError(f"Unsupported Nextflow construct: {unsupported.group().strip()}")
    workflow = re.search(r"workflow\s*\{(.*?)\}", content, re.DOTALL)
    if workflow:
        for line in workflow.group(1).splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("//"):
                continue
            if re.fullmatch(r"\w+\(\s*\w*\s*\)", stripped):
                continue
            if re.fullmatch(r"\w+\s*=\s*\w+\.out(?:\.\w+)?", stripped):
                continue
            if re.fullmatch(r"\w+\s*=\s*Channel\.fromPath\([^()]+\)", stripped):
                continue
            raise ValueError(f"Unsupported Nextflow workflow expression: {stripped[:60]}")


def _parse_workflow_block(content: str) -> dict[str, Any]:
    """Parse the workflow block from a NextFlow DSL2 script."""
    calls: list[dict[str, Any]] = []
    wf_match = re.search(r"workflow\s*\{(.*?)\}", content, re.DOTALL)
    if not wf_match:
        return {"calls": calls}
    wf_content = wf_match.group(1)
    for line in wf_content.splitlines():
        stripped = line.strip()
        call_match = re.match(r"(\w+)\(([^)]*)\)", stripped)
        if call_match:
            calls.append({
                "process": call_match.group(1),
                "input_channels": [c.strip() for c in call_match.group(2).split(",") if c.strip()],
            })
        assign_match = re.match(r"(\w+)\s*=\s*(\w+)\.out", stripped)
        if assign_match and calls:
            calls[-1]["output_channel"] = assign_match.group(1)
    return {"calls": calls}


def _topological_sort_nf(
    nodes: dict[str, dict[str, Any]],
    incoming: dict[str, list[dict[str, Any]]],
) -> list[str]:
    in_degree = {nid: len(incoming[nid]) for nid in nodes}
    queue = deque(nid for nid, deg in in_degree.items() if deg == 0)
    order: list[str] = []
    while queue:
        nid = queue.popleft()
        order.append(nid)
        for other_nid in nodes:
            for edge in incoming.get(other_nid, []):
                if edge_source(edge) == nid:
                    in_degree[other_nid] -= 1
                    if in_degree[other_nid] == 0:
                        queue.append(other_nid)
    if len(order) != len(nodes):
        return list(nodes.keys())
    return order


def _nextflow_process_to_node_type(proc_name: str, script: str) -> str:
    mapping = {
        "fastqc": "fastqc", "multiqc": "multiqc", "fastp": "fastp",
        "trimmomatic": "trimmomatic", "bowtie2": "bowtie2", "bwa": "bwa_mem",
        "samtools_sort": "samtools_sort", "samtools_index": "samtools_index",
        "bcftools": "bcftools_mpileup", "spades": "spades", "prokka": "prokka",
        "star": "star_align", "hisat2": "hisat2", "salmon": "salmon_quant",
        "featurecounts": "featurecounts", "kraken2": "kraken2", "iqtree": "iqtree",
    }
    for key, val in mapping.items():
        if key in proc_name.lower():
            return val
    for key, val in mapping.items():
        if key in script.lower():
            return val
    return "generic_command"
