"""
SnakeMake import/export converter.

Converts BioNodulo workflows to SnakeMake Snakefiles and vice versa.
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path
from typing import Any

from bionodulo.converter.edge_utils import (
    edge_source, edge_source_port, edge_target, edge_target_port, executable_edges, executable_nodes, node_output_path, node_outputs, validate_edge_ports,
)
from bionodulo.converter.node_adapter import canonicalize_foreign_workflow, node_option_widgets
from bionodulo.converter.roundtrip import restore_workflow_source, stamp_workflow_source


def export_to_snakemake(
    workflow: dict[str, Any],
    output_path: str | Path | None = None,
    env_dir: str = "envs",
) -> str:
    """Convert a BioNodulo workflow to a SnakeMake Snakefile.

    Args:
        workflow: BioNodulo workflow dict with ``nodes`` and ``edges``.
        output_path: If given, write the Snakefile to this path.
        env_dir: Directory for conda environment YAML files.

    Returns:
        The Snakefile content as a string.
    """
    nodes = executable_nodes(workflow)
    edges = executable_edges(workflow, nodes)
    validate_edge_ports(nodes, edges)

    incoming: dict[str, list[dict[str, Any]]] = {nid: [] for nid in nodes}
    outgoing: dict[str, list[dict[str, Any]]] = {nid: [] for nid in nodes}
    for edge in edges:
        src = edge_source(edge)
        tgt = edge_target(edge)
        if src in nodes and tgt in nodes:
            required_input = "reads" if nodes[tgt].get("type") == "fastqc" else "reports"
            if edge_target_port(edge) != required_input:
                raise ValueError(f"Snakemake export cannot bind {required_input!r} from edge {edge.get('id', '')!r}")
            if (nodes[tgt].get("type") != "multiqc" or
                    nodes[src].get("type") != "fastqc" or edge_source_port(edge) != "report_dir"):
                raise ValueError("Snakemake export supports only FastQC.report_dir to MultiQC.reports edges")
            incoming[tgt].append(edge)
            outgoing[src].append(edge)

    rule_names = [_sanitize_rule_name(node_id) for node_id in nodes]
    if len(set(rule_names)) != len(rule_names):
        raise ValueError("Snakemake export has colliding rule names after sanitization")
    for node_id, node in nodes.items():
        if node.get("type") not in {"fastqc", "multiqc"}:
            raise ValueError(f"Cannot export unsupported node type '{node.get('type')}' to SnakeMake")
        ports = set(node_outputs(node))
        required_ports = {"report_dir"} if node.get("type") == "fastqc" else {"report", "data_dir"}
        if ports != required_ports or len(incoming[node_id]) > 1:
            raise ValueError("Snakemake export requires supported FastQC/MultiQC output ports and at most one incoming edge")
        supported_widgets = ({"input_path", "threads", "kmers", "nogroup", "extract", "format", "contaminants", "adapters", "limits"} if node.get("type") == "fastqc" else {"input_path", "title", "comment", "filename", "force"})
        options = node_option_widgets(node, connected_inputs={edge_target_port(e) for e in incoming[node_id]})
        ignored = set(options) - supported_widgets
        if ignored:
            raise ValueError(f"Snakemake export cannot preserve widgets: {', '.join(sorted(ignored))}")
        if node.get("type") == "fastqc" and any(
            options.get(name) for name in ("contaminants", "adapters", "limits")
        ):
            raise ValueError("Snakemake export cannot stage FastQC adapter/contaminant/limits files")

    lines: list[str] = [
        "# Auto-generated by BioNodulo v2",
        "# SnakeMake workflow",
        "",
    ]

    target_nodes = [nid for nid, out in outgoing.items() if not out]
    if target_nodes:
        all_outputs = []
        for nid in target_nodes:
            node = nodes[nid]
            for port, spec in node_outputs(node).items():
                all_outputs.append(repr(node_output_path(nid, port, spec)))
        lines.extend(["rule all:", "    input:"])
        for out in all_outputs:
            lines.append("        " + out + ",")
        lines.append("")

    for node_id, node in nodes.items():
        node_type = node.get("type", "unknown")
        meta = node.get("meta", {})
        widgets = node_option_widgets(node, connected_inputs={edge_target_port(e) for e in incoming[node_id]})
        rule_name = _sanitize_rule_name(node_id)
        lines.append("rule " + rule_name + ":")

        # Inputs
        input_paths: list[str] = []
        for edge in incoming[node_id]:
            src = edge_source(edge)
            src_port = edge_source_port(edge)
            if src in nodes:
                src_node = nodes[src]
                src_out = node_outputs(src_node).get(src_port, {})
                input_paths.append(repr(node_output_path(src, src_port, src_out)))
        if input_paths:
            lines.append("    input:")
            for inp in input_paths:
                lines.append("        " + inp + ",")
        else:
            input_path = widgets.get("input_path")
            lines.append("    input:")
            if input_path:
                lines.append("        " + repr(str(input_path)) + ",")
            else:
                lines.append(f'        lambda wildcards: config["{rule_name}_input"],')

        # Outputs
        output_paths: list[str] = []
        for port, spec in node_outputs(node).items():
            output_expression = repr(node_output_path(node_id, port, spec))
            if port in {"report_dir", "data_dir"}:
                output_expression = f"directory({output_expression})"
            output_paths.append(port + "=" + output_expression)
        if output_paths:
            lines.append("    output:")
            for out in output_paths:
                lines.append("        " + out + ",")

        # Params
        if widgets:
            lines.append("    params:")
            for k, v in widgets.items():
                safe_v = repr(v)
                # Snakemake treats braces in string params as wildcards unless
                # a callable returns the literal value.
                if isinstance(v, str):
                    safe_v = "lambda wildcards: " + safe_v
                lines.append('        ' + k + '=' + safe_v + ',')

        # Conda env
        env = meta.get("conda_env") or widgets.get("conda_env")
        if env:
            env_file = env_dir + "/" + _sanitize_rule_name(env) + ".yaml"
            lines.append('    conda:\n        "' + env_file + '"')

        threads = meta.get("threads") or widgets.get("threads")
        if threads:
            lines.append("    threads: " + str(threads))

        mem = meta.get("memory") or widgets.get("memory")
        if mem:
            lines.append("    resources:\n        mem_mb=" + str(mem))

        command = _build_shell_command(node_type, widgets, input_paths, output_paths)
        lines.append("    shell:\n        " + repr(command))
        lines.append("")

    content = stamp_workflow_source("\n".join(lines), workflow, "#")
    if output_path:
        destination = Path(output_path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
    return content


def import_from_snakemake(
    snakefile_content: str,
    workflow_id: str = "imported_snakemake",
) -> dict[str, Any]:
    """Parse a SnakeMake Snakefile into a BioNodulo workflow."""
    original = restore_workflow_source(snakefile_content, "#")
    if original is not None:
        return original
    _validate_foreign_snakemake(snakefile_content)
    rules = _parse_rules(snakefile_content)
    if not rules:
        raise ValueError("No supported Snakemake rules found")
    unsupported = [rule["name"] for rule in rules if rule["name"] != "all" and not rule.get("shell")]
    if unsupported:
        raise ValueError(
            "Cannot import Snakemake rules without a simple shell directive: "
            + ", ".join(unsupported)
        )
    rules = [rule for rule in rules if rule["name"] != "all"]
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    node_id_map: dict[str, str] = {}

    for rule in rules:
        rule_name = rule["name"]
        node_id = "node_" + rule_name
        node_id_map[rule_name] = node_id
        node_type = "generic_command"

        inputs = {}
        for i, inp in enumerate(rule.get("inputs", [])):
            inputs["input_" + str(i)] = {"type": "FILE", "value": inp}

        outputs = {}
        for out_spec in rule.get("outputs", []):
            if "=" in out_spec:
                port, path = out_spec.split("=", 1)
                outputs[port.strip()] = {"path": path.strip().strip('"').strip("'")}
            else:
                outputs["output_" + str(len(outputs))] = {"path": out_spec.strip().strip('"').strip("'")}

        widgets = dict(rule.get("params", {}))
        if node_type == "generic_command" and rule.get("shell"):
            widgets["command"] = str(rule["shell"]).strip()

        node = {
            "id": node_id,
            "type": node_type,
            "pos": [100 + len(nodes) * 250, 100 + (len(nodes) % 3) * 200],
            "inputs": inputs,
            "outputs": outputs,
            "widgets": widgets,
            "meta": {
                "threads": rule.get("threads"),
                "conda_env": rule.get("conda"),
                "import_status": "structural_only",
            },
        }
        nodes.append(node)

    # Create edges from input references
    output_to_node: dict[str, tuple[str, str]] = {}
    for rule in rules:
        rule_name = rule["name"]
        for index, out_spec in enumerate(rule.get("outputs", [])):
            if "=" in out_spec:
                port, path = out_spec.split("=", 1)
                output_to_node[path.strip().strip('"').strip("'")] = (rule_name, port.strip())
            else:
                output_to_node[out_spec.strip().strip('"').strip("'")] = (rule_name, f"output_{index}")

    for rule in rules:
        tgt_rule = rule["name"]
        tgt_id = node_id_map.get(tgt_rule, "")
        for index, inp in enumerate(rule.get("inputs", [])):
            inp_clean = inp.strip().strip('"').strip("'")
            if inp_clean in output_to_node:
                src_rule, src_port = output_to_node[inp_clean]
                src_id = node_id_map.get(src_rule, "")
                edges.append({
                    "id": "edge_" + src_rule + "_" + tgt_rule,
                    "source": src_id,
                    "target": tgt_id,
                    "source_output": src_port,
                    "target_input": f"input_{index}",
                })

    return canonicalize_foreign_workflow({
        "id": workflow_id,
        "name": "Imported SnakeMake Workflow",
        "nodes": nodes,
        "edges": edges,
    })


def _sanitize_rule_name(name: str) -> str:
    sanitized = re.sub(r"[^a-zA-Z0-9_-]", "_", name)
    sanitized = re.sub(r"_+", "_", sanitized).strip("_")
    if sanitized and sanitized[0].isdigit():
        sanitized = "rule_" + sanitized
    return sanitized or "unnamed_rule"


def _shell_arg(value: Any) -> str:
    raw = str(value)
    if raw == "{input:q}":
        return raw
    return shlex.quote(raw).replace("{", "{{").replace("}", "}}")


def _widget_arg(value: Any) -> str:
    return shlex.quote(str(value)).replace("{", "{{").replace("}", "}}")


def _build_shell_command(
    node_type: str,
    widgets: dict[str, Any],
    inputs: list[str],
    outputs: list[str],
) -> str:
    if node_type == "fastqc" and any(out.startswith("report_dir=") for out in outputs):
        flags = ["--threads", _widget_arg(widgets.get("threads", 1))]
        for name in ("nogroup", "extract"):
            if widgets.get(name):
                flags.append("--" + name)
        for name in ("kmers", "format", "contaminants", "adapters", "limits"):
            if widgets.get(name) not in (None, ""):
                flags.extend(["--" + name, _widget_arg(widgets[name])])
        return "mkdir -p {output.report_dir:q} && fastqc " + " ".join(flags) + " --outdir {output.report_dir:q} {input:q}"
    if node_type == "multiqc" and any(out.startswith("report=") for out in outputs):
        stem = str(widgets.get("filename") or "multiqc_report").removesuffix(".html")
        if not stem or "/" in stem or "\\" in stem or stem in {".", ".."}:
            raise ValueError("MultiQC export requires a filename basename")
        force = widgets.get("force", False)
        if not isinstance(force, bool):
            raise ValueError("MultiQC force option must be a boolean")
        flags = ["--filename", _widget_arg(stem)]
        if force:
            flags.append("--force")
        for name in ("title", "comment"):
            if widgets.get(name):
                flags.extend(["--" + name, _widget_arg(widgets[name])])
        return (
            'multiqc_tmp=$(mktemp -d) && trap \'rm -rf "$multiqc_tmp"\' EXIT && '
            'multiqc {input:q} --outdir "$multiqc_tmp" ' + " ".join(flags)
            + ' && mkdir -p $(dirname {output.report:q}) $(dirname {output.data_dir:q})'
            + ' && mv "$multiqc_tmp"/' + _widget_arg(stem + '.html') + ' {output.report:q}'
            + ' && mv "$multiqc_tmp"/' + _widget_arg(stem + '_data') + ' {output.data_dir:q}'
        )
    output_dict = {}
    for out in outputs:
        if "=" in out:
            k, v = out.split("=", 1)
            output_dict[k.strip()] = v.strip().strip('"').strip("'")
    in_file = "{input:q}"
    out_file = list(output_dict.values())[0] if output_dict else "{output}"
    q_in = _shell_arg(in_file)
    q_out = _shell_arg(out_file)
    q_index = _shell_arg(widgets.get("index", "index"))
    q_ref = _shell_arg(widgets.get("ref", "ref.fa"))
    q_genome_dir = _shell_arg(widgets.get("genome_dir", "./"))
    q_annotation = _shell_arg(widgets.get("annotation", "anno.gtf"))
    q_db = _shell_arg(widgets.get("db", "db"))

    templates: dict[str, str] = {
        "fastqc": f"mkdir -p $(dirname {q_out}) && fastqc -o $(dirname {q_out}) {q_in} && mv $(dirname {q_out})/*_fastqc.{('zip' if out_file.endswith('.zip') else 'html')} {q_out}",
        "multiqc": f"mkdir -p $(dirname {q_out}) && multiqc_tmp=$(mktemp -d) && trap 'rm -rf \"$multiqc_tmp\"' EXIT && cp {q_in} \"$multiqc_tmp/input_fastqc.zip\" && multiqc \"$multiqc_tmp\" -o $(dirname {q_out}) && mv $(dirname {q_out})/multiqc_report.html {q_out}",
        "fastp": f"fastp -i {q_in} -o {q_out}",
        "trimmomatic": f"trimmomatic PE {q_in} {q_out}",
        "bowtie2": f"bowtie2 -x {q_index} -U {q_in} -S {q_out}",
        "bwa": f"bwa mem {q_index} {q_in} > {q_out}",
        "samtools_sort": f"samtools sort {q_in} -o {q_out}",
        "samtools_index": f"samtools index {q_in}",
        "bcftools": f"bcftools mpileup -f {q_ref} {q_in} | bcftools call -mv -o {q_out}",
        "spades": f"spades.py -1 {q_in} -o {q_out}",
        "prokka": f"prokka --outdir {q_out} {q_in}",
        "star": f"STAR --genomeDir {q_genome_dir} --readFilesIn {q_in} --outFileNamePrefix {q_out}",
        "hisat2": f"hisat2 -x {q_index} -U {q_in} -S {q_out}",
        "salmon": f"salmon quant -i {q_index} -l A -r {q_in} -o {q_out}",
        "featurecounts": f"featureCounts -a {q_annotation} -o {q_out} {q_in}",
        "kraken2": f"kraken2 --db {q_db} {q_in} --output {q_out}",
        "iqtree": f"iqtree -s {q_in} -pre {q_out}",
    }

    if node_type not in templates:
        raise ValueError(f"Cannot export unsupported node type '{node_type}' to SnakeMake")
    return templates[node_type]


def _parse_rules(content: str) -> list[dict[str, Any]]:
    """Parse Snakefile content into a list of rule dicts."""
    rules: list[dict[str, Any]] = []
    current_rule: dict[str, Any] | None = None
    current_section: str | None = None

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        rule_match = re.match(r"rule\s+(\w+)\s*:", stripped)
        if rule_match:
            if current_rule:
                rules.append(current_rule)
            current_rule = {"name": rule_match.group(1), "inputs": [], "outputs": [], "params": {}}
            current_section = None
            continue
        section_match = re.match(r"(\w+)\s*:", stripped)
        if section_match and current_rule and line.startswith("    ") and not line.startswith("        "):
            current_section = section_match.group(1)
            continue
        if current_rule and stripped:
            if stripped.endswith(","):
                stripped = stripped[:-1].strip()
            if current_section == "input":
                current_rule["inputs"].append(stripped)
            elif current_section == "output":
                current_rule["outputs"].append(stripped)
            elif current_section == "params":
                if "=" in stripped:
                    k, v = stripped.split("=", 1)
                    current_rule["params"][k.strip()] = v.strip().strip('"').strip("'")
            elif current_section == "shell":
                current_rule.setdefault("shell", "")
                current_rule["shell"] += " " + stripped.strip("'\"")
            elif current_section == "threads":
                current_rule["threads"] = stripped
            elif current_section == "conda":
                current_rule["conda"] = stripped.strip('"').strip("'")
    if current_rule:
        rules.append(current_rule)
    return rules


def _validate_foreign_snakemake(content: str) -> None:
    """Accept only literal, shell-based rules that can be shown as a draft."""
    in_rule = False
    section = ""
    allowed = {"input", "output", "params", "threads", "conda", "shell"}
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith((" ", "\t")):
            if not re.fullmatch(r"rule\s+[A-Za-z_]\w*\s*:", stripped):
                raise ValueError(f"Unsupported Snakemake top-level construct: {stripped[:60]}")
            in_rule, section = True, ""
        elif line.startswith("    ") and not line.startswith("        "):
            directive = stripped.removesuffix(":")
            if not in_rule or directive not in allowed:
                raise ValueError(f"Unsupported Snakemake rule directive: {stripped[:60]}")
            section = directive
        elif not in_rule or not section or "lambda " in stripped or "wildcards" in stripped:
            raise ValueError(f"Unsupported Snakemake rule expression: {stripped[:60]}")


def _snakemake_rule_to_node_type(rule_name: str, shell: str) -> str:
    mapping = {
        "fastqc": "fastqc", "multiqc": "multiqc", "fastp": "fastp",
        "trimmomatic": "trimmomatic", "bowtie2": "bowtie2", "bwa": "bwa_mem",
        "samtools_sort": "samtools_sort", "samtools_index": "samtools_index",
        "bcftools": "bcftools_mpileup", "spades": "spades", "prokka": "prokka",
        "star": "star_align", "hisat2": "hisat2", "salmon": "salmon_quant",
        "featurecounts": "featurecounts", "kraken2": "kraken2", "iqtree": "iqtree",
    }
    for key, val in mapping.items():
        if key in rule_name.lower():
            return val
    for key, val in mapping.items():
        if key in shell.lower():
            return val
    return "generic_command"
