"""
SnakeMake import/export converter.

Converts BioNodulo workflows to SnakeMake Snakefiles and vice versa.
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path
from typing import Any


def export_to_snakemake(
    workflow: dict[str, Any],
    output_path: str | Path | None = None,
    env_dir: str = "envs",
) -> str:
    """Convert a BioNodulo workflow to a SnakeMake Snakefile.

    Args:
        workflow: BioNodulo workflow dict with ``nodes`` and ``edges``.
        output_path: If given, write the Snakefile to this path.
        env_dir: Directory for conda environment YAML files.

    Returns:
        The Snakefile content as a string.
    """
    nodes: dict[str, dict[str, Any]] = {
        n["id"]: n for n in workflow.get("nodes", [])
    }
    edges: list[dict[str, Any]] = workflow.get("edges", [])

    incoming: dict[str, list[dict[str, Any]]] = {nid: [] for nid in nodes}
    outgoing: dict[str, list[dict[str, Any]]] = {nid: [] for nid in nodes}
    for edge in edges:
        src = edge.get("source")
        tgt = edge.get("target")
        if src in nodes and tgt in nodes:
            incoming[tgt].append(edge)
            outgoing[src].append(edge)

    lines: list[str] = [
        "# Auto-generated by BioNodulo v2",
        "# SnakeMake workflow",
        "",
        'configfile: "config.yaml"',
        "",
    ]

    target_nodes = [nid for nid, out in outgoing.items() if not out]
    if target_nodes:
        all_outputs = []
        for nid in target_nodes:
            node = nodes[nid]
            for port, spec in node.get("outputs", {}).items():
                if isinstance(spec, dict) and "path" in spec:
                    all_outputs.append('"' + spec["path"] + '"')
                else:
                    all_outputs.append('"results/' + nid + '/' + port + '_output"')
        lines.extend(["rule all:", "    input:"])
        for out in all_outputs:
            lines.append("        " + out + ",")
        lines.append("")

    for node_id, node in nodes.items():
        node_type = node.get("type", "unknown")
        meta = node.get("meta", {})
        widgets = node.get("widgets", {})
        rule_name = _sanitize_rule_name(node_id)
        lines.append("rule " + rule_name + ":")

        # Inputs
        input_paths: list[str] = []
        for edge in incoming[node_id]:
            src = edge.get("source")
            src_port = edge.get("source_output", "default")
            if src in nodes:
                src_node = nodes[src]
                src_out = src_node.get("outputs", {}).get(src_port, {})
                if isinstance(src_out, dict) and "path" in src_out:
                    input_paths.append('"' + src_out["path"] + '"')
                else:
                    input_paths.append('"results/' + src + '/' + src_port + '_output"')
        if input_paths:
            lines.append("    input:")
            for inp in input_paths:
                lines.append("        " + inp + ",")

        # Outputs
        output_paths: list[str] = []
        for port, spec in node.get("outputs", {}).items():
            if isinstance(spec, dict) and "path" in spec:
                output_paths.append(port + '="' + spec["path"] + '"')
            else:
                output_paths.append(port + '="results/' + node_id + '/' + port + '_output"')
        if output_paths:
            lines.append("    output:")
            for out in output_paths:
                lines.append("        " + out + ",")

        # Params
        if widgets:
            lines.append("    params:")
            for k, v in widgets.items():
                safe_v = shlex.quote(str(v))
                lines.append('        ' + k + '=' + safe_v + ',')

        # Conda env
        env = meta.get("conda_env") or widgets.get("conda_env")
        if env:
            env_file = env_dir + "/" + _sanitize_rule_name(env) + ".yaml"
            lines.append('    conda:\n        "' + env_file + '"')

        threads = meta.get("threads") or widgets.get("threads")
        if threads:
            lines.append("    threads: " + str(threads))

        mem = meta.get("memory") or widgets.get("memory")
        if mem:
            lines.append("    resources:\n        mem_mb=" + str(mem))

        command = _build_shell_command(node_type, widgets, input_paths, output_paths)
        lines.append("    shell:\n        '" + command + "'")
        lines.append("")

    content = "\n".join(lines)
    if output_path:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
    return content


def import_from_snakemake(
    snakefile_content: str,
    workflow_id: str = "imported_snakemake",
) -> dict[str, Any]:
    """Parse a SnakeMake Snakefile into a BioNodulo workflow."""
    rules = _parse_rules(snakefile_content)
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    node_id_map: dict[str, str] = {}

    for rule in rules:
        rule_name = rule["name"]
        node_id = "node_" + rule_name
        node_id_map[rule_name] = node_id
        node_type = _snakemake_rule_to_node_type(rule_name, rule.get("shell", ""))

        inputs = {}
        for i, inp in enumerate(rule.get("inputs", [])):
            inputs["input_" + str(i)] = {"type": "FILE", "value": inp}

        outputs = {}
        for out_spec in rule.get("outputs", []):
            if "=" in out_spec:
                port, path = out_spec.split("=", 1)
                outputs[port.strip()] = {"path": path.strip().strip('"')}
            else:
                outputs["output_" + str(len(outputs))] = {"path": out_spec.strip().strip('"')}

        widgets = dict(rule.get("params", {}))

        node = {
            "id": node_id,
            "type": node_type,
            "pos": [100 + len(nodes) * 250, 100 + (len(nodes) % 3) * 200],
            "inputs": inputs,
            "outputs": outputs,
            "widgets": widgets,
            "meta": {
                "threads": rule.get("threads"),
                "conda_env": rule.get("conda"),
            },
        }
        nodes.append(node)

    # Create edges from input references
    output_to_node: dict[str, str] = {}
    for rule in rules:
        rule_name = rule["name"]
        for out_spec in rule.get("outputs", []):
            if "=" in out_spec:
                _, path = out_spec.split("=", 1)
                output_to_node[path.strip().strip('"')] = rule_name

    for rule in rules:
        tgt_rule = rule["name"]
        tgt_id = node_id_map.get(tgt_rule, "")
        for inp in rule.get("inputs", []):
            inp_clean = inp.strip().strip('"')
            if inp_clean in output_to_node:
                src_rule = output_to_node[inp_clean]
                src_id = node_id_map.get(src_rule, "")
                edges.append({
                    "id": "edge_" + src_rule + "_" + tgt_rule,
                    "source": src_id,
                    "target": tgt_id,
                    "source_output": "default",
                    "target_input": "default",
                })

    return {
        "id": workflow_id,
        "name": "Imported SnakeMake Workflow",
        "nodes": nodes,
        "edges": edges,
    }


def _sanitize_rule_name(name: str) -> str:
    sanitized = re.sub(r"[^a-zA-Z0-9_-]", "_", name)
    sanitized = re.sub(r"_+", "_", sanitized).strip("_")
    if sanitized and sanitized[0].isdigit():
        sanitized = "rule_" + sanitized
    return sanitized or "unnamed_rule"


def _build_shell_command(
    node_type: str,
    widgets: dict[str, Any],
    inputs: list[str],
    outputs: list[str],
) -> str:
    input_paths = [inp.strip('"') for inp in inputs]
    output_dict = {}
    for out in outputs:
        if "=" in out:
            k, v = out.split("=", 1)
            output_dict[k.strip()] = v.strip().strip('"').strip("'")
    in_file = input_paths[0] if input_paths else "{input}"
    out_file = list(output_dict.values())[0] if output_dict else "{output}"

    templates: dict[str, str] = {
        "fastqc": f"fastqc -o $(dirname {out_file}) {in_file}",
        "multiqc": f"multiqc {in_file} -o {out_file}",
        "fastp": f"fastp -i {in_file} -o {out_file}",
        "trimmomatic": f"trimmomatic PE {in_file} {out_file}",
        "bowtie2": "bowtie2 -x " + widgets.get("index", "index") + f" -U {in_file} -S {out_file}",
        "bwa": "bwa mem " + widgets.get("index", "index") + f" {in_file} > {out_file}",
        "samtools_sort": f"samtools sort {in_file} -o {out_file}",
        "samtools_index": f"samtools index {in_file}",
        "bcftools": "bcftools mpileup -f " + widgets.get("ref", "ref.fa") + f" {in_file} | bcftools call -mv -o {out_file}",
        "spades": f"spades.py -1 {in_file} -o {out_file}",
        "prokka": f"prokka --outdir {out_file} {in_file}",
        "star": "STAR --genomeDir " + widgets.get("genome_dir", "./") + f" --readFilesIn {in_file} --outFileNamePrefix {out_file}",
        "hisat2": "hisat2 -x " + widgets.get("index", "index") + f" -U {in_file} -S {out_file}",
        "salmon": "salmon quant -i " + widgets.get("index", "index") + f" -l A -r {in_file} -o {out_file}",
        "featurecounts": "featureCounts -a " + widgets.get("annotation", "anno.gtf") + f" -o {out_file} {in_file}",
        "kraken2": "kraken2 --db " + widgets.get("db", "db") + f" {in_file} --output {out_file}",
        "iqtree": f"iqtree -s {in_file} -pre {out_file}",
    }

    return templates.get(node_type, f"# TODO: implement command for {node_type}\necho \'Running {node_type} on {{input}} -> {{output}}\'")


def _parse_rules(content: str) -> list[dict[str, Any]]:
    """Parse Snakefile content into a list of rule dicts."""
    rules: list[dict[str, Any]] = []
    current_rule: dict[str, Any] | None = None
    current_section: str | None = None

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        rule_match = re.match(r"rule\s+(\w+)\s*:", stripped)
        if rule_match:
            if current_rule:
                rules.append(current_rule)
            current_rule = {"name": rule_match.group(1), "inputs": [], "outputs": [], "params": {}}
            current_section = None
            continue
        section_match = re.match(r"(\w+)\s*:", stripped)
        if section_match and current_rule and not stripped.startswith(" "):
            current_section = section_match.group(1)
            continue
        if current_rule and stripped:
            if stripped.endswith(","):
                stripped = stripped[:-1].strip()
            if current_section == "input":
                current_rule["inputs"].append(stripped)
            elif current_section == "output":
                current_rule["outputs"].append(stripped)
            elif current_section == "params":
                if "=" in stripped:
                    k, v = stripped.split("=", 1)
                    current_rule["params"][k.strip()] = v.strip().strip('"').strip("'")
            elif current_section == "shell":
                current_rule.setdefault("shell", "")
                current_rule["shell"] += " " + stripped.strip("'\"")
            elif current_section == "threads":
                current_rule["threads"] = stripped
            elif current_section == "conda":
                current_rule["conda"] = stripped.strip('"').strip("'")
    if current_rule:
        rules.append(current_rule)
    return rules


def _snakemake_rule_to_node_type(rule_name: str, shell: str) -> str:
    mapping = {
        "fastqc": "fastqc", "multiqc": "multiqc", "fastp": "fastp",
        "trimmomatic": "trimmomatic", "bowtie2": "bowtie2", "bwa": "bwa_mem",
        "samtools_sort": "samtools_sort", "samtools_index": "samtools_index",
        "bcftools": "bcftools_mpileup", "spades": "spades", "prokka": "prokka",
        "star": "star_align", "hisat2": "hisat2", "salmon": "salmon_quant",
        "featurecounts": "featurecounts", "kraken2": "kraken2", "iqtree": "iqtree",
    }
    for key, val in mapping.items():
        if key in rule_name.lower():
            return val
    for key, val in mapping.items():
        if key in shell.lower():
            return val
    return "command"
