#!/usr/bin/env python
"""Determine, by solving, which platforms each committed environment supports.

Predicting macOS support from a table of package names does not work. Three
separate mechanisms defeat it:

  * a version pin with no macOS build for that exact version (blast 2.17.0
    publishes osx-arm64 for other versions, just not that one);
  * a pinned build string that only exists on linux (macs2 py311hdad781d_1);
  * a transitive dependency that runs out of candidates several levels down
    (bcftools 1.24 -> htslib >=1.24 -> no osx-64 build).

Only the solver knows. So this script asks it: for each committed lock, try the
widest platform set, drop whichever macOS platform fails, and record the result
in bionodulo/environments/platform_support.py. Manifest rendering then reads
that recorded answer, which keeps it a pure function of the package set while
making the answer a proven one.

Run after changing any pinned version:

    ./.venv/bin/python scripts/solve_macos_locks.py            # report only
    ./.venv/bin/python scripts/solve_macos_locks.py --write    # update table
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LOCKS = REPO / "bionodulo" / "environments" / "locks"
TABLE = REPO / "bionodulo" / "environments" / "platform_support.py"

BASE = "linux-64"
OPTIONAL = ("osx-64", "osx-arm64")
SOLVE_TIMEOUT_S = 1800

_PLATFORMS_LINE = re.compile(r"^platforms = \[.*?\]$", re.M)


def _pixi() -> str:
    sys.path.insert(0, str(REPO))
    from bionodulo.manager.runtime_installer import get_pixi_path

    pixi = get_pixi_path()
    if pixi is None:
        raise SystemExit("pixi executable not found; install it first")
    return str(pixi)


def _set_platforms(manifest: Path, platforms: list[str]) -> None:
    text = manifest.read_text(encoding="utf-8")
    rendered = ", ".join(f'"{p}"' for p in platforms)
    manifest.write_text(
        _PLATFORMS_LINE.sub(f"platforms = [{rendered}]", text, count=1), encoding="utf-8"
    )


def _solves(pixi: str, manifest: Path) -> bool:
    result = subprocess.run(
        [pixi, "lock", "--manifest-path", str(manifest)],
        capture_output=True,
        text=True,
        timeout=SOLVE_TIMEOUT_S,
    )
    return result.returncode == 0


def _supported_platforms(pixi: str, manifest: Path) -> list[str]:
    """Widest platform set that actually solves, always including linux-64.

    Each optional platform is tested on its own against linux-64 before any are
    combined. Narrowing a single list from the end would lose valid
    combinations: bismark solves on osx-arm64 but not osx-64, so dropping the
    last entry first would discard Apple Silicon support that exists.
    """
    _set_platforms(manifest, [BASE])
    if not _solves(pixi, manifest):
        raise SystemExit(f"{manifest.parent.name} no longer solves for {BASE}")

    supported = []
    for platform in OPTIONAL:
        _set_platforms(manifest, [BASE, platform])
        if _solves(pixi, manifest):
            supported.append(platform)

    # Solving each in isolation does not guarantee they solve together: pixi
    # resolves the manifest as a unit and a shared dependency can be pinned to
    # incompatible builds. Verify the union, and fall back if it fails.
    if len(supported) > 1:
        _set_platforms(manifest, [BASE, *supported])
        if not _solves(pixi, manifest):
            print(f"  {manifest.parent.name}: platforms conflict, keeping {supported[0]}")
            supported = supported[:1]

    result = [BASE, *supported]
    _set_platforms(manifest, result)
    if not _solves(pixi, manifest):  # pragma: no cover - defensive
        raise SystemExit(f"{manifest.parent.name} failed to re-solve its final set")
    return result


def _render_table(support: dict[str, list[str]]) -> str:
    lines = [
        '"""Platforms each committed environment is proven to solve for.',
        "",
        "GENERATED by scripts/solve_macos_locks.py -- do not edit by hand.",
        "",
        "Keyed by environment id (the package-set hash used for lock directory",
        "names). An id absent from this table falls back to linux-64 only, so a",
        "new environment is cloud-runnable before anyone has solved it for macOS.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "ENVIRONMENT_PLATFORMS: dict[str, tuple[str, ...]] = {",
    ]
    for env_id in sorted(support):
        rendered = ", ".join(f'"{p}"' for p in support[env_id])
        lines.append(f'    "{env_id}": ({rendered},),')
    lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="update the generated table")
    args = parser.parse_args()

    pixi = _pixi()
    manifests = sorted(LOCKS.glob("*/pixi.toml"))
    if not manifests:
        raise SystemExit(f"no committed locks under {LOCKS}")

    support: dict[str, list[str]] = {}
    for manifest in manifests:
        env_id = manifest.parent.name
        original = manifest.read_text(encoding="utf-8")
        try:
            platforms = _supported_platforms(pixi, manifest)
        except Exception:
            manifest.write_text(original, encoding="utf-8")
            raise
        support[env_id] = platforms
        if not args.write:
            manifest.write_text(original, encoding="utf-8")
        print(f"{env_id}  {', '.join(platforms)}", flush=True)

    both = sum(1 for p in support.values() if len(p) == 3)
    intel = sum(1 for p in support.values() if p == [BASE, "osx-64"])
    print(
        f"\n{len(support)} environments: {both} all platforms, "
        f"{intel} linux+intel-mac, {len(support) - both - intel} linux only"
    )

    if args.write:
        TABLE.write_text(_render_table(support), encoding="utf-8")
        print(f"wrote {TABLE.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
