from __future__ import annotations

import json
from typing import Any

from bionodulo.nodes.command_node import CommandNode
from bionodulo.nodes.registry import NodeRegistry
from bionodulo.workflow.graph import topological_sort
from bionodulo.workflow.schema import Workflow


SUPPORTED_FORMATS = {"snakemake", "nextflow", "cwl", "wdl"}


def export_workflow(workflow: Workflow, registry: NodeRegistry, fmt: str) -> dict[str, Any]:
    normalized = fmt.lower()
    if normalized not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported export format: {fmt}")
    warnings = _warnings(workflow, registry, production=normalized == "snakemake")
    if normalized == "snakemake":
        content = _snakemake(workflow, registry, warnings)
        filename = "Snakefile"
    elif normalized == "nextflow":
        content = _nextflow(workflow, registry)
        filename = "main.nf"
    elif normalized == "cwl":
        content = _cwl(workflow)
        filename = "workflow.cwl"
    else:
        content = _wdl(workflow)
        filename = "workflow.wdl"
    return {"format": normalized, "filename": filename, "content": content, "warnings": warnings}


def _snakemake(workflow: Workflow, registry: NodeRegistry, warnings: list[str]) -> str:
    lines = [
        "# Auto-generated by BioNodulo.",
        "import json",
        "",
        f"WORKFLOW = {json.dumps(workflow.model_dump(by_alias=True), indent=2, default=str)}",
        "",
        "rule all:",
        "    input:",
        "        expand('runs/{node}/.done', node=[node['id'] for node in WORKFLOW['nodes']])",
        "",
    ]
    for node_id in topological_sort(workflow):
        node = next(item for item in workflow.nodes if item.id == node_id)
        safe = _safe_rule(node.id)
        node_cls = registry.get(node.type) if registry.has(node.type) else None
        command = "echo 'Python-only or unknown BioNodulo node; run in BioNodulo for exact behavior.'"
        if node_cls and issubclass(node_cls, CommandNode):
            command = " ".join(getattr(node_cls, "COMMAND", []) or [f"echo run {node.id}"])
        lines.extend(
            [
                f"rule {safe}:",
                "    output:",
                f"        touch('runs/{node.id}/.done')",
                "    shell:",
                f"        {command!r}",
                "",
            ]
        )
    if warnings:
        lines.extend(["# Export warnings:", *[f"# - {warning}" for warning in warnings]])
    return "\n".join(lines)


def _nextflow(workflow: Workflow, registry: NodeRegistry) -> str:
    body = ["// Experimental BioNodulo Nextflow export.", "workflow {"]
    for node in workflow.nodes:
        body.append(f"  { _safe_rule(node.id) }()")
    body.append("}")
    for node in workflow.nodes:
        body.extend(["", f"process {_safe_rule(node.id)} {{", "  script:", f"  \"\"\"echo {node.type} {node.id}\"\"\"", "}"])
    return "\n".join(body)


def _cwl(workflow: Workflow) -> str:
    steps = "\n".join(f"  {node.id}:\n    run: echo.cwl\n    in: []\n    out: []" for node in workflow.nodes)
    return f"cwlVersion: v1.2\nclass: Workflow\nlabel: {workflow.name}\ninputs: []\noutputs: []\nsteps:\n{steps}\n"


def _wdl(workflow: Workflow) -> str:
    calls = "\n".join(f"  call Echo as {_safe_rule(node.id)}" for node in workflow.nodes)
    return f"version 1.1\nworkflow { _safe_rule(workflow.name or 'BioNoduloWorkflow') } {{\n{calls}\n}}\n\ntask Echo {{\n  command <<< echo bionodulo >>>\n  output {{ String out = read_string(stdout()) }}\n}}\n"


def _warnings(workflow: Workflow, registry: NodeRegistry, *, production: bool) -> list[str]:
    warnings: list[str] = []
    for node in workflow.nodes:
        if not registry.has(node.type):
            warnings.append(f"{node.id}: unknown node type {node.type}.")
            continue
        node_cls = registry.get(node.type)
        if not issubclass(node_cls, CommandNode):
            level = "not production-equivalent" if production else "experimental"
            warnings.append(f"{node.id}: Python-only node is {level} in exported workflow.")
    return warnings


def _safe_rule(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in value)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"node_{cleaned}"
    return cleaned
