"""NodeRegistry - discovers, registers, and manages all BioNodulo nodes.

Supports built-in nodes and custom nodes from external directories.
"""

from __future__ import annotations

import importlib
import importlib.util
import inspect
import json
import logging
import pkgutil
import sys
from pathlib import Path
from typing import Any, ClassVar, Iterator, Optional, Type

from bionodulo.nodes.base import BaseNode
from bionodulo.nodes.command_node import CommandNode

logger = logging.getLogger(__name__)

# Build-time index: {node_id: module_name} for every builtin node. Lets the
# registry LAZILY import only the module that defines a requested node instead
# of eagerly importing all ~1k (soon 10k+) builtin modules on every run (§44).
# Regenerated by scripts/gen_node_index.py; a test asserts it stays fresh.
_NODE_INDEX_PATH = Path(__file__).parent / "node_index.json"


def _load_node_index() -> dict[str, str]:
    try:
        with _NODE_INDEX_PATH.open() as fh:
            data = json.load(fh)
        return data if isinstance(data, dict) else {}
    except (OSError, ValueError):
        # No index (dev tree without it, or malformed) → lazy path disabled;
        # callers fall back to eager load_builtin_nodes().
        return {}


# Prebuilt full metadata (object_info) for every builtin node (§44). Lets the
# editor palette be served WITHOUT importing every node class. Loaded once.
_NODE_METADATA_PATH = Path(__file__).parent / "node_metadata.json"
_BUILTIN_METADATA_CACHE: dict[str, Any] | None = None


def _load_builtin_metadata() -> dict[str, Any]:
    global _BUILTIN_METADATA_CACHE
    if _BUILTIN_METADATA_CACHE is None:
        try:
            with _NODE_METADATA_PATH.open() as fh:
                data = json.load(fh)
            _BUILTIN_METADATA_CACHE = data if isinstance(data, dict) else {}
        except (OSError, ValueError):
            _BUILTIN_METADATA_CACHE = {}
    return _BUILTIN_METADATA_CACHE


class NodeRegistry:
    """Central registry for all node classes in BioNodulo.

    Provides node discovery, registration, metadata queries, and
    dynamic loading of custom node packages.
    """

    _instance: ClassVar[Optional[NodeRegistry]] = None

    _nodes: dict[str, Type[BaseNode]]
    _loaded: set[str]
    _object_info_cache: dict[str, Any] | None
    _node_index: dict[str, str]
    _index_exhausted: bool
    _custom_node_packages: dict[str, dict[str, Any]]
    _custom_node_sources: dict[str, str]
    _custom_node_roots: dict[str, set[str]]
    _custom_node_shadows: dict[
        str,
        list[tuple[Type[BaseNode], dict[str, Any] | None, str | None]],
    ]

    def __new__(cls) -> NodeRegistry:
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._initialise_instance(cls._instance)
        return cls._instance

    @classmethod
    def create_isolated(cls) -> NodeRegistry:
        """Create a non-singleton registry for tests and isolated runtimes."""
        registry = super().__new__(cls)
        cls._initialise_instance(registry)
        return registry

    @staticmethod
    def _initialise_instance(registry: NodeRegistry) -> None:
        registry._nodes = {}
        registry._loaded = set()
        registry._object_info_cache = None
        registry._custom_node_packages = {}
        registry._custom_node_sources = {}
        registry._custom_node_roots = {}
        registry._custom_node_shadows = {}
        # Lazy-load index (§44). Loaded once; empty dict disables the lazy path.
        registry._node_index = _load_node_index()
        registry._index_exhausted = False

    # ── Registration ─────────────────────────────────────────────────

    def register(
        self,
        node_class: Type[BaseNode],
        custom_node_package: dict[str, Any] | None = None,
        custom_node_source: str | None = None,
    ) -> None:
        """Register a single node class.

        Args:
            node_class: A BaseNode subclass to register.
            custom_node_package: Optional manifest package metadata for custom nodes.
            custom_node_source: Optional custom-node root key used for reload cleanup.

        Raises:
            ValueError: If NODE_ID is missing or already registered.
        """
        node_id = node_class.NODE_ID
        if not node_id:
            raise ValueError(f"Node class {node_class.__name__} missing NODE_ID")
        validate_metadata_contract = getattr(node_class, "validate_metadata_contract", None)
        if callable(validate_metadata_contract):
            validate_metadata_contract()
        if node_id in self._nodes:
            logger.warning("Overwriting registered node: %s", node_id)
        previous_node = self._nodes.get(node_id)
        previous_source = self._custom_node_sources.get(node_id)
        if custom_node_source is not None and previous_node is not None and previous_source != custom_node_source:
            previous_package = self._custom_node_packages.get(node_id)
            self._custom_node_shadows.setdefault(node_id, []).append(
                (
                    previous_node,
                    dict(previous_package) if previous_package is not None else None,
                    previous_source,
                )
            )
        elif custom_node_source is None and previous_source:
            self._custom_node_roots.get(previous_source, set()).discard(node_id)
            self._custom_node_shadows.pop(node_id, None)
        self._nodes[node_id] = node_class
        if custom_node_package is None:
            self._custom_node_packages.pop(node_id, None)
        else:
            self._custom_node_packages[node_id] = dict(custom_node_package)
        if previous_source and previous_source != custom_node_source:
            self._custom_node_roots.get(previous_source, set()).discard(node_id)
        if custom_node_source is None:
            self._custom_node_sources.pop(node_id, None)
        else:
            self._custom_node_sources[node_id] = custom_node_source
            self._custom_node_roots.setdefault(custom_node_source, set()).add(node_id)
        self._object_info_cache = None
        logger.debug("Registered node: %s", node_id)

    def get(self, node_id: str) -> Optional[Type[BaseNode]]:
        """Get a registered node class by ID.

        Lazy (§44): if the node isn't registered yet but the build-time index
        knows which module defines it, import ONLY that module and register it.
        This lets a worker resolve a workflow's node types without eagerly
        importing every builtin module. Already-registered nodes (e.g. after an
        eager ``load_builtin_nodes()`` for the editor) short-circuit here.

        Args:
            node_id: The unique node identifier.

        Returns:
            The node class or None if not found (even after a lazy attempt).
        """
        node = self._nodes.get(node_id)
        if node is not None:
            return node
        if self._lazy_import(node_id):
            return self._nodes.get(node_id)
        return None

    def _lazy_import(self, node_id: str) -> bool:
        """Import the single builtin module that defines ``node_id`` (if any).

        Returns True if a module was newly imported (so the caller should re-look
        up). No-ops when there's no index, the id isn't in it, or its module was
        already loaded. Registering a module may pull in a handful of sibling
        nodes from the same file — that's fine and still far cheaper than a full
        walk.
        """
        module_name = self._node_index.get(node_id)
        if not module_name or module_name in self._loaded:
            return False
        try:
            module = importlib.import_module(module_name)
            self.register_from_module(module, own_module_only=True)
            self._loaded.add(module_name)
            return True
        except Exception as exc:  # noqa: BLE001
            logger.warning("Lazy import of %s (for %s) failed: %s", module_name, node_id, exc)
            return False

    def has(self, node_id: str) -> bool:
        """Check if a node ID is registered (lazy-aware, §44).

        Args:
            node_id: The node identifier to check.

        Returns:
            True if the node is registered or resolvable via the lazy index.
        """
        if node_id in self._nodes:
            return True
        if node_id in self._node_index:
            self._lazy_import(node_id)
            return node_id in self._nodes
        return False

    def all(self) -> dict[str, Type[BaseNode]]:
        """Return all registered node classes.

        Returns:
            Dictionary mapping node IDs to node classes.
        """
        return dict(self._nodes)

    def object_info(self, node_id: str | None = None) -> dict[str, Any]:
        """Return node metadata for the frontend registry.

        Args:
            node_id: Optional specific node ID. If None, returns all nodes.

        Returns:
            Dictionary of node metadata keyed by node ID.
        """
        if node_id is not None:
            node_class = self._nodes.get(node_id)
            if node_class is None:
                return {}
            return _to_node_info(
                node_class,
                self._custom_node_packages.get(node_id),
            )

        if self._object_info_cache is None:
            # §44: serve builtin metadata from the prebuilt manifest (no need to
            # import 943→10k node CLASSES just to render the palette). Overlay
            # metadata for anything actually loaded (custom nodes, or builtins a
            # worker lazily imported), so live state always wins over the static
            # snapshot. When the manifest is absent (dev tree without it), fall
            # back to computing from whatever's registered.
            merged: dict[str, Any] = dict(_load_builtin_metadata())
            for nid, nc in self._nodes.items():
                merged[nid] = _to_node_info(nc, self._custom_node_packages.get(nid))
            self._object_info_cache = {k: merged[k] for k in sorted(merged)}
        return self._object_info_cache

    # ── Discovery ────────────────────────────────────────────────────

    def load_builtin_nodes(self) -> int:
        """Import and register all built-in node modules.

        Walks the bionodulo.nodes.builtin package and registers
        all BaseNode subclasses found.

        Returns:
            Number of node classes registered.
        """
        import bionodulo.nodes.builtin as builtin_pkg

        pkg_path = Path(builtin_pkg.__file__).parent
        count = 0

        for module_info in pkgutil.walk_packages([str(pkg_path)], prefix="bionodulo.nodes.builtin."):
            _, full_name, ispkg = module_info
            modname = full_name.rsplit(".", 1)[-1]
            if ispkg or modname.startswith("_"):
                continue
            if full_name in self._loaded:
                continue
            try:
                module = importlib.import_module(full_name)
                count += self.register_from_module(module, own_module_only=True)
                self._loaded.add(full_name)
            except Exception as exc:
                logger.warning("Failed to load builtin module %s: %s", full_name, exc)

        logger.info("Loaded %d nodes from builtin modules", count)
        return count

    def load_custom_nodes(self, custom_nodes_dir: str | Path) -> int:
        """Dynamically load custom nodes from a directory.

        Scans the directory for Python files and packages that define
        BaseNode subclasses and registers them.

        Args:
            custom_nodes_dir: Path to the custom_nodes directory.

        Returns:
            Number of node classes registered.
        """
        custom_path = Path(custom_nodes_dir)
        custom_root = str(custom_path.resolve())
        self._clear_custom_node_root(custom_root)
        if not custom_path.exists():
            logger.info("Custom nodes directory does not exist: %s", custom_path)
            return 0

        count = 0
        before_custom = set(self._nodes.keys())
        sys.path.insert(0, str(custom_path.parent))

        for entry in sorted(custom_path.iterdir()):
            if entry.name.startswith("_") or entry.name.endswith(".pyc"):
                continue

            try:
                if entry.is_file() and entry.suffix == ".py":
                    module = self._load_module_from_path(entry.stem, entry)
                    if module:
                        count += self.register_from_module(module, custom_node_source=custom_root)
                elif entry.is_dir() and (entry / "bionodulo.toml").exists():
                    count += self._load_manifest_package(entry, custom_node_source=custom_root)
                elif entry.is_dir() and (entry / "__init__.py").exists():
                    module = self._load_module_from_path(entry.name, entry / "__init__.py")
                    if module:
                        count += self.register_from_module(module, custom_node_source=custom_root)
            except Exception as exc:
                logger.warning("Failed to load custom node %s: %s", entry.name, exc)

        # Validate custom nodes have GIT_URL
        for node_id, node_class in self._nodes.items():
            if node_id in before_custom:
                continue
            if not node_class.GIT_URL:
                logger.warning(
                    "Custom node '%s' (%s) is missing GIT_URL. "
                    "All custom nodes should declare a git repository for dependency resolution.",
                    node_id,
                    node_class.__name__,
                )

        logger.info("Loaded %d nodes from custom_nodes", count)
        return count

    def _clear_custom_node_root(self, custom_root: str) -> None:
        """Remove nodes previously loaded from one custom node root."""
        node_ids = self._custom_node_roots.pop(custom_root, set())
        if not node_ids:
            return
        for node_id in node_ids:
            if self._custom_node_sources.get(node_id) != custom_root:
                continue
            shadows = self._custom_node_shadows.get(node_id)
            if shadows:
                node_class, package, source = shadows.pop()
                self._nodes[node_id] = node_class
                if package is None:
                    self._custom_node_packages.pop(node_id, None)
                else:
                    self._custom_node_packages[node_id] = dict(package)
                if source is None:
                    self._custom_node_sources.pop(node_id, None)
                else:
                    self._custom_node_sources[node_id] = source
                    self._custom_node_roots.setdefault(source, set()).add(node_id)
                if not shadows:
                    self._custom_node_shadows.pop(node_id, None)
            else:
                self._nodes.pop(node_id, None)
                self._custom_node_packages.pop(node_id, None)
                self._custom_node_sources.pop(node_id, None)
        self._object_info_cache = None

    def _load_manifest_package(self, package_dir: Path, custom_node_source: str) -> int:
        """Load modules declared by a custom node package manifest."""
        try:
            from bionodulo.manager.custom_nodes import load_package_manifest

            manifest = load_package_manifest(package_dir)
        except Exception as exc:
            logger.warning("Failed to load custom node package manifest %s: %s", package_dir, exc)
            return 0

        count = 0
        entrypoints = manifest.entrypoints or ["__init__"]
        for entrypoint in entrypoints:
            module_path = self._entrypoint_path(package_dir, entrypoint)
            if module_path is None:
                logger.warning(
                    "Custom node package %s entrypoint %r was not found",
                    package_dir.name,
                    entrypoint,
                )
                continue
            module_name = self._module_name_for_entrypoint(package_dir.name, entrypoint)
            module = self._load_module_from_path(module_name, module_path)
            if module:
                package_info = {
                    "name": manifest.name,
                    "version": manifest.version,
                    "repository": manifest.repository,
                    "directory": manifest.directory,
                    "entrypoint": entrypoint,
                    "requirements": list(manifest.requirements),
                    "manifest_present": manifest.manifest_present,
                }
                count += self.register_from_module(
                    module,
                    custom_node_package=package_info,
                    custom_node_source=custom_node_source,
                )
        return count

    @staticmethod
    def _entrypoint_path(package_dir: Path, entrypoint: str) -> Path | None:
        """Resolve a manifest entrypoint module path inside a package directory."""
        entry = entrypoint.strip()
        if not entry:
            return None
        package_root = package_dir.resolve()
        parts = [part for part in entry.replace("/", ".").split(".") if part]
        if parts and parts[0] == package_dir.name:
            parts = parts[1:]
        if not parts:
            candidates = [package_dir / "__init__.py"]
        else:
            candidate = package_dir.joinpath(*parts)
            candidates = [candidate.with_suffix(".py"), candidate / "__init__.py"]

        for candidate in candidates:
            try:
                candidate.resolve().relative_to(package_root)
            except ValueError:
                continue
            if candidate.exists() and candidate.is_file():
                return candidate
        return None

    @staticmethod
    def _module_name_for_entrypoint(package_name: str, entrypoint: str) -> str:
        raw = f"bionodulo_custom_{package_name}_{entrypoint}"
        return "".join(char if char.isalnum() or char == "_" else "_" for char in raw)

    def register_from_module(
        self,
        module: Any,
        custom_node_package: dict[str, Any] | None = None,
        custom_node_source: str | None = None,
        own_module_only: bool = False,
    ) -> int:
        """Find and register all BaseNode subclasses in a module.

        Args:
            module: Python module to scan.
            custom_node_package: Optional manifest package metadata for custom nodes.
            custom_node_source: Optional custom-node root key used for reload cleanup.

        Returns:
            Number of node classes registered.
        """
        count = 0
        for _name, obj in inspect.getmembers(module, inspect.isclass):
            if (
                issubclass(obj, BaseNode)
                and obj is not BaseNode
                and obj is not CommandNode
                and obj.NODE_ID
                and (not own_module_only or obj.__module__ == module.__name__)
            ):
                self.register(
                    obj,
                    custom_node_package=custom_node_package,
                    custom_node_source=custom_node_source,
                )
                count += 1
        return count

    def iter_node_classes(self) -> Iterator[Type[BaseNode]]:
        """Yield all registered node classes.

        Yields:
            BaseNode subclasses.
        """
        for node_class in self._nodes.values():
            yield node_class

    def _load_module_from_path(self, name: str, path: Path) -> Any:
        """Dynamically load a module from a file path.

        Args:
            name: Module name.
            path: Path to the Python file.

        Returns:
            Loaded module or None on failure.
        """
        try:
            spec = importlib.util.spec_from_file_location(name, path)
            if spec is None or spec.loader is None:
                return None
            module = importlib.util.module_from_spec(spec)
            sys.modules[name] = module
            spec.loader.exec_module(module)
            return module
        except Exception as exc:
            logger.warning("Failed to load module %s from %s: %s", name, path, exc)
            return None

    def clear(self) -> None:
        """Clear all registrations (primarily for testing)."""
        self._nodes.clear()
        self._loaded.clear()
        self._custom_node_packages.clear()
        self._custom_node_sources.clear()
        self._custom_node_roots.clear()
        self._custom_node_shadows.clear()
        self._object_info_cache = None
        self._index_exhausted = False


# Node types whose primary artifact is a figure/report and so should render
# their preview inline (a collapsible body on the node) instead of requiring a
# separate image_preview/html_preview sink. Custom nodes can opt in with a
# class attribute ``INLINE_PREVIEW = True``.
INLINE_PREVIEW_NODE_IDS: frozenset[str] = frozenset(
    {
        # Generic charts (visualization.py)
        "bar_chart",
        "line_chart",
        "scatter_plot",
        "volcano_plot",
        "ma_plot",
        "heatmap",
        "manhattan_plot",
        "coverage_plot",
        "vcf_stats_chart",
        "forest_plot",
        "circos_plot",
        "phylo_tree_viewer",
        # R / ggplot2
        "r_plot",
        "r_pheatmap",
        # Domain-standard tools that emit a single figure or HTML report.
        # (Multi-figure producers like ``scanpy_umap`` keep explicit preview nodes,
        # one per output, since an inline body can only surface one figure.)
        "quast",
        "krona",
        "nanoplot",
        "multiqc",
        "fastqc",
        "deeptools_plot_heatmap",
        "deeptools_plot_profile",
        "cnvkit_plot",
    }
)


def _is_inline_preview(node_class: Type[BaseNode]) -> bool:
    explicit = getattr(node_class, "INLINE_PREVIEW", None)
    if explicit is not None:
        return bool(explicit)
    return node_class.NODE_ID in INLINE_PREVIEW_NODE_IDS


def _to_node_info(
    node_class: Type[BaseNode],
    custom_node_package: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Convert a BaseNode class to frontend registry metadata.

    Args:
        node_class: The node class to convert.

    Returns:
        Dictionary consumed by the frontend node registry.
    """
    input_types = node_class.INPUT_TYPES()
    required = input_types.get("required", {})
    optional = input_types.get("optional", {})
    hidden = input_types.get("hidden", {})

    node_input: dict[str, Any] = {"required": {}, "optional": {}, "hidden": {}}

    for name, spec in required.items():
        node_input["required"][name] = _to_frontend_input_spec(spec)

    for name, spec in optional.items():
        node_input["optional"][name] = _to_frontend_input_spec(spec)

    for name, spec in hidden.items():
        node_input["hidden"][name] = _to_frontend_input_spec(spec)

    info = {
        "input": node_input,
        "output": list(node_class.RETURN_TYPES),
        "output_name": list(node_class.RETURN_NAMES),
        "name": node_class.NODE_ID,
        "display_name": node_class.DISPLAY_NAME or node_class.NODE_ID,
        "description": node_class.DESCRIPTION,
        "search_aliases": list(node_class.SEARCH_ALIASES),
        "category": node_class.CATEGORY,
        "output_node": node_class.OUTPUT_NODE,
        "inline_preview": _is_inline_preview(node_class),
        "visual_only": node_class.VISUAL_ONLY,
        "experimental": node_class.EXPERIMENTAL,
        "requires_external_tools": getattr(node_class, "REQUIRES_EXTERNAL_TOOLS", True),
        "version": node_class.VERSION,
        "deprecated": node_class.DEPRECATED,
        "deprecation_message": node_class.DEPRECATION_MESSAGE,
        "replaced_by": node_class.REPLACED_BY,
        "lifecycle": node_class.lifecycle_metadata(),
        "versioning": node_class.versioning_metadata(),
        "builtin": node_class.__module__.startswith("bionodulo.nodes.builtin"),
        "python_class": f"{node_class.__module__}.{node_class.__name__}",
        "git_url": node_class.GIT_URL,
        "git_commit": node_class.GIT_COMMIT,
        "required_executables": getattr(node_class, "REQUIRED_EXECUTABLES", []),
        "required_conda_packages": getattr(node_class, "REQUIRED_CONDA_PACKAGES", []),
        "required_r_packages": getattr(node_class, "REQUIRED_R_PACKAGES", []),
        "documentation_url": getattr(node_class, "DOCUMENTATION_URL", ""),
        "citation_dois": list(getattr(node_class, "CITATION_DOIS", [])),
        "citation_urls": list(getattr(node_class, "CITATION_URLS", [])),
        "citation_text": getattr(node_class, "CITATION_TEXT", ""),
    }
    if custom_node_package is not None:
        info["custom_node_package"] = dict(custom_node_package)
    return info


def _to_frontend_input_spec(spec: Any) -> tuple[str, dict[str, Any]]:
    type_name = spec[0] if isinstance(spec, (list, tuple)) else spec
    raw_config = spec[1] if isinstance(spec, (list, tuple)) and len(spec) > 1 else {}
    config = dict(raw_config) if isinstance(raw_config, dict) else {}
    if isinstance(type_name, (list, tuple)):
        config.setdefault("options", list(type_name))
    return (_node_type(type_name), config)


def _node_type(bionodulo_type: str | list | tuple) -> str:
    """Map BioNodulo type names to frontend socket type names.

    Args:
        bionodulo_type: BioNodulo type string (or list/tuple in edge cases).

    Returns:
        Frontend socket type string.
    """
    while isinstance(bionodulo_type, (list, tuple)):
        bionodulo_type = bionodulo_type[0] if len(bionodulo_type) > 0 else "STRING"
    if not isinstance(bionodulo_type, str):
        bionodulo_type = str(bionodulo_type)
    passthrough_types = {
        "STRING",
        "INT",
        "FLOAT",
        "BOOLEAN",
        "FILE",
        "DIRECTORY",
        "INDEX_DIR",
        "FASTQ",
        "FASTQ_LIST",
        "FASTA",
        "FASTA_INDEX",
        "SEQUENCE_DICTIONARY",
        "SAM",
        "BAM",
        "BAI",
        "CRAM",
        "VCF",
        "VCF_GZ",
        "BCF",
        "BWA_MEM2_INDEX",
        "BOWTIE2_INDEX",
        "VCF_INDEX",
        "GFF",
        "GTF",
        "GFF_GTF",
        "BED",
        "BIGWIG",
        "ASSEMBLY",
        "CONTIGS",
        "SCAFFOLDS",
        "HAL",
        "MAF",
        "VG",
        "TAR",
        "GFA",
        "ODGI",
        "GBZ",
        "PHYLOGENY_TREE",
        "IMAGE",
        "H5AD",
        "LOOM",
        "JSON",
        "CSV",
        "TSV",
        "EMBEDDING",
    }
    if bionodulo_type in passthrough_types:
        return bionodulo_type
    if bionodulo_type == "ANY":
        return "*"
    return "STRING"
