from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any, Awaitable, Callable

LogEmit = Callable[[str, str], Awaitable[None]]


async def run_mock_node(
    *,
    node_display_name: str,
    outputs: dict[str, Any],
    node_dir: Path,
    stdout_log: Path,
    emit_log: LogEmit,
) -> None:
    lines = [
        f"Started {node_display_name} in mock mode.",
        "Inspecting inputs and parameters.",
        "Producing placeholder bioinformatics outputs.",
        f"Finished {node_display_name}.",
    ]
    with stdout_log.open("a", encoding="utf-8") as handle:
        for line in lines:
            handle.write(line + "\n")
            await emit_log("stdout", line)
            await asyncio.sleep(0.15)
    for value in _flatten(outputs):
        if isinstance(value, str):
            path = Path(value)
            try:
                path.resolve().relative_to(node_dir.resolve())
            except ValueError:
                continue
            if path.suffix:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(f"Mock output generated by bionodulo for {node_display_name}\n", encoding="utf-8")
            else:
                path.mkdir(parents=True, exist_ok=True)
                (path / "README.txt").write_text(f"Mock directory output for {node_display_name}\n", encoding="utf-8")
    (node_dir / "mock.txt").write_text("This node was executed in mock mode.\n", encoding="utf-8")


def _flatten(value: Any) -> list[Any]:
    if isinstance(value, dict):
        result: list[Any] = []
        for item in value.values():
            result.extend(_flatten(item))
        return result
    if isinstance(value, (list, tuple)):
        result = []
        for item in value:
            result.extend(_flatten(item))
        return result
    return [value]
