"""
Mock execution runner for safe testing.

Creates synthetic output files and stdout logs without invoking real
bioinformatics tools, enabling rapid workflow validation and UI testing.
"""

from __future__ import annotations

import asyncio
import json as json_mod
import random
import string
from pathlib import Path
from typing import Any, Callable


async def run_mock_node(
    node_id: str,
    node_type: str,
    node_dir: str | Path,
    planned_outputs: dict[str, str | Path],
    params: dict[str, Any] | None = None,
    duration_range: tuple[float, float] = (0.1, 0.5),
    emit: Callable[[str, dict[str, Any]], None] | None = None,
) -> dict[str, str]:
    """Execute a mock node run, creating synthetic outputs.

    Args:
        node_id: Unique node identifier.
        node_type: The node's type (e.g. ``"fastqc"``, ``"bowtie2"``).
        node_dir: Working directory for the node.
        planned_outputs: Mapping of output port names to planned file paths.
        params: Node parameters (logged but not otherwise used).
        duration_range: ``(min, max)`` seconds to sleep, simulating runtime.
        emit: Optional callback for log events.

    Returns:
        Mapping of output port names to created file paths.
    """
    node_dir = Path(node_dir)
    node_dir.mkdir(parents=True, exist_ok=True)
    params = params or {}

    def _emit(level: str, message: str) -> None:
        if emit:
            emit("log", {"node_id": node_id, "level": level, "message": message})

    _emit("info", f"[mock] Starting {node_type} (node={node_id})")
    _emit("debug", f"[mock] params={params}")

    duration = random.uniform(*duration_range)
    _emit("debug", f"[mock] Simulating execution for {duration:.2f}s")
    await asyncio.sleep(duration)

    stdout_path = node_dir / "mock_stdout.log"
    stderr_path = node_dir / "mock_stderr.log"
    stdout_content = (
        f"[{node_type}] Mock execution log for {node_id}\n"
        f"Parameters: {params}\n"
        f"Simulated duration: {duration:.2f}s\n"
        f"{''.join(random.choices(string.ascii_letters + string.digits, k=80))}\n"
    )
    stdout_path.write_text(stdout_content, encoding="utf-8")
    stderr_path.write_text("[mock] No errors (mock mode)\n", encoding="utf-8")
    _emit("debug", f"[mock] Wrote stdout -> {stdout_path}")

    created: dict[str, str] = {}
    for port_name, file_path in planned_outputs.items():
        out_path = Path(file_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)

        ext = out_path.suffix.lower()
        if ext in (".fastq", ".fq", ".fasta", ".fa", ".fna"):
            content = _mock_sequence_content(node_type, port_name)
        elif ext in (".sam", ".bam"):
            content = _mock_sam_header(node_type, port_name)
        elif ext in (".vcf",):
            content = _mock_vcf_header(node_type, port_name)
        elif ext in (".html", ".htm"):
            content = _mock_html_report(node_type, node_id, params)
        elif ext in (".json",):
            content = _mock_json_output(node_type, port_name, params)
        elif ext in (".csv", ".tsv", ".txt", ".log", ".out"):
            content = _mock_tabular_content(node_type, port_name)
        elif ext in (".png", ".jpg", ".jpeg", ".gif", ".svg"):
            content = _mock_binary_placeholder(ext)
        else:
            content = (
                f"# Mock output for {node_type}\n"
                f"# Node: {node_id}\n"
                f"# Port: {port_name}\n"
                f"# Generated by BioNodulo mock runner\n"
            )

        if isinstance(content, bytes):
            out_path.write_bytes(content)
        else:
            out_path.write_text(content, encoding="utf-8")

        created[port_name] = str(out_path)
        _emit("debug", f"[mock] Created output '{port_name}' -> {out_path}")

    _emit("info", f"[mock] Completed {node_type} (node={node_id}) outputs={list(created.keys())}")
    return created


def _mock_sequence_content(node_type: str, port_name: str) -> str:
    lines = [f"@SEQ_{node_type}_{i} mock read" for i in range(1, 5)]
    seqs = [
        "ACGTACGTACGTACGTACGTACGTACGTACGTACGTAC",
        "TGCATGCATGCATGCATGCATGCATGCATGCATGCATG",
        "AAAATTTTCCCCGGGGAAAATTTTCCCCGGGGAAAA",
        "ACGTACGTACGTACGTACGTACGTACGTACGTACGTAC",
    ]
    quals = [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ]
    parts = [f"# Mock FASTQ output for {node_type} port={port_name}\n"]
    for hdr, seq, qual in zip(lines, seqs, quals):
        parts.extend([hdr, seq, "+", qual, ""])
    return "\n".join(parts)


def _mock_sam_header(node_type: str, port_name: str) -> str:
    return (
        f"@HD\tVN:1.6\tSO:unsorted\n"
        f"@SQ\tSN:ref\tLN:10000\n"
        f"@PG\tID:{node_type}\tPN:{node_type}\tCL:mock\n"
        f"# Mock SAM output for {node_type} port={port_name}\n"
    )


def _mock_vcf_header(node_type: str, port_name: str) -> str:
    return (
        "##fileformat=VCFv4.2\n"
        "##source=BioNodulo_mock\n"
        f"##node={node_type}\n"
        f"##port={port_name}\n"
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n"
    )


def _mock_html_report(node_type: str, node_id: str, params: dict) -> str:
    return (
        "<!DOCTYPE html>\n"
        "<html><head>"
        f"<title>{node_type} Report - {node_id}</title>"
        "</head><body>\n"
        f"<h1>{node_type} Quality Report</h1>\n"
        f"<p>Node: <code>{node_id}</code></p>\n"
        f"<p>Params: <code>{params}</code></p>\n"
        "<p><em>This is a mock report generated for testing.</em></p>\n"
        "</body></html>\n"
    )


def _mock_json_output(node_type: str, port_name: str, params: dict) -> str:
    return json_mod.dumps(
        {
            "node_type": node_type,
            "port": port_name,
            "params": params,
            "mock": True,
            "summary": {"reads": 10000, "mapped": 9500, "unmapped": 500},
        },
        indent=2,
    )


def _mock_tabular_content(node_type: str, port_name: str) -> str:
    return (
        f"# Mock tabular output for {node_type} port={port_name}\n"
        "sample_id\treads\tmapped\tpercent\n"
        "S001\t10000\t9500\t95.0\n"
        "S002\t12000\t11800\t98.3\n"
        "S003\t8000\t7600\t95.0\n"
    )


def _mock_binary_placeholder(ext: str) -> bytes:
    if ext == ".png":
        return bytes.fromhex(
            "89504e470d0a1a0a0000000d4948445200000001"
            "0000000108080000000054697dd90000000a4944"
            "4154789c63000100000500010d0a2db4000000"
            "0049454e44ae426082"
        )
    if ext in (".jpg", ".jpeg"):
        return bytes.fromhex("ffd8ffe000104a46494600010100000100010000ffdb")
    if ext == ".gif":
        return bytes.fromhex(
            "474946383761000100008000000000ffffff2c"
            "00000000010001000002024401003b"
        )
    return b"\x00" * 16
