import { useState, useRef, useEffect, useMemo } from 'react';
import { useAtomValue, useSetAtom } from 'jotai';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import type { LogEntry, RunRecord, NodeStatus } from '../../types';
import Icon from '../ui/Icon';
import { apiGetText } from '../../api/client';
import { htmlPreviewStateAtom, openLightboxAtom } from '../../state/lightboxAtoms';
import { logError } from '../../state/logging';
import { logsAtom } from '../../state/runAtoms';
import { appPath } from '../../utils/appBase';

function runStatusLabel(t: TFunction, status: RunRecord['status'] | 'failed'): string {
  return t(`console.status.${status}`);
}

type ConsoleTab = 'logs' | 'previews' | 'report';

interface BottomConsoleProps {
  queue: RunRecord[];
  history: RunRecord[];
  onClose: () => void;
  onClearLogs?: () => void;
  /**
   * Mapping from internal node UUID to its human-friendly title/type. When a
   * log entry's `node_id` matches an entry here, we render the friendly name
   * instead of the long UUID. Logs are already grouped by run/workflow so the
   * raw UUID was pure clutter.
   */
  nodeIdToName?: ReadonlyMap<string, string>;
  /**
   * Cloud editor mode. Previews and the HTML report are generated by the local
   * host from on-disk run artifacts (`/api/previews`, `/api/runs/:id/report`),
   * which the stateless editor Lambda can't serve — so those tabs are hidden.
   */
  editorMode?: boolean;
}

const IMAGE_EXTS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.bmp']);
const HTML_EXTS = new Set(['.html', '.htm']);

function isImagePath(path: string): boolean {
  const lower = path.toLowerCase();
  return Array.from(IMAGE_EXTS).some(ext => lower.endsWith(ext));
}

function isHtmlPath(path: string): boolean {
  const lower = path.toLowerCase();
  return Array.from(HTML_EXTS).some(ext => lower.endsWith(ext));
}

function logFallbackLabel(t: TFunction, value: string): string {
  return value === 'unknown' ? t('console.unknownLogLabel') : value;
}

function LogLine({ entry, nodeIdToName, t }: { entry: LogEntry; nodeIdToName?: ReadonlyMap<string, string>; t: TFunction }) {
  const [expanded, setExpanded] = useState(false);
  const level = entry.level || 'info';
  const timestamp = typeof entry.timestamp === 'string' ? entry.timestamp : '';
  const rawNodeId = typeof entry.node_id === 'string' ? entry.node_id : 'unknown';
  // Prefer the friendly node title when we have it. We still keep the raw id
  // accessible via the title attribute for debugging.
  const nodeLabel = nodeIdToName?.get(rawNodeId) ?? logFallbackLabel(t, rawNodeId);
  const message = typeof entry.message === 'string' ? entry.message : '';
  const detail = typeof entry.detail === 'string' ? entry.detail : '';
  const hasDetail = detail.length > 0;

  return (
    <div className={`console-log-line ${level}`}>
      <div className="console-log-main">
        <span className="console-log-ts">[{timestamp ? timestamp.slice(11, 19) : '--:--:--'}]</span>
        <span className="console-log-node" title={rawNodeId !== nodeLabel ? rawNodeId : undefined}>[{nodeLabel}]</span>
        <span className="console-log-msg">{message}</span>
        {hasDetail && (
          <button
            className="console-log-toggle"
            onClick={() => setExpanded(v => !v)}
            title={expanded ? t('console.hideDetails') : t('console.showDetails')}
          >
            <Icon name={expanded ? 'chevronUp' : 'chevronDown'} size={10} />
          </button>
        )}
      </div>
      {expanded && hasDetail && (
        <pre className="console-log-detail">{detail}</pre>
      )}
    </div>
  );
}

function groupLogsByRun(logs: LogEntry[]): Map<string, LogEntry[]> {
  const groups = new Map<string, LogEntry[]>();
  for (const log of logs) {
    const runId = log.run_id || 'unknown';
    const existing = groups.get(runId);
    if (existing) {
      existing.push(log);
    } else {
      groups.set(runId, [log]);
    }
  }
  return groups;
}

function deriveDisplayLogs(logs: LogEntry[]): {
  safeLogs: LogEntry[];
  hostLogs: LogEntry[];
  solverLogs: LogEntry[];
  displayLogs: LogEntry[];
  groupedLogs: Map<string, LogEntry[]>;
  groupedEntries: Array<[string, LogEntry[]]>;
  hasPixiInstallLogs: boolean;
} {
  const safeLogs = Array.isArray(logs) ? logs.filter((l): l is LogEntry => l != null && typeof l === 'object') : [];
  const hostLogs: LogEntry[] = [];
  const solverLogs: LogEntry[] = [];
  const displayLogs: LogEntry[] = [];
  let pendingDetails: string[] = [];

  for (const log of safeLogs) {
    const msg = log.message || '';
    const isSolver = msg.startsWith('[solver]');
    if (isSolver) {
      solverLogs.push(log);
      pendingDetails.push(msg.replace('[solver] ', ''));
      continue;
    }

    hostLogs.push(log);
    if (pendingDetails.length > 0 && displayLogs.length > 0) {
      const last = displayLogs[displayLogs.length - 1];
      displayLogs[displayLogs.length - 1] = { ...last, detail: pendingDetails.join('\n') };
      pendingDetails = [];
    }
    displayLogs.push(log);
  }

  if (pendingDetails.length > 0 && displayLogs.length > 0) {
    const last = displayLogs[displayLogs.length - 1];
    displayLogs[displayLogs.length - 1] = { ...last, detail: pendingDetails.join('\n') };
  }

  const groupedLogs = groupLogsByRun(displayLogs);
  const groupedEntries = Array.from(groupedLogs.entries());
  return {
    safeLogs,
    hostLogs,
    solverLogs,
    displayLogs,
    groupedLogs,
    groupedEntries,
    hasPixiInstallLogs: groupedLogs.has('install-pixi'),
  };
}

function groupLogsByNode(logs: LogEntry[]): Map<string, LogEntry[]> {
  const nodeGroups = new Map<string, LogEntry[]>();
  for (const log of logs) {
    const nodeId = log.node_id || 'unknown';
    const existing = nodeGroups.get(nodeId);
    if (existing) existing.push(log);
    else nodeGroups.set(nodeId, [log]);
  }
  return nodeGroups;
}

function derivePreviews(history: RunRecord[], t: TFunction): {
  imagePreviews: { src: string; alt: string; filename: string; runId: string; nodeId: string }[];
  htmlPreviews: { src: string; filename: string; runId: string; nodeId: string }[];
} {
  const imagePreviews: { src: string; alt: string; filename: string; runId: string; nodeId: string }[] = [];
  const htmlPreviews: { src: string; filename: string; runId: string; nodeId: string }[] = [];
  for (const run of history) {
    const previews = run.previews || {};
    for (const [nodeId, path] of Object.entries(previews)) {
      if (isImagePath(path)) {
        const filename = path.split('/').pop() || `${nodeId}.png`;
        imagePreviews.push({
          src: appPath(`/api/previews/${run.run_id}/${nodeId}?path=${encodeURIComponent(path)}`),
          alt: t('console.previewImageAlt', { node: nodeId }),
          filename,
          runId: run.run_id,
          nodeId,
        });
      } else if (isHtmlPath(path)) {
        const filename = path.split('/').pop() || `${nodeId}.html`;
        htmlPreviews.push({
          src: appPath(`/api/previews/${run.run_id}/${nodeId}?path=${encodeURIComponent(path)}`),
          filename,
          runId: run.run_id,
          nodeId,
        });
      }
    }
  }
  return { imagePreviews, htmlPreviews };
}

function ReportPanel({ history, t }: { history: RunRecord[]; t: TFunction }) {
  const completed = history.filter(r => r.status === 'completed' || r.status === 'error' || r.status === 'cancelled');
  const [selectedRunId, setSelectedRunId] = useState<string | null>(completed[0]?.run_id ?? null);
  const [reportHtml, setReportHtml] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (selectedRunId === null && completed.length > 0) {
      setSelectedRunId(completed[0].run_id);
    }
  }, [completed, selectedRunId]);

  useEffect(() => {
    if (!selectedRunId) {
      setReportHtml(null);
      return;
    }
    const runId = selectedRunId;
    let cancelled = false;
    setLoading(true);
    setError(null);
    fetchReport();
    async function fetchReport() {
      try {
        const text = await apiGetText(`/api/runs/${encodeURIComponent(runId)}/report`);
        if (!cancelled) setReportHtml(text);
      } catch (err) {
        if (!cancelled) {
          logError('console.report.fetch', err);
          setError(t('console.reportLoadError'));
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    return () => { cancelled = true; };
  }, [selectedRunId, t]);

  const downloadManifest = () => {
    if (!selectedRunId) return;
    const url = appPath(`/api/runs/${encodeURIComponent(selectedRunId)}/manifest`);
    const link = document.createElement('a');
    link.href = url;
    link.download = `bionodulo-manifest-${selectedRunId}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (completed.length === 0) {
    return (
      <div style={{ color: 'var(--muted)', padding: 12 }}>
        {t('console.reportEmpty')}
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 8, height: '100%' }}>
      <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
        <label style={{ fontSize: 11, color: 'var(--muted)' }}>{t('console.reportRunLabel')}</label>
        <select
          value={selectedRunId ?? ''}
          onChange={event => setSelectedRunId(event.target.value || null)}
          style={{
            minWidth: 240,
            padding: '4px 8px',
            border: '1px solid var(--border)',
            borderRadius: 6,
            background: 'var(--surface-2)',
            color: 'var(--text)',
            fontSize: 12,
          }}
        >
          {completed.map(run => (
            <option key={run.run_id} value={run.run_id}>
              {run.workflow_name || run.run_id} - {runStatusLabel(t, run.status)}
            </option>
          ))}
        </select>
        <button
          className="btn btn-sm"
          onClick={downloadManifest}
          disabled={!selectedRunId}
          title={t('console.downloadManifestTitle')}
        >
          <Icon name="export" size={12} /> {t('console.manifestJson')}
        </button>
        {selectedRunId && (
          <a
            className="btn btn-sm"
            href={appPath(`/api/runs/${encodeURIComponent(selectedRunId)}/report`)}
            target="_blank"
            rel="noreferrer"
            title={t('console.openReportTitle')}
          >
            <Icon name="link" size={12} /> {t('console.openReport')}
          </a>
        )}
      </div>
      <div style={{ flex: 1, border: '1px solid var(--border)', borderRadius: 6, overflow: 'hidden', minHeight: 200 }}>
        {loading && (
          <div style={{ padding: 12, color: 'var(--muted)' }}>{t('console.loadingReport')}</div>
        )}
        {error && !loading && (
          <div style={{ padding: 12, color: 'var(--danger, #dc3545)' }}>{error}</div>
        )}
        {!loading && !error && reportHtml && (
          <iframe
            title={t('console.runReportTitle')}
            srcDoc={reportHtml}
            sandbox=""
            style={{ width: '100%', height: '100%', minHeight: 200, border: 'none', background: 'white' }}
          />
        )}
      </div>
    </div>
  );
}

export default function BottomConsole({
  queue,
  history,
  onClose,
  onClearLogs,
  nodeIdToName,
  editorMode = false,
}: BottomConsoleProps) {
  const { t } = useTranslation();
  const logs = useAtomValue(logsAtom);
  const openLightbox = useSetAtom(openLightboxAtom);
  const setHtmlPreviewState = useSetAtom(htmlPreviewStateAtom);
  const [tab, setTab] = useState<ConsoleTab>('logs');
  const [showVerbose, setShowVerbose] = useState(true);
  const [expandedRuns, setExpandedRuns] = useState<Set<string>>(new Set());
  const [expandedNodes, setExpandedNodes] = useState<Set<string>>(new Set());
  // Per-node log render caps. Default cap keeps the DOM bounded even when a
  // run dumps tens of thousands of lines (e.g. `--verbose` aligners) — the
  // user can opt to render more on demand.
  const [expandedNodeCaps, setExpandedNodeCaps] = useState<Map<string, number>>(new Map());
  const LOG_RENDER_CAP = 250;
  const LOG_RENDER_STEP = 1000;
  const logsBodyRef = useRef<HTMLDivElement>(null);
  const userScrolledUpRef = useRef(false);

  const {
    safeLogs,
    hostLogs,
    solverLogs,
    groupedEntries,
    hasPixiInstallLogs,
  } = useMemo(() => deriveDisplayLogs(logs), [logs]);

  const toggleRun = (runId: string) => {
    setExpandedRuns(prev => {
      const next = new Set(prev);
      if (next.has(runId)) next.delete(runId);
      else next.add(runId);
      return next;
    });
  };

  const toggleNode = (runId: string, nodeId: string) => {
    const key = `${runId}:${nodeId}`;
    setExpandedNodes(prev => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  // Auto-expand live nodes without overriding a group the user opened.
  useEffect(() => {
    const nextExpanded = new Set<string>();
    const allRuns = new Map<string, RunRecord>();
    for (const r of queue) allRuns.set(r.run_id, r);
    for (const r of history) allRuns.set(r.run_id, r);

    for (const [runId, runLogs] of groupedEntries) {
      const run = allRuns.get(runId);
      const statusMap = new Map<string, NodeStatus['status']>();
      if (run?.node_statuses) {
        for (const ns of run.node_statuses) statusMap.set(ns.node_id, ns.status);
      }
      const nodeIds = new Set(runLogs.map(l => l.node_id || 'unknown'));
      for (const nodeId of nodeIds) {
        const key = `${runId}:${nodeId}`;
        const status = statusMap.get(nodeId);
        if (status === 'running' || status === 'pending') {
          nextExpanded.add(key);
        } else if (status) {
          // completed, error, cached, skipped → collapsed (don't add)
        } else {
          // No status known: infer from log levels
          const nodeLogLevels = runLogs.filter(l => (l.node_id || 'unknown') === nodeId).map(l => l.level);
          const hasCompletion = nodeLogLevels.some(l => l === 'success' || l === 'error');
          if (!hasCompletion) nextExpanded.add(key);
        }
      }
    }
    setExpandedNodes(prev => {
      const next = new Set(prev);
      nextExpanded.forEach(key => next.add(key));
      if (prev.size === next.size && [...prev].every(k => next.has(k))) return prev;
      return next;
    });
  }, [groupedEntries, queue, history]);

  // Pixi installation is triggered from a banner. Keep its live logs visible
  // so the error output does not hide behind a collapsed run while it streams.
  useEffect(() => {
    if (!hasPixiInstallLogs) return;
    setExpandedRuns(prev => {
      if (prev.has('install-pixi')) return prev;
      const next = new Set(prev);
      next.add('install-pixi');
      return next;
    });
    setExpandedNodes(prev => {
      if (prev.has('install-pixi:host')) return prev;
      const next = new Set(prev);
      next.add('install-pixi:host');
      return next;
    });
  }, [hasPixiInstallLogs]);

  // Auto-scroll when logs change (only if user is near bottom)
  useEffect(() => {
    const container = logsBodyRef.current;
    if (!container) return;
    if (!userScrolledUpRef.current) {
      container.scrollTop = container.scrollHeight;
    }
  }, [safeLogs.length]);

  // Auto-scroll to bottom when logs tab becomes active
  useEffect(() => {
    const container = logsBodyRef.current;
    if (!container) return;
    if (tab === 'logs') {
      container.scrollTop = container.scrollHeight;
      userScrolledUpRef.current = false;
    }
  }, [tab]);

  const handleScroll = () => {
    const container = logsBodyRef.current;
    if (!container) return;
    const threshold = 50;
    const isNearBottom = container.scrollHeight - container.scrollTop - container.clientHeight < threshold;
    userScrolledUpRef.current = !isNearBottom;
  };

  const { imagePreviews, htmlPreviews } = useMemo(() => derivePreviews(history, t), [history, t]);

  const handleDoubleClick = (idx: number) => {
    openLightbox({
      images: imagePreviews.map(img => ({ src: img.src, alt: img.alt, filename: img.filename })),
      index: idx,
    });
  };

  const allRunIds = groupedEntries.map(([runId]) => runId);
  const previewCount = imagePreviews.length + htmlPreviews.length;

  return (
    <div className="bottom-console">
      <div className="console-tabs">
        <button className={`console-tab ${tab === 'logs' ? 'active' : ''}`} onClick={() => setTab('logs')}>
          {t('console.tabsLogs')} {hostLogs.length > 0 && `(${hostLogs.length})`}
        </button>
        {!editorMode && (
          <button className={`console-tab ${tab === 'previews' ? 'active' : ''}`} onClick={() => setTab('previews')}>
            {t('console.tabsPreviews')} {previewCount > 0 && `(${previewCount})`}
          </button>
        )}
        {!editorMode && (
          <button className={`console-tab ${tab === 'report' ? 'active' : ''}`} onClick={() => setTab('report')}>
            {t('console.tabsReport')}
          </button>
        )}
        <div style={{ flex: 1 }} />
        {tab === 'logs' && allRunIds.length > 0 && (
          <>
            <button
              className="btn btn-sm btn-ghost"
              onClick={() => setExpandedRuns(new Set(allRunIds))}
              title={t('console.expandAllLogGroups')}
            >
              {t('console.expandAll')}
            </button>
            <button
              className="btn btn-sm btn-ghost"
              onClick={() => setExpandedRuns(new Set())}
              title={t('console.collapseAllLogGroups')}
            >
              {t('console.collapseAll')}
            </button>
          </>
        )}
        {tab === 'logs' && safeLogs.length > 0 && onClearLogs && (
          <button className="btn btn-sm btn-ghost" onClick={onClearLogs} title={t('console.clearAllLogs')}>
            {t('common.clear')}
          </button>
        )}
        {tab === 'logs' && solverLogs.length > 0 && (
          <button
            className="btn btn-sm btn-ghost"
            onClick={() => setShowVerbose(v => !v)}
            title={showVerbose ? t('console.hideSolverDetails') : t('console.showSolverDetails')}
          >
            {showVerbose ? t('console.hideVerbose') : t('console.showVerbose')}
          </button>
        )}
        <button className="btn btn-icon btn-sm" onClick={onClose} title={t('console.closeTitle')} aria-label={t('console.closeTitle')}>
          <Icon name="close" size={14} />
        </button>
      </div>
      <div className="console-body" ref={logsBodyRef} onScroll={handleScroll}>
        {tab === 'logs' && (
          hostLogs.length === 0 && solverLogs.length === 0
            ? <div style={{ color: 'var(--muted)' }}>{t('console.emptyLogs')}</div>
            : (
              <>
                {groupedEntries.map(([runId, runLogs]) => {
                  const isExpanded = expandedRuns.has(runId);
                  const nodeGroups = groupLogsByNode(runLogs);
                  const runLabel = logFallbackLabel(t, runId);
                  return (
                    <div key={runId} className="console-log-group">
                      <button
                        className="console-log-group-header"
                        onClick={() => toggleRun(runId)}
                        title={isExpanded ? t('common.collapse') : t('common.expand')}
                      >
                        <Icon name={isExpanded ? 'chevronDown' : 'chevronRight'} size={12} />
                        <span className="console-log-group-title" title={runLabel !== runId ? runId : undefined}>{runLabel}</span>
                        <span className="console-log-group-count">
                          ({t('console.logGroupCount', { lines: runLogs.length, nodes: nodeGroups.size })})
                        </span>
                      </button>
                      {isExpanded && (
                        <div className="console-log-group-body">
                          {Array.from(nodeGroups.entries()).map(([nodeId, nodeLogs]) => {
                            const nodeKey = `${runId}:${nodeId}`;
                            const isNodeExpanded = expandedNodes.has(nodeKey);
                            const nodeTitle = nodeIdToName?.get(nodeId) ?? logFallbackLabel(t, nodeId);
                            return (
                              <div key={nodeId} className="console-log-node-group">
                                <button
                                  className="console-log-node-header"
                                  onClick={() => toggleNode(runId, nodeId)}
                                  title={isNodeExpanded ? t('console.collapseNode') : t('console.expandNode')}
                                >
                                  <Icon name={isNodeExpanded ? 'chevronDown' : 'chevronRight'} size={10} />
                                  <span className="console-log-node-title" title={nodeTitle !== nodeId ? nodeId : undefined}>{nodeTitle}</span>
                                  <span className="console-log-node-count">({nodeLogs.length})</span>
                                </button>
                                {isNodeExpanded && (() => {
                                  const cap = expandedNodeCaps.get(nodeKey) ?? LOG_RENDER_CAP;
                                  // Always show the tail (most recent lines) — for execution logs
                                  // the newest output is by far the most useful.
                                  const visible = nodeLogs.length > cap ? nodeLogs.slice(-cap) : nodeLogs;
                                  const hidden = nodeLogs.length - visible.length;
                                  return (
                                    <div className="console-log-node-body">
                                      {hidden > 0 && (
                                        <button
                                          type="button"
                                          className="console-log-load-more"
                                          onClick={() => setExpandedNodeCaps(prev => {
                                            const next = new Map(prev);
                                            next.set(nodeKey, cap + LOG_RENDER_STEP);
                                            return next;
                                          })}
                                        >
                                          {t('console.showEarlierLines', { count: Math.min(LOG_RENDER_STEP, hidden), hidden })}
                                        </button>
                                      )}
                                      {visible.map((l, i) => (
                                        <LogLine
                                          key={`${nodeKey}-${nodeLogs.length - visible.length + i}`}
                                          nodeIdToName={nodeIdToName}
                                          t={t}
                                          entry={{
                                            ...l,
                                            detail: showVerbose ? l.detail : undefined,
                                          }}
                                        />
                                      ))}
                                    </div>
                                  );
                                })()}
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  );
                })}
                {!showVerbose && solverLogs.length > 0 && (
                  <div style={{ color: 'var(--muted)', fontSize: 11, padding: '4px 0' }}>
                    {t('console.solverLinesHidden', { count: solverLogs.length })}
                  </div>
                )}
              </>
            )
        )}
        {tab === 'previews' && (
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', overflowY: 'auto' }}>
            {imagePreviews.length === 0 && htmlPreviews.length === 0 ? (
              <div style={{ color: 'var(--muted)' }}>{t('console.emptyPreviews')}</div>
            ) : (
              <>
                {imagePreviews.map((img, idx) => (
                  <div
                    key={`img-${img.runId}-${img.nodeId}`}
                    style={{ textAlign: 'center', cursor: 'pointer' }}
                    onDoubleClick={() => handleDoubleClick(idx)}
                    title={t('console.previewImageTitle')}
                  >
                    <img
                      src={img.src}
                      alt={img.alt}
                      style={{ maxHeight: 180, maxWidth: 280, borderRadius: 6, border: '1px solid var(--border)' }}
                      onError={e => { (e.target as HTMLImageElement).style.display = 'none'; }}
                    />
                    <div style={{ fontSize: 10, color: 'var(--muted)', marginTop: 4 }}>{img.nodeId}</div>
                  </div>
                ))}
                {htmlPreviews.map(htmlItem => (
                  <div
                    key={`html-${htmlItem.runId}-${htmlItem.nodeId}`}
                    style={{
                      width: 260,
                      height: 200,
                      borderRadius: 6,
                      border: '1px solid var(--border)',
                      overflow: 'hidden',
                      background: '#ffffff',
                      cursor: 'pointer',
                      position: 'relative',
                      display: 'flex',
                      flexDirection: 'column',
                    }}
                    onClick={() => setHtmlPreviewState({ src: htmlItem.src, filename: htmlItem.filename })}
                    title={t('console.previewHtmlTitle')}
                  >
                    <div style={{
                      flex: 1,
                      overflow: 'hidden',
                      position: 'relative',
                      pointerEvents: 'none',
                    }}>
                      <iframe
                        src={htmlItem.src}
                        title={t('console.previewFrameTitle', { node: htmlItem.nodeId })}
                        sandbox="allow-scripts"
                        referrerPolicy="no-referrer"
                        loading="lazy"
                        style={{
                          width: '200%',
                          height: '200%',
                          border: 'none',
                          transform: 'scale(0.5)',
                          transformOrigin: 'top left',
                          pointerEvents: 'none',
                        }}
                      />
                    </div>
                    <div style={{
                      fontSize: 11,
                      color: 'var(--text)',
                      padding: '4px 8px',
                      borderTop: '1px solid var(--border)',
                      background: 'var(--surface)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      gap: 6,
                    }}>
                      <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        <Icon name="file" size={10} /> {htmlItem.filename}
                      </span>
                      <span style={{ fontSize: 9, color: 'var(--muted)' }}>{t('console.previewHtmlBadge')}</span>
                    </div>
                  </div>
                ))}
              </>
            )}
          </div>
        )}
        {tab === 'report' && (
          <ReportPanel history={history} t={t} />
        )}
      </div>
    </div>
  );
}
