# European UCSC public MariaDB server used by the pinned Galaxy wrappers.
db.host=genome-euro-mysql.soe.ucsc.edu
db.user=genomep
db.password=password
central.db=hgcentral
central.host=genome-euro-mysql.soe.ucsc.edu
central.user=genomep
central.password=password
gbdbLoc1=http://hgdownload.soe.ucsc.edu/gbdb/
forceTwoBit=on
